0 0 dataAuditErrors
2 0 # INFO: I/O PADS = C4(4 on 8) #
367 0 ERROR: CA(net) not covered by CA(drawing) found!
370 0 ERROR: CABAR(net) not covered by CABAR(drawing) found!
373 0 ERROR: E2(net) not covered by E2(drawing) found!
376 0 ERROR: FT(net) not covered by FT(drawing) found!
379 0 ERROR: NS(net) not covered by NS(drawing) found!
382 0 ERROR: NW(net) not covered by NW(drawing) found!
385 0 ERROR: V1(net) not covered by V1(drawing) found!
388 0 ERROR: V1BAR(net) not covered by V1BAR(drawing) found!
391 0 ERROR: V2(net) not covered by V2(drawing) found!
394 0 ERROR: V2BAR(net) not covered by V2BAR(drawing) found!
397 0 ERROR: V3(net) not covered by V3(drawing) found!
400 0 ERROR: V3BAR(net) not covered by V3BAR(drawing) found!
403 0 ERROR: V4(net) not covered by V4(drawing) found!
406 0 ERROR: V4BAR(net) not covered by V4BAR(drawing) found!
409 0 ERROR: V5(net) not covered by V5(drawing) found!
412 0 ERROR: V5BAR(net) not covered by V5BAR(drawing) found!
415 0 ERROR: AM(net or pin) not covered by AM(drawing) found!
418 0 ERROR: DV(net or pin) not covered by DV(drawing) found!
421 0 ERROR: E1(net or pin) not covered by E1(drawing) found!
424 0 ERROR: LV(net or pin) not covered by LV(drawing) found!
427 0 ERROR: M1(net or pin) not covered by M1(drawing) found!
430 0 ERROR: M2(net or pin) not covered by M2(drawing) found!
433 0 ERROR: M3(net or pin) not covered by M3(drawing) found!
436 0 ERROR: M4(net or pin) not covered by M4(drawing) found!
439 0 ERROR: M5(net or pin) not covered by M5(drawing) found!
442 0 ERROR: MA(net or pin) not covered by MA(drawing) found!
445 0 ERROR: ML(net or pin) not covered by ML(drawing) found!
448 0 ERROR: MT(net or pin) not covered by MT(drawing) found!
450 0 ERROR: NW(net or pin) not covered by NW(drawing) found!
453 0 ERROR: RX(net or pin) not covered by RX(drawing) found!
456 0 ERROR: PC(net) not covered by PC(drawing) found!
460 0 ERROR: PC(pin) not covered by PC(drawing) found!
461 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (BF)
462 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (BH)
463 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (BN)
464 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (DE)
465 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (DF)
466 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (PH)
467 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (AMFILL)
468 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (E1FILL)
469 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (M1FILL)
470 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (M2FILL)
471 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (M3FILL)
472 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (M4FILL)
473 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (M5FILL)
474 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (MAFILL)
475 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (MLFILL)
476 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (MTFILL)
477 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (PCFILL)
478 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (RXFILL)
481 0 GRPN001: Shape straddling LOGOBND found! (ZEROVT)
482 0 GRPN001: Shape straddling LOGOBND found! (FT)
484 0 GRPN001: Shape straddling LOGOBND found! (FRBAR)
485 0 GRPN001: Shape straddling LOGOBND found! (AM)
486 0 GRPN001: Shape straddling LOGOBND found! (MA)
487 0 GRPN001: Shape straddling LOGOBND found! (E1)
488 0 GRPN001: Shape straddling LOGOBND found! (E2)
489 0 GRPN001: Shape straddling LOGOBND found! (ML)
491 0 GRPN001: Shape straddling LOGOBND found! (BB)
492 0 GRPN001: Shape straddling LOGOBND found! (BF)
494 0 GRPN001: Shape straddling LOGOBND found! (BFMOAT)
495 0 GRPN001: Shape straddling LOGOBND found! (BH)
496 0 GRPN001: Shape straddling LOGOBND found! (BN)
498 0 GRPN001: Shape straddling LOGOBND found! (BP)
500 0 GRPN001: Shape straddling LOGOBND found! (BP2ND)
501 0 GRPN001: Shape straddling LOGOBND found! (CA)
502 0 GRPN001: Shape straddling LOGOBND found! (CABAR)
504 0 GRPN001: Shape straddling LOGOBND found! (CAP)
505 0 GRPN001: Shape straddling LOGOBND found! (DE)
506 0 GRPN001: Shape straddling LOGOBND found! (DF)
507 0 WARNING: 5V_FET NOT RUN!
508 0 GRPN001: Shape straddling LOGOBND found! (TG)
510 0 GRPN001: Shape straddling LOGOBND found! (DG)
512 0 GRPN001: Shape straddling LOGOBND found! (DI)
514 0 GRPN001: Shape straddling LOGOBND found! (HT)
516 0 GRPN001: Shape straddling LOGOBND found! (K1)
517 0 GRPN001: Shape straddling LOGOBND found! (M1)
519 0 GRPN001: Shape straddling LOGOBND found! (M1CHEXCL)
520 0 GRPN001: Shape straddling LOGOBND found! (M2)
521 0 GRPN001: Shape straddling LOGOBND found! (M3)
522 0 GRPN001: Shape straddling LOGOBND found! (M4)
523 0 GRPN001: Shape straddling LOGOBND found! (M5)
525 0 GRPN001: Shape straddling LOGOBND found! (MIM_HK)
527 0 GRPN001: Shape straddling LOGOBND found! (MIM_HD)
529 0 GRPN001: Shape straddling LOGOBND found! (MOSVAR)
530 0 GRPN001: Shape straddling LOGOBND found! (MT)
531 0 GRPN001: Shape straddling LOGOBND found! (NS)
532 0 GRPN001: Shape straddling LOGOBND found! (NW)
534 0 GRPN001: Shape straddling LOGOBND found! (NWASP)
536 0 GRPN001: Shape straddling LOGOBND found! (OP)
537 0 GRPN001: Shape straddling LOGOBND found! (PC)
539 0 GRPN001: Shape straddling LOGOBND found! (PCING)
541 0 GRPN001: Shape straddling LOGOBND found! (PD)
543 0 GRPN001: Shape straddling LOGOBND found! (PCFUSE)
544 0 GRPN001: Shape straddling LOGOBND found! (PH)
546 0 GRPN001: Shape straddling LOGOBND found! (PI)
548 0 GRPN001: Shape straddling LOGOBND found! (QT)
550 0 GRPN001: Shape straddling LOGOBND found! (RN)
552 0 GRPN001: Shape straddling LOGOBND found! (RP)
554 0 GRPN001: Shape straddling LOGOBND found! (RR)
556 0 GRPN001: Shape straddling LOGOBND found! (PR)
558 0 GRPN001: Shape straddling LOGOBND found! (NR)
559 0 GRPN001: Shape straddling LOGOBND found! (RX)
560 0 GRPN001: Shape straddling LOGOBND found! (V1)
561 0 GRPN001: Shape straddling LOGOBND found! (V1BAR)
562 0 GRPN001: Shape straddling LOGOBND found! (V2)
563 0 GRPN001: Shape straddling LOGOBND found! (V2BAR)
564 0 GRPN001: Shape straddling LOGOBND found! (V3)
565 0 GRPN001: Shape straddling LOGOBND found! (V3BAR)
566 0 GRPN001: Shape straddling LOGOBND found! (V4)
567 0 GRPN001: Shape straddling LOGOBND found! (V4BAR)
568 0 GRPN001: Shape straddling LOGOBND found! (V5)
569 0 GRPN001: Shape straddling LOGOBND found! (V5BAR)
571 0 GRPN001: Shape straddling LOGOBND found! (dgv      )
573 0 GRPN001: Shape straddling LOGOBND found! (lvdummy  )
575 0 GRPN001: Shape straddling LOGOBND found! (esd_cdm  )
577 0 GRPN001: Shape straddling LOGOBND found! (c4lv     )
579 0 GRPN001: Shape straddling LOGOBND found! (dipi     )
580 0 GRPN001: Shape straddling LOGOBND found! (grlogic  )
582 0 GRPN001: Shape straddling LOGOBND found! (fltgate  )
584 0 GRPN001: Shape straddling LOGOBND found! (wvr      )
586 0 GRPN001: Shape straddling LOGOBND found! (sblk     )
588 0 GRPN001: Shape straddling LOGOBND found! (JD)
590 0 GRPN001: Shape straddling LOGOBND found! (ind_filt )
592 0 GRPN001: Shape straddling LOGOBND found! (bondpad  )
594 0 GRPN001: Shape straddling LOGOBND found! (tline_am )
596 0 GRPN001: Shape straddling LOGOBND found! (tline_ma )
598 0 GRPN001: Shape straddling LOGOBND found! (tline_ml )
600 0 GRPN001: Shape straddling LOGOBND found! (lowcrnt  )
602 0 GRPN001: Shape straddling LOGOBND found! (vncapm1  )
604 0 GRPN001: Shape straddling LOGOBND found! (vncapm2  )
606 0 GRPN001: Shape straddling LOGOBND found! (vncapm3  )
608 0 GRPN001: Shape straddling LOGOBND found! (vncapm4  )
610 0 GRPN001: Shape straddling LOGOBND found! (vncapm5  )
612 0 GRPN001: Shape straddling LOGOBND found! (vncapmt  )
614 0 GRPN001: Shape straddling LOGOBND found! (vncapcnt )
616 0 GRPN001: Shape straddling LOGOBND found! (vncapparm)
618 0 GRPN001: Shape straddling LOGOBND found! (rx5v     )
620 0 GRPN001: Shape straddling LOGOBND found! (reshv    )
622 0 GRPN001: Shape straddling LOGOBND found! (5vonly   )
624 0 GRPN001: Shape straddling LOGOBND found! (bipolar  )
626 0 GRPN001: Shape straddling LOGOBND found! (schky    )
628 0 GRPN001: Shape straddling LOGOBND found! (scgate   )
630 0 GRPN001: Shape straddling LOGOBND found! (plyoncrk )
636 0 GRPN203: CA to CA space (logo) >= 0.400 um.
639 0 GRPN502: M1 to M1 space (logo) >= 0.400 um.
651 0 GRPN553: V1 to V1 space (logo) >= 0.400 um.
653 0 GRPN553: V2 to V2 space (logo) >= 0.400 um.
655 0 GRPN553: V3 to V3 space (logo) >= 0.400 um.
657 0 GRPN553: V4 to V4 space (logo) >= 0.400 um.
659 0 GRPN553: V5 to V5 space (logo) >= 0.400 um.
666 0 GRPN602: M2 to M2 space (logo) >= 0.400 um.
668 0 GRPN602: M3 to M3 space (logo) >= 0.400 um.
670 0 GRPN602: M4 to M4 space (logo) >= 0.400 um.
672 0 GRPN602: M5 to M5 space (logo) >= 0.400 um.
674 0 GRPN602: MT to MT space (logo) >= 0.400 um.
677 0 GRPN907: DV over LOGOBND found!
679 0 GRPN907: LV over LOGOBND found!
682 0 GRPN907: TV over LOGOBND found!
721 0 # INFO: 3 Level Metal (M1+MT+AM) #
722 0 # INFO: 4 Level Metal (M1+M2+MT+AM) #
723 0 # INFO: 5 Level Metal (M1+M2+M3+MT+AM) #
724 0 # INFO: 6 Level Metal (M1+M2+M3+M4+MT+AM) #
725 0 # INFO: 7 Level Metal (M1+M2+M3+M4+M5+MT+AM) #
729 0 # INFO: 4 Level Metal (M1+MT+E1+MA) #
730 0 # INFO: 5 Level Metal (M1+M2+MT+E1+MA) #
731 0 # INFO: 6 Level Metal (M1+M2+M3+MT+E1+MA) #
732 0 # INFO: 7 Level Metal (M1+M2+M3+M4+MT+E1+MA) #
733 0 # INFO: 8 Level Metal (M1+M2+M3+M4+M5+MT+E1+MA) #
737 0 # INFO: 3 Level Metal (M1+MT+ML) #
738 0 # INFO: 4 Level Metal (M1+M2+MT+ML) #
739 0 # INFO: 5 Level Metal (M1+M2+M3+MT+ML) #
740 0 # INFO: 6 Level Metal (M1+M2+M3+M4+MT+ML) #
741 0 # INFO: 7 Level Metal (M1+M2+M3+M4+M5+MT+ML) #
745 0 # INFO: 7 Level Metal (M1+M2+M3+M4+M5+MT+MZ) #
756 0 WARNING: MULTIPLE LAST METAL LEVELS FOUND! (AM or MA or ML or MZ)
759 0 # WARNING: LV and DV are present in same Design. It is prohibited!
947 0 GRS1: Off-Grid path centerline found!_am
948 0 GRS1: Off-Grid path centerline found!_as
949 0 GRS1: Off-Grid path centerline found!_bb
950 0 GRS1: Off-Grid path centerline found!_bf
951 0 GRS1: Off-Grid path centerline found!_bh
952 0 GRS1: Off-Grid path centerline found!_bn
953 0 GRS1: Off-Grid path centerline found!_bp
954 0 GRS1: Off-Grid path centerline found!_bp2nd
955 0 GRS1: Off-Grid path centerline found!_bt
956 0 GRS1: Off-Grid path centerline found!_ca
957 0 GRS1: Off-Grid path centerline found!_cabar
958 0 GRS1: Off-Grid path centerline found!_de
959 0 GRS1: Off-Grid path centerline found!_df
960 0 GRS1: Off-Grid path centerline found!_dg
961 0 GRS1: Off-Grid path centerline found!_dv
962 0 GRS1: Off-Grid path centerline found!_e1
963 0 GRS1: Off-Grid path centerline found!_e2
964 0 GRS1: Off-Grid path centerline found!_ft
965 0 GRS1: Off-Grid path centerline found!_ftbar
966 0 GRS1: Off-Grid path centerline found!_hr
967 0 GRS1: Off-Grid path centerline found!_ht
968 0 GRS1: Off-Grid path centerline found!_jc
969 0 GRS1: Off-Grid path centerline found!_jd
970 0 GRS1: Off-Grid path centerline found!_js
971 0 GRS1: Off-Grid path centerline found!_k1
972 0 GRS1: Off-Grid path centerline found!_lv
973 0 GRS1: Off-Grid path centerline found!_m1
974 0 GRS1: Off-Grid path centerline found!_m2
975 0 GRS1: Off-Grid path centerline found!_m3
976 0 GRS1: Off-Grid path centerline found!_m4
977 0 GRS1: Off-Grid path centerline found!_m5
978 0 GRS1: Off-Grid path centerline found!_ma
979 0 GRS1: Off-Grid path centerline found!_ml
980 0 GRS1: Off-Grid path centerline found!_mt
981 0 GRS1: Off-Grid path centerline found!_mz
982 0 GRS1: Off-Grid path centerline found!_nr
983 0 GRS1: Off-Grid path centerline found!_ns
984 0 GRS1: Off-Grid path centerline found!_nv
985 0 GRS1: Off-Grid path centerline found!_nw
986 0 GRS1: Off-Grid path centerline found!_op
987 0 GRS1: Off-Grid path centerline found!_pv
988 0 GRS1: Off-Grid path centerline found!_pc
989 0 GRS1: Off-Grid path centerline found!_pcfuse
990 0 GRS1: Off-Grid path centerline found!_pcing
991 0 GRS1: Off-Grid path centerline found!_pd
992 0 GRS1: Off-Grid path centerline found!_ph
993 0 GRS1: Off-Grid path centerline found!_pi
994 0 GRS1: Off-Grid path centerline found!_pr
995 0 GRS1: Off-Grid path centerline found!_qt
996 0 GRS1: Off-Grid path centerline found!_rn
997 0 GRS1: Off-Grid path centerline found!_rp
998 0 GRS1: Off-Grid path centerline found!_rr
999 0 GRS1: Off-Grid path centerline found!_rx
1000 0 GRS1: Off-Grid path centerline found!_te
1001 0 GRS1: Off-Grid path centerline found!_tf
1002 0 GRS1: Off-Grid path centerline found!_tg
1003 0 GRS1: Off-Grid path centerline found!_ti
1004 0 GRS1: Off-Grid path centerline found!_tv
1005 0 GRS1: Off-Grid path centerline found!_v1
1006 0 GRS1: Off-Grid path centerline found!_v1bar
1007 0 GRS1: Off-Grid path centerline found!_v2
1008 0 GRS1: Off-Grid path centerline found!_v2bar
1009 0 GRS1: Off-Grid path centerline found!_v3
1010 0 GRS1: Off-Grid path centerline found!_v3bar
1011 0 GRS1: Off-Grid path centerline found!_v4
1012 0 GRS1: Off-Grid path centerline found!_v4bar
1013 0 GRS1: Off-Grid path centerline found!_v5
1014 0 GRS1: Off-Grid path centerline found!_v5bar
1015 0 GRS1: Off-Grid path centerline found!_amexclud
1016 0 GRS1: Off-Grid path centerline found!_bfcus
1017 0 GRS1: Off-Grid path centerline found!_bfmoat
1018 0 GRS1: Off-Grid path centerline found!_bipolar
1019 0 GRS1: Off-Grid path centerline found!_bondpad
1020 0 GRS1: Off-Grid path centerline found!_bperi
1021 0 GRS1: Off-Grid path centerline found!_btcus
1022 0 GRS1: Off-Grid path centerline found!_c4lv
1023 0 GRS1: Off-Grid path centerline found!_cap
1024 0 GRS1: Off-Grid path centerline found!_chipedge
1025 0 GRS1: Off-Grid path centerline found!_crackstop
1026 0 GRS1: Off-Grid path centerline found!_cupillar
1027 0 GRS1: Off-Grid path centerline found!_dcap
1028 0 GRS1: Off-Grid path centerline found!_dgv
1029 0 GRS1: Off-Grid path centerline found!_di
1030 0 GRS1: Off-Grid path centerline found!_dipi
1031 0 GRS1: Off-Grid path centerline found!_dns_sram
1032 0 GRS1: Off-Grid path centerline found!_ds_match
1033 0 GRS1: Off-Grid path centerline found!_e1_coil
1034 0 GRS1: Off-Grid path centerline found!_e1exclud
1035 0 GRS1: Off-Grid path centerline found!_esd_cdm
1036 0 GRS1: Off-Grid path centerline found!_esdrf
1037 0 GRS1: Off-Grid path centerline found!_esdummy
1038 0 GRS1: Off-Grid path centerline found!_fivevonly
1039 0 GRS1: Off-Grid path centerline found!_fltgate
1040 0 GRS1: Off-Grid path centerline found!_grlogic
1041 0 GRS1: Off-Grid path centerline found!_guardrng
1042 0 GRS1: Off-Grid path centerline found!_guardedge
1043 0 GRS1: Off-Grid path centerline found!_hrcus
1044 0 GRS1: Off-Grid path centerline found!_ind_filt
1045 0 GRS1: Off-Grid path centerline found!_logobnd
1046 0 GRS1: Off-Grid path centerline found!_lowcrnt
1047 0 GRS1: Off-Grid path centerline found!_lvdummy
1048 0 GRS1: Off-Grid path centerline found!_m1chexcl
1049 0 GRS1: Off-Grid path centerline found!_m1exclud
1050 0 GRS1: Off-Grid path centerline found!_m2exclud
1051 0 GRS1: Off-Grid path centerline found!_m3_coil
1052 0 GRS1: Off-Grid path centerline found!_m3exclud
1053 0 GRS1: Off-Grid path centerline found!_m4_coil
1054 0 GRS1: Off-Grid path centerline found!_m4exclud
1055 0 GRS1: Off-Grid path centerline found!_m5_coil
1056 0 GRS1: Off-Grid path centerline found!_m5exclud
1057 0 GRS1: Off-Grid path centerline found!_maexclud
1058 0 GRS1: Off-Grid path centerline found!_mimhd
1059 0 GRS1: Off-Grid path centerline found!_mimhk
1060 0 GRS1: Off-Grid path centerline found!_mlexclud
1061 0 GRS1: Off-Grid path centerline found!_mosvar
1062 0 GRS1: Off-Grid path centerline found!_mpw_edge
1063 0 GRS1: Off-Grid path centerline found!_mt_coil
1064 0 GRS1: Off-Grid path centerline found!_mtexclud
1065 0 GRS1: Off-Grid path centerline found!_mzexclud
1066 0 GRS1: Off-Grid path centerline found!_nixbf
1067 0 GRS1: Off-Grid path centerline found!_nixbt
1068 0 GRS1: Off-Grid path centerline found!_nixhr
1069 0 GRS1: Off-Grid path centerline found!_nohr
1070 0 GRS1: Off-Grid path centerline found!_noibmcrackstop
1071 0 GRS1: Off-Grid path centerline found!_nosubc
1072 0 GRS1: Off-Grid path centerline found!_nwasp
1073 0 GRS1: Off-Grid path centerline found!_outlinefill
1074 0 GRS1: Off-Grid path centerline found!_padfiltr
1075 0 GRS1: Off-Grid path centerline found!_pcexclud
1076 0 GRS1: Off-Grid path centerline found!_plyoncrk
1077 0 GRS1: Off-Grid path centerline found!_reshv
1078 0 GRS1: Off-Grid path centerline found!_rf_modfill
1079 0 GRS1: Off-Grid path centerline found!_rx5v
1080 0 GRS1: Off-Grid path centerline found!_rxexclud
1081 0 GRS1: Off-Grid path centerline found!_sblk
1082 0 GRS1: Off-Grid path centerline found!_scgate
1083 0 GRS1: Off-Grid path centerline found!_schky
1084 0 GRS1: Off-Grid path centerline found!_seg_gring
1085 0 GRS1: Off-Grid path centerline found!_tline_am
1086 0 GRS1: Off-Grid path centerline found!_tline_ma
1087 0 GRS1: Off-Grid path centerline found!_tline_ml
1088 0 GRS1: Off-Grid path centerline found!_trans
1089 0 GRS1: Off-Grid path centerline found!_vncapcount
1090 0 GRS1: Off-Grid path centerline found!_vncapm1
1091 0 GRS1: Off-Grid path centerline found!_vncapm2
1092 0 GRS1: Off-Grid path centerline found!_vncapm3
1093 0 GRS1: Off-Grid path centerline found!_vncapm4
1094 0 GRS1: Off-Grid path centerline found!_vncapm5
1095 0 GRS1: Off-Grid path centerline found!_vncapmt
1096 0 GRS1: Off-Grid path centerline found!_vncapparm
1097 0 GRS1: Off-Grid path centerline found!_vtsens
1098 0 GRS1: Off-Grid path centerline found!_wellasp
1099 0 GRS1: Off-Grid path centerline found!_wvr
1100 0 GRS1: Off-Grid path centerline found!_zerovt
1101 0 GRS1: Off-Grid path centerline found!_ca_net
1102 0 GRS1: Off-Grid path centerline found!_cab_net
1103 0 GRS1: Off-Grid path centerline found!_e2_net
1104 0 GRS1: Off-Grid path centerline found!_ft_net
1105 0 GRS1: Off-Grid path centerline found!_ns_net
1106 0 GRS1: Off-Grid path centerline found!_nw_net
1107 0 GRS1: Off-Grid path centerline found!_pc_net
1108 0 GRS1: Off-Grid path centerline found!_v1_net
1109 0 GRS1: Off-Grid path centerline found!_v1b_net
1110 0 GRS1: Off-Grid path centerline found!_v2_net
1111 0 GRS1: Off-Grid path centerline found!_v2b_net
1112 0 GRS1: Off-Grid path centerline found!_v3_net
1113 0 GRS1: Off-Grid path centerline found!_v3b_net
1114 0 GRS1: Off-Grid path centerline found!_v4_net
1115 0 GRS1: Off-Grid path centerline found!_v4b_net
1116 0 GRS1: Off-Grid path centerline found!_v5_net
1117 0 GRS1: Off-Grid path centerline found!_v5b_net
1118 0 GRS1: Off-Grid path centerline found!_tv_net
1119 0 GRS1: Off-Grid path centerline found!_am_ntpn
1120 0 GRS1: Off-Grid path centerline found!_dv_ntpn
1121 0 GRS1: Off-Grid path centerline found!_e1_ntpn
1122 0 GRS1: Off-Grid path centerline found!_lv_ntpn
1123 0 GRS1: Off-Grid path centerline found!_m1_ntpn
1124 0 GRS1: Off-Grid path centerline found!_m2_ntpn
1125 0 GRS1: Off-Grid path centerline found!_m3_ntpn
1126 0 GRS1: Off-Grid path centerline found!_m4_ntpn
1127 0 GRS1: Off-Grid path centerline found!_m5_ntpn
1128 0 GRS1: Off-Grid path centerline found!_ma_ntpn
1129 0 GRS1: Off-Grid path centerline found!_ml_ntpn
1130 0 GRS1: Off-Grid path centerline found!_mt_ntpn
1131 0 GRS1: Off-Grid path centerline found!_nw_ntpn
1132 0 GRS1: Off-Grid path centerline found!_rx_ntpn
1133 0 GRS1: Off-Grid path centerline found!_pc_pin
1134 0 GRS1: Off-Grid path centerline found!_amFill
1135 0 GRS1: Off-Grid path centerline found!_e1Fill
1136 0 GRS1: Off-Grid path centerline found!_m1Fill
1137 0 GRS1: Off-Grid path centerline found!_m2Fill
1138 0 GRS1: Off-Grid path centerline found!_m3Fill
1139 0 GRS1: Off-Grid path centerline found!_m4Fill
1140 0 GRS1: Off-Grid path centerline found!_m5Fill
1141 0 GRS1: Off-Grid path centerline found!_maFill
1142 0 GRS1: Off-Grid path centerline found!_mlFill
1143 0 GRS1: Off-Grid path centerline found!_mtFill
1144 0 GRS1: Off-Grid path centerline found!_pcFill
1145 0 GRS1: Off-Grid path centerline found!_rxFill
1146 0 GRS1: Off-Grid path centerline found!_m1exclud_rl03
1147 0 GRS1: Off-Grid path centerline found!_m2exclud_rl03
1148 0 GRS1: Off-Grid path centerline found!_m3exclud_rl03
1149 0 GRS1: Off-Grid path centerline found!_m4exclud_rl03
1150 0 GRS1: Off-Grid path centerline found!_m5exclud_rl03
1153 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (AM)
1155 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (AM)(unmerged)
1156 0 GRS2: Shape with acute angles found! (AM) (internal)
1157 0 GRS2: Shape with acute angles found! (AM) (external)
1161 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (AM)
1162 0 GRS10: Text data on mask build layer found! (AM)
1165 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (AS)
1167 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (AS)(unmerged)
1168 0 GRS2: Shape with acute angles found! (AS) (internal)
1169 0 GRS2: Shape with acute angles found! (AS) (external)
1173 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (AS)
1174 0 GRS10: Text data on mask build layer found! (AS)
1177 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (BB)
1179 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (BB)(unmerged)
1180 0 GRS2: Shape with acute angles found! (BB) (internal)
1181 0 GRS2: Shape with acute angles found! (BB) (external)
1185 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (BB)
1186 0 GRS10: Text data on mask build layer found! (BB)
1189 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (BFMOAT)
1191 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (BFMOAT)(unmerged)
1192 0 GRS2: Shape with acute angles found! (BFMOAT) (internal)
1193 0 GRS2: Shape with acute angles found! (BFMOAT) (external)
1197 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (BFMOAT)
1198 0 GRS10: Text data on mask build layer found! (BFMOAT)
1201 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (BONDPAD)
1203 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (BONDPAD)(unmerged)
1204 0 GRS2: Shape with acute angles found! (BONDPAD) (internal)
1205 0 GRS2: Shape with acute angles found! (BONDPAD) (external)
1209 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (BONDPAD)
1210 0 GRS10: Text data on mask build layer found! (BONDPAD)
1213 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (BP)
1215 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (BP)(unmerged)
1216 0 GRS2: Shape with acute angles found! (BP) (internal)
1217 0 GRS2: Shape with acute angles found! (BP) (external)
1221 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (BP)
1222 0 GRS10: Text data on mask build layer found! (BP)
1225 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (BPERI)
1227 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (BPERI)(unmerged)
1229 0 GRS2: Shape with acute angles found! (BPERI) (internal)
1231 0 GRS2: Shape with acute angles found! (BPERI) (external)
1237 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (BPERI)
1238 0 GRS10: Text data on mask build layer found! (BPERI)
1241 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (BP2ND)
1243 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (BP2ND)(unmerged)
1244 0 GRS2: Shape with acute angles found! (BP2ND) (internal)
1245 0 GRS2: Shape with acute angles found! (BP2ND) (external)
1249 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (BP2ND)
1250 0 GRS10: Text data on mask build layer found! (BP2ND)
1253 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (CA)
1255 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (CA)(unmerged)
1256 0 GRS2: Shape with acute angles found! (CA) (internal)
1257 0 GRS2: Shape with acute angles found! (CA) (external)
1261 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (CA)
1262 0 GRS10: Text data on mask build layer found! (CA)
1265 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (CABAR)
1267 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (CABAR)(unmerged)
1268 0 GRS2: Shape with acute angles found! (CABAR) (internal)
1269 0 GRS2: Shape with acute angles found! (CABAR) (external)
1273 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (CABAR)
1274 0 GRS10: Text data on mask build layer found! (CABAR)
1277 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (CAP)
1279 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (CAP)(unmerged)
1280 0 GRS2: Shape with acute angles found! (CAP) (internal)
1281 0 GRS2: Shape with acute angles found! (CAP) (external)
1285 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (CAP)
1286 0 GRS10: Text data on mask build layer found! (CAP)
1289 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (CHIPEDGE)
1291 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (CHIPEDGE)(unmerged)
1292 0 GRS2: Shape with acute angles found! (CHIPEDGE) (internal)
1293 0 GRS2: Shape with acute angles found! (CHIPEDGE) (external)
1297 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (CHIPEDGE)
1298 0 GRS10: Text data on mask build layer found! (CHIPEDGE)
1301 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (TG)
1303 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (TG)(unmerged)
1304 0 GRS2: Shape with acute angles found! (TG) (internal)
1305 0 GRS2: Shape with acute angles found! (TG) (external)
1309 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (TG)
1310 0 GRS10: Text data on mask build layer found! (TG)
1313 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (DG)
1315 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (DG)(unmerged)
1316 0 GRS2: Shape with acute angles found! (DG) (internal)
1317 0 GRS2: Shape with acute angles found! (DG) (external)
1321 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (DG)
1322 0 GRS10: Text data on mask build layer found! (DG)
1325 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (DV)
1327 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (DV)(unmerged)
1328 0 GRS2: Shape with acute angles found! (DV) (internal)
1329 0 GRS2: Shape with acute angles found! (DV) (external)
1333 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (DV)
1334 0 GRS10: Text data on mask build layer found! (DV)
1337 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (E1)
1339 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (E1)(unmerged)
1340 0 GRS2: Shape with acute angles found! (E1) (internal)
1341 0 GRS2: Shape with acute angles found! (E1) (external)
1345 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (E1)
1346 0 GRS10: Text data on mask build layer found! (E1)
1349 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (E2)
1351 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (E2)(unmerged)
1352 0 GRS2: Shape with acute angles found! (E2) (internal)
1353 0 GRS2: Shape with acute angles found! (E2) (external)
1357 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (E2)
1358 0 GRS10: Text data on mask build layer found! (E2)
1361 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (FT)
1363 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (FT)(unmerged)
1364 0 GRS2: Shape with acute angles found! (FT) (internal)
1365 0 GRS2: Shape with acute angles found! (FT) (external)
1369 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (FT)
1370 0 GRS10: Text data on mask build layer found! (FT)
1373 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (FTBAR)
1375 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (FTBAR)(unmerged)
1376 0 GRS2: Shape with acute angles found! (FTBAR) (internal)
1377 0 GRS2: Shape with acute angles found! (FTBAR) (external)
1381 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (FTBAR)
1382 0 GRS10: Text data on mask build layer found! (FTBAR)
1385 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (HT)
1387 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (HT)(unmerged)
1388 0 GRS2: Shape with acute angles found! (HT) (internal)
1389 0 GRS2: Shape with acute angles found! (HT) (external)
1393 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (HT)
1394 0 GRS10: Text data on mask build layer found! (HT)
1397 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (IND_FILT)
1399 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (IND_FILT)(unmerged)
1400 0 GRS2: Shape with acute angles found! (IND_FILT) (internal)
1401 0 GRS2: Shape with acute angles found! (IND_FILT) (external)
1405 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (IND_FILT)
1406 0 GRS10: Text data on mask build layer found! (IND_FILT)
1409 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (K1)
1411 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (K1)(unmerged)
1412 0 GRS2: Shape with acute angles found! (K1) (internal)
1413 0 GRS2: Shape with acute angles found! (K1) (external)
1417 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (K1)
1418 0 GRS10: Text data on mask build layer found! (K1)
1421 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (LOGOBND)
1423 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (LOGOBND)(unmerged)
1424 0 GRS2: Shape with acute angles found! (LOGOBND) (internal)
1425 0 GRS2: Shape with acute angles found! (LOGOBND) (external)
1429 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (LOGOBND)
1430 0 GRS10: Text data on mask build layer found! (LOGOBND)
1433 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (LV)
1435 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (LV)(unmerged)
1436 0 GRS2: Shape with acute angles found! (LV) (internal)
1437 0 GRS2: Shape with acute angles found! (LV) (external)
1441 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (LV)
1442 0 GRS10: Text data on mask build layer found! (LV)
1445 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (LVDUMMY)
1447 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (LVDUMMY)(unmerged)
1448 0 GRS2: Shape with acute angles found! (LVDUMMY) (internal)
1449 0 GRS2: Shape with acute angles found! (LVDUMMY) (external)
1453 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (LVDUMMY)
1454 0 GRS10: Text data on mask build layer found! (LVDUMMY)
1457 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (M1)
1459 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (M1)(unmerged)
1460 0 GRS2: Shape with acute angles found! (M1) (internal)
1461 0 GRS2: Shape with acute angles found! (M1) (external)
1465 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (M1)
1466 0 GRS10: Text data on mask build layer found! (M1)
1469 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (M2)
1471 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (M2)(unmerged)
1472 0 GRS2: Shape with acute angles found! (M2) (internal)
1473 0 GRS2: Shape with acute angles found! (M2) (external)
1477 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (M2)
1478 0 GRS10: Text data on mask build layer found! (M2)
1481 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (M3)
1483 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (M3)(unmerged)
1484 0 GRS2: Shape with acute angles found! (M3) (internal)
1485 0 GRS2: Shape with acute angles found! (M3) (external)
1489 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (M3)
1490 0 GRS10: Text data on mask build layer found! (M3)
1493 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (M4)
1495 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (M4)(unmerged)
1496 0 GRS2: Shape with acute angles found! (M4) (internal)
1497 0 GRS2: Shape with acute angles found! (M4) (external)
1501 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (M4)
1502 0 GRS10: Text data on mask build layer found! (M4)
1505 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (M5)
1507 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (M5)(unmerged)
1508 0 GRS2: Shape with acute angles found! (M5) (internal)
1509 0 GRS2: Shape with acute angles found! (M5) (external)
1513 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (M5)
1514 0 GRS10: Text data on mask build layer found! (M5)
1517 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (MA)
1519 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (MA)(unmerged)
1520 0 GRS2: Shape with acute angles found! (MA) (internal)
1521 0 GRS2: Shape with acute angles found! (MA) (external)
1525 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (MA)
1526 0 GRS10: Text data on mask build layer found! (MA)
1529 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (ML)
1531 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (ML)(unmerged)
1532 0 GRS2: Shape with acute angles found! (ML) (internal)
1533 0 GRS2: Shape with acute angles found! (ML) (external)
1537 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (ML)
1538 0 GRS10: Text data on mask build layer found! (ML)
1541 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (MOSVAR)
1543 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (MOSVAR)(unmerged)
1544 0 GRS2: Shape with acute angles found! (MOSVAR) (internal)
1545 0 GRS2: Shape with acute angles found! (MOSVAR) (external)
1549 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (MOSVAR)
1550 0 GRS10: Text data on mask build layer found! (MOSVAR)
1553 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (MT)
1555 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (MT)(unmerged)
1556 0 GRS2: Shape with acute angles found! (MT) (internal)
1557 0 GRS2: Shape with acute angles found! (MT) (external)
1561 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (MT)
1562 0 GRS10: Text data on mask build layer found! (MT)
1565 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (NS)
1567 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (NS)(unmerged)
1568 0 GRS2: Shape with acute angles found! (NS) (internal)
1569 0 GRS2: Shape with acute angles found! (NS) (external)
1573 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (NS)
1574 0 GRS10: Text data on mask build layer found! (NS)
1577 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (NW)
1579 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (NW)(unmerged)
1580 0 GRS2: Shape with acute angles found! (NW) (internal)
1581 0 GRS2: Shape with acute angles found! (NW) (external)
1585 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (NW)
1586 0 GRS10: Text data on mask build layer found! (NW)
1589 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (NWASP)
1591 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (NWASP)(unmerged)
1592 0 GRS2: Shape with acute angles found! (NWASP) (internal)
1593 0 GRS2: Shape with acute angles found! (NWASP) (external)
1597 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (NWASP)
1598 0 GRS10: Text data on mask build layer found! (NWASP)
1601 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (OP)
1603 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (OP)(unmerged)
1604 0 GRS2: Shape with acute angles found! (OP) (internal)
1605 0 GRS2: Shape with acute angles found! (OP) (external)
1609 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (OP)
1610 0 GRS10: Text data on mask build layer found! (OP)
1613 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (PI)
1615 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (PI)(unmerged)
1616 0 GRS2: Shape with acute angles found! (PI) (internal)
1617 0 GRS2: Shape with acute angles found! (PI) (external)
1621 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (PI)
1622 0 GRS10: Text data on mask build layer found! (PI)
1625 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (PC)
1627 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (PC)(unmerged)
1628 0 GRS2: Shape with acute angles found! (PC) (internal)
1629 0 GRS2: Shape with acute angles found! (PC) (external)
1633 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (PC)
1634 0 GRS10: Text data on mask build layer found! (PC)
1637 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (PCFUSE)
1639 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (PCFUSE)(unmerged)
1640 0 GRS2: Shape with acute angles found! (PCFUSE) (internal)
1641 0 GRS2: Shape with acute angles found! (PCFUSE) (external)
1645 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (PCFUSE)
1646 0 GRS10: Text data on mask build layer found! (PCFUSE)
1649 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (PCING)
1651 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (PCING)(unmerged)
1652 0 GRS2: Shape with acute angles found! (PCING) (internal)
1653 0 GRS2: Shape with acute angles found! (PCING) (external)
1657 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (PCING)
1658 0 GRS10: Text data on mask build layer found! (PCING)
1661 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (PD)
1663 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (PD)(unmerged)
1664 0 GRS2: Shape with acute angles found! (PD) (internal)
1665 0 GRS2: Shape with acute angles found! (PD) (external)
1669 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (PD)
1670 0 GRS10: Text data on mask build layer found! (PD)
1673 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (QT)
1675 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (QT)(unmerged)
1676 0 GRS2: Shape with acute angles found! (QT) (internal)
1677 0 GRS2: Shape with acute angles found! (QT) (external)
1681 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (QT)
1682 0 GRS10: Text data on mask build layer found! (QT)
1685 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (RN)
1687 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (RN)(unmerged)
1688 0 GRS2: Shape with acute angles found! (RN) (internal)
1689 0 GRS2: Shape with acute angles found! (RN) (external)
1693 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (RN)
1694 0 GRS10: Text data on mask build layer found! (RN)
1697 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (RP)
1699 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (RP)(unmerged)
1700 0 GRS2: Shape with acute angles found! (RP) (internal)
1701 0 GRS2: Shape with acute angles found! (RP) (external)
1705 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (RP)
1706 0 GRS10: Text data on mask build layer found! (RP)
1709 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (RR)
1711 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (RR)(unmerged)
1712 0 GRS2: Shape with acute angles found! (RR) (internal)
1713 0 GRS2: Shape with acute angles found! (RR) (external)
1717 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (RR)
1718 0 GRS10: Text data on mask build layer found! (RR)
1721 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (RX)
1723 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (RX)(unmerged)
1724 0 GRS2: Shape with acute angles found! (RX) (internal)
1725 0 GRS2: Shape with acute angles found! (RX) (external)
1729 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (RX)
1730 0 GRS10: Text data on mask build layer found! (RX)
1733 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (RX5V)
1735 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (RX5V)(unmerged)
1736 0 GRS2: Shape with acute angles found! (RX5V) (internal)
1737 0 GRS2: Shape with acute angles found! (RX5V) (external)
1741 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (RX5V)
1742 0 GRS10: Text data on mask build layer found! (RX5V)
1745 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (TLINE_AM)
1747 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (TLINE_AM)(unmerged)
1748 0 GRS2: Shape with acute angles found! (TLINE_AM) (internal)
1749 0 GRS2: Shape with acute angles found! (TLINE_AM) (external)
1753 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (TLINE_AM)
1754 0 GRS10: Text data on mask build layer found! (TLINE_AM)
1757 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (TLINE_MA)
1759 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (TLINE_MA)(unmerged)
1760 0 GRS2: Shape with acute angles found! (TLINE_MA) (internal)
1761 0 GRS2: Shape with acute angles found! (TLINE_MA) (external)
1765 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (TLINE_MA)
1766 0 GRS10: Text data on mask build layer found! (TLINE_MA)
1769 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (TLINE_ML)
1771 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (TLINE_ML)(unmerged)
1772 0 GRS2: Shape with acute angles found! (TLINE_ML) (internal)
1773 0 GRS2: Shape with acute angles found! (TLINE_ML) (external)
1777 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (TLINE_ML)
1778 0 GRS10: Text data on mask build layer found! (TLINE_ML)
1781 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V1)
1783 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V1)(unmerged)
1784 0 GRS2: Shape with acute angles found! (V1) (internal)
1785 0 GRS2: Shape with acute angles found! (V1) (external)
1789 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (V1)
1790 0 GRS10: Text data on mask build layer found! (V1)
1793 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V1BAR)
1795 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V1BAR)(unmerged)
1796 0 GRS2: Shape with acute angles found! (V1BAR) (internal)
1797 0 GRS2: Shape with acute angles found! (V1BAR) (external)
1801 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (V1BAR)
1802 0 GRS10: Text data on mask build layer found! (V1BAR)
1805 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V2)
1807 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V2)(unmerged)
1808 0 GRS2: Shape with acute angles found! (V2) (internal)
1809 0 GRS2: Shape with acute angles found! (V2) (external)
1813 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (V2)
1814 0 GRS10: Text data on mask build layer found! (V2)
1817 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V2BAR)
1819 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V2BAR)(unmerged)
1820 0 GRS2: Shape with acute angles found! (V2BAR) (internal)
1821 0 GRS2: Shape with acute angles found! (V2BAR) (external)
1825 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (V2BAR)
1826 0 GRS10: Text data on mask build layer found! (V2BAR)
1829 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V3)
1831 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V3)(unmerged)
1832 0 GRS2: Shape with acute angles found! (V3) (internal)
1833 0 GRS2: Shape with acute angles found! (V3) (external)
1837 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (V3)
1838 0 GRS10: Text data on mask build layer found! (V3)
1841 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V3BAR)
1843 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V3BAR)(unmerged)
1844 0 GRS2: Shape with acute angles found! (V3BAR) (internal)
1845 0 GRS2: Shape with acute angles found! (V3BAR) (external)
1849 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (V3BAR)
1850 0 GRS10: Text data on mask build layer found! (V3BAR)
1853 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V4)
1855 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V4)(unmerged)
1856 0 GRS2: Shape with acute angles found! (V4) (internal)
1857 0 GRS2: Shape with acute angles found! (V4) (external)
1861 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (V4)
1862 0 GRS10: Text data on mask build layer found! (V4)
1865 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V4BAR)
1867 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V4BAR)(unmerged)
1868 0 GRS2: Shape with acute angles found! (V4BAR) (internal)
1869 0 GRS2: Shape with acute angles found! (V4BAR) (external)
1873 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (V4BAR)
1874 0 GRS10: Text data on mask build layer found! (V4BAR)
1877 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V5)
1879 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V5)(unmerged)
1880 0 GRS2: Shape with acute angles found! (V5) (internal)
1881 0 GRS2: Shape with acute angles found! (V5) (external)
1885 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (V5)
1886 0 GRS10: Text data on mask build layer found! (V5)
1889 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V5BAR)
1891 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (V5BAR)(unmerged)
1892 0 GRS2: Shape with acute angles found! (V5BAR) (internal)
1893 0 GRS2: Shape with acute angles found! (V5BAR) (external)
1897 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (V5BAR)
1898 0 GRS10: Text data on mask build layer found! (V5BAR)
1901 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (ZEROVT)
1903 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (ZEROVT)(unmerged)
1904 0 GRS2: Shape with acute angles found! (ZEROVT) (internal)
1905 0 GRS2: Shape with acute angles found! (ZEROVT) (external)
1909 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (ZEROVT)
1910 0 GRS10: Text data on mask build layer found! (ZEROVT)
1913 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (JC)
1915 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (JC)(unmerged)
1916 0 GRS2: Shape with acute angles found! (JC) (internal)
1917 0 GRS2: Shape with acute angles found! (JC) (external)
1921 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (JC)
1922 0 GRS10: Text data on mask build layer found! (JC)
1925 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (JD)
1927 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (JD)(unmerged)
1928 0 GRS2: Shape with acute angles found! (JD) (internal)
1929 0 GRS2: Shape with acute angles found! (JD) (external)
1933 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (JD)
1934 0 GRS10: Text data on mask build layer found! (JD)
1937 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (MZ)
1939 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (MZ)(unmerged)
1940 0 GRS2: Shape with acute angles found! (MZ) (internal)
1941 0 GRS2: Shape with acute angles found! (MZ) (external)
1945 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (MZ)
1946 0 GRS10: Text data on mask build layer found! (MZ)
1949 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (TV)
1951 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (TV)(unmerged)
1952 0 GRS2: Shape with acute angles found! (TV) (internal)
1953 0 GRS2: Shape with acute angles found! (TV) (external)
1957 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (TV)
1958 0 GRS10: Text data on mask build layer found! (TV)
1961 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (DI)
1963 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (DI)(unmerged)
1964 0 GRS2: Shape with acute angles found! (DI) (internal)
1965 0 GRS2: Shape with acute angles found! (DI) (external)
1969 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (DI)
1970 0 GRS10: Text data on mask build layer found! (DI)
1973 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (ESD_CDM)
1975 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (ESD_CDM)(unmerged)
1976 0 GRS2: Shape with acute angles found! (ESD_CDM) (internal)
1977 0 GRS2: Shape with acute angles found! (ESD_CDM) (external)
1981 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (ESD_CDM)
1982 0 GRS10: Text data on mask build layer found! (ESD_CDM)
1985 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (ESDUMMY)
1987 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (ESDUMMY)(unmerged)
1989 0 GRS2: Shape with acute angles found! (ESDUMMY) (internal)
1991 0 GRS2: Shape with acute angles found! (ESDUMMY) (external)
1997 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (ESDUMMY)
1998 0 GRS10: Text data on mask build layer found! (ESDUMMY)
2001 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (WVR)
2003 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (WVR)(unmerged)
2004 0 GRS2: Shape with acute angles found! (WVR) (internal)
2005 0 GRS2: Shape with acute angles found! (WVR) (external)
2009 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (WVR)
2010 0 GRS10: Text data on mask build layer found! (WVR)
2013 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (FIVEVONLY)
2015 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (FIVEVONLY)(unmerged)
2016 0 GRS2: Shape with acute angles found! (FIVEVONLY) (internal)
2017 0 GRS2: Shape with acute angles found! (FIVEVONLY) (external)
2021 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (FIVEVONLY)
2022 0 GRS10: Text data on mask build layer found! (FIVEVONLY)
2025 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (SCGATE)
2027 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (SCGATE)(unmerged)
2028 0 GRS2: Shape with acute angles found! (SCGATE) (internal)
2029 0 GRS2: Shape with acute angles found! (SCGATE) (external)
2033 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (SCGATE)
2034 0 GRS10: Text data on mask build layer found! (SCGATE)
2037 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (SCHKY)
2039 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (SCHKY)(unmerged)
2040 0 GRS2: Shape with acute angles found! (SCHKY) (internal)
2041 0 GRS2: Shape with acute angles found! (SCHKY) (external)
2045 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (SCHKY)
2046 0 GRS10: Text data on mask build layer found! (SCHKY)
2049 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (BIPOLAR)
2051 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (BIPOLAR)(unmerged)
2052 0 GRS2: Shape with acute angles found! (BIPOLAR) (internal)
2053 0 GRS2: Shape with acute angles found! (BIPOLAR) (external)
2057 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (BIPOLAR)
2058 0 GRS10: Text data on mask build layer found! (BIPOLAR)
2061 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (DS_MATCH)
2063 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (DS_MATCH)(unmerged)
2065 0 GRS2: Shape with acute angles found! (DS_MATCH) (internal)
2067 0 GRS2: Shape with acute angles found! (DS_MATCH) (external)
2073 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (DS_MATCH)
2074 0 GRS10: Text data on mask build layer found! (DS_MATCH)
2077 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (RF_MODFILL)
2079 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (RF_MODFILL)(unmerged)
2081 0 GRS2: Shape with acute angles found! (RF_MODFILL) (internal)
2083 0 GRS2: Shape with acute angles found! (RF_MODFILL) (external)
2089 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (RF_MODFILL)
2090 0 GRS10: Text data on mask build layer found! (RF_MODFILL)
2093 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (VTSENS)
2095 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (VTSENS)(unmerged)
2097 0 GRS2: Shape with acute angles found! (VTSENS) (internal)
2099 0 GRS2: Shape with acute angles found! (VTSENS) (external)
2105 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (VTSENS)
2106 0 GRS10: Text data on mask build layer found! (VTSENS)
2109 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (WELLASP)
2111 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (WELLASP)(unmerged)
2113 0 GRS2: Shape with acute angles found! (WELLASP) (internal)
2115 0 GRS2: Shape with acute angles found! (WELLASP) (external)
2121 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (WELLASP)
2122 0 GRS10: Text data on mask build layer found! (WELLASP)
2125 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (DGV)
2127 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (DGV)(unmerged)
2128 0 GRS2: Shape with acute angles found! (DGV) (internal)
2129 0 GRS2: Shape with acute angles found! (DGV) (external)
2133 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (DGV)
2134 0 GRS10: Text data on mask build layer found! (DGV)
2137 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (DIPI)
2139 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (DIPI)(unmerged)
2140 0 GRS2: Shape with acute angles found! (DIPI) (internal)
2141 0 GRS2: Shape with acute angles found! (DIPI) (external)
2145 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (DIPI)
2146 0 GRS10: Text data on mask build layer found! (DIPI)
2149 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (GRLOGIC)
2151 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (GRLOGIC)(unmerged)
2152 0 GRS2: Shape with acute angles found! (GRLOGIC) (internal)
2153 0 GRS2: Shape with acute angles found! (GRLOGIC) (external)
2157 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (GRLOGIC)
2158 0 GRS10: Text data on mask build layer found! (GRLOGIC)
2161 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (FLTGATE)
2163 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (FLTGATE)(unmerged)
2164 0 GRS2: Shape with acute angles found! (FLTGATE) (internal)
2165 0 GRS2: Shape with acute angles found! (FLTGATE) (external)
2169 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (FLTGATE)
2170 0 GRS10: Text data on mask build layer found! (FLTGATE)
2173 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (SBLK)
2175 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (SBLK)(unmerged)
2176 0 GRS2: Shape with acute angles found! (SBLK) (internal)
2177 0 GRS2: Shape with acute angles found! (SBLK) (external)
2181 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (SBLK)
2182 0 GRS10: Text data on mask build layer found! (SBLK)
2185 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (VNCAPM1)
2187 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (VNCAPM1)(unmerged)
2188 0 GRS2: Shape with acute angles found! (VNCAPM1) (internal)
2189 0 GRS2: Shape with acute angles found! (VNCAPM1) (external)
2193 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (VNCAPM1)
2194 0 GRS10: Text data on mask build layer found! (VNCAPM1)
2197 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (VNCAPM2)
2199 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (VNCAPM2)(unmerged)
2200 0 GRS2: Shape with acute angles found! (VNCAPM2) (internal)
2201 0 GRS2: Shape with acute angles found! (VNCAPM2) (external)
2205 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (VNCAPM2)
2206 0 GRS10: Text data on mask build layer found! (VNCAPM2)
2209 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (VNCAPM3)
2211 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (VNCAPM3)(unmerged)
2212 0 GRS2: Shape with acute angles found! (VNCAPM3) (internal)
2213 0 GRS2: Shape with acute angles found! (VNCAPM3) (external)
2217 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (VNCAPM3)
2218 0 GRS10: Text data on mask build layer found! (VNCAPM3)
2221 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (VNCAPM4)
2223 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (VNCAPM4)(unmerged)
2224 0 GRS2: Shape with acute angles found! (VNCAPM4) (internal)
2225 0 GRS2: Shape with acute angles found! (VNCAPM4) (external)
2229 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (VNCAPM4)
2230 0 GRS10: Text data on mask build layer found! (VNCAPM4)
2233 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (VNCAPM5)
2235 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (VNCAPM5)(unmerged)
2236 0 GRS2: Shape with acute angles found! (VNCAPM5) (internal)
2237 0 GRS2: Shape with acute angles found! (VNCAPM5) (external)
2241 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (VNCAPM5)
2242 0 GRS10: Text data on mask build layer found! (VNCAPM5)
2245 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (VNCAPMT)
2247 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (VNCAPMT)(unmerged)
2248 0 GRS2: Shape with acute angles found! (VNCAPMT) (internal)
2249 0 GRS2: Shape with acute angles found! (VNCAPMT) (external)
2253 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (VNCAPMT)
2254 0 GRS10: Text data on mask build layer found! (VNCAPMT)
2257 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (MIMHK)
2259 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (MIMHK)(unmerged)
2260 0 GRS2: Shape with acute angles found! (MIMHK) (internal)
2261 0 GRS2: Shape with acute angles found! (MIMHK) (external)
2265 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (MIMHK)
2266 0 GRS10: Text data on mask build layer found! (MIMHK)
2269 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (MIMHD)
2271 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (MIMHD)(unmerged)
2272 0 GRS2: Shape with acute angles found! (MIMHD) (internal)
2273 0 GRS2: Shape with acute angles found! (MIMHD) (external)
2277 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (MIMHD)
2278 0 GRS10: Text data on mask build layer found! (MIMHD)
2281 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (RESHV)
2283 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (RESHV)(unmerged)
2284 0 GRS2: Shape with acute angles found! (RESHV) (internal)
2285 0 GRS2: Shape with acute angles found! (RESHV) (external)
2289 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (RESHV)
2290 0 GRS10: Text data on mask build layer found! (RESHV)
2293 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (E1_COIL)
2295 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (E1_COIL)(unmerged)
2297 0 GRS2: Shape with acute angles found! (E1_COIL) (internal)
2299 0 GRS2: Shape with acute angles found! (E1_COIL) (external)
2305 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (E1_COIL)
2306 0 GRS10: Text data on mask build layer found! (E1_COIL)
2309 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (MT_COIL)
2311 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (MT_COIL)(unmerged)
2313 0 GRS2: Shape with acute angles found! (MT_COIL) (internal)
2315 0 GRS2: Shape with acute angles found! (MT_COIL) (external)
2321 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (MT_COIL)
2322 0 GRS10: Text data on mask build layer found! (MT_COIL)
2325 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (M5_COIL)
2327 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (M5_COIL)(unmerged)
2329 0 GRS2: Shape with acute angles found! (M5_COIL) (internal)
2331 0 GRS2: Shape with acute angles found! (M5_COIL) (external)
2337 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (M5_COIL)
2338 0 GRS10: Text data on mask build layer found! (M5_COIL)
2341 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (M4_COIL)
2343 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (M4_COIL)(unmerged)
2345 0 GRS2: Shape with acute angles found! (M4_COIL) (internal)
2347 0 GRS2: Shape with acute angles found! (M4_COIL) (external)
2353 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (M4_COIL)
2354 0 GRS10: Text data on mask build layer found! (M4_COIL)
2357 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (M3_COIL)
2359 0 offGridShapeErrors: GRS1: Off-Grid vertex found! (M3_COIL)(unmerged)
2361 0 GRS2: Shape with acute angles found! (M3_COIL) (internal)
2363 0 GRS2: Shape with acute angles found! (M3_COIL) (external)
2369 0 GRS6: Shape with Non-Orthogonal or Non-45 degree edges found! (M3_COIL)
2370 0 GRS10: Text data on mask build layer found! (M3_COIL)
2374 0 offGridShapeErrors: GRCE001: CHIPEDGE not on a 0.02 GRID found!
2380 0 offGridShapeErrors: GRCE001b: Union(CHIPEDGE,MPW_EDGE,CRACKSTOP) not on a 0.02 GRID found!
2385 0 GRPHHOLE7: (PHHOLE1 over NW) enclosed area >= 0.537 sq.um.
2386 0 GRPHHOLE8: ((PC over RX) over NW) touching PHHOLE1 found!
2387 0 GRPHHOLE8: ((PC over RX) over NW) to PHHOLE1 space >= 0.360 um.
2389 0 GRRL01: (JS touching DATA_EXTENT) not allowed!
2391 0 GRRL03: (M1EXCLUD touching DATA_EXTENT) not allowed!
2565 0 GRLEG_990a: RX(chipring) width >= 1.08 um.(45 edge)
2566 0 GRLEG_990a: RX(chipring) width >= 1.08 um.(90 edge)
2567 0 GRLEG_990b: BP(chipring) width >= 1.52 um.(45 edge)
2568 0 GRLEG_990b: BP(chipring) width >= 1.52 um.(90 edge)
2569 0 GRLEG_990c: BP(chipring) touching BB found!
2570 0 GRLEG_990f: M1(chipring) width >= 1.08 um.(45 edge)
2571 0 GRLEG_990f: M1(chipring) width >= 1.08 um.(90 edge)
2572 0 GRLEG_990f: M2(chipring) width >= 1.08 um.(45 edge)
2573 0 GRLEG_990f: M2(chipring) width >= 1.08 um.(90 edge)
2574 0 GRLEG_990f: M3(chipring) width >= 1.08 um.(45 edge)
2575 0 GRLEG_990f: M3(chipring) width >= 1.08 um.(90 edge)
2576 0 GRLEG_990f: M4(chipring) width >= 1.08 um.(45 edge)
2577 0 GRLEG_990f: M4(chipring) width >= 1.08 um.(90 edge)
2578 0 GRLEG_990f: M5(chipring) width >= 1.08 um.(45 edge)
2579 0 GRLEG_990f: M5(chipring) width >= 1.08 um.(90 edge)
2580 0 GRLEG_990g: MT(chipring) width >= 3.24 um.(45 edge)
2581 0 GRLEG_990g: MT(chipring) width >= 3.24 um.(90 edge)
2582 0 GRLEG_990h: E2(chipring) width >= 2.00 um.(45 edge)
2583 0 GRLEG_990h: E2(chipring) width >= 2.00 um.(90 edge)
2584 0 GRLEG_990i: E1(chipring) width >= 3.24 um.(45 edge)
2585 0 GRLEG_990i: E1(chipring) width >= 3.24 um.(90 edge)
2586 0 GRLEG_990k: AM(chipring) width >= 2.00 um.(45 edge)
2587 0 GRLEG_990k: AM(chipring) width >= 2.00 um.(90 edge)
2588 0 GRLEG_990k: MA(chipring) width >= 2.00 um.(45 edge)
2589 0 GRLEG_990k: MA(chipring) width >= 2.00 um.(90 edge)
2590 0 GRLEG_990k: ML(chipring) width >= 2.00 um.(45 edge)
2591 0 GRLEG_990k: ML(chipring) width >= 2.00 um.(90 edge)
2592 0 GRLEG_990k: MZ(chipring) width >= 2.00 um.(45 edge)
2593 0 GRLEG_990k: MZ(chipring) width >= 2.00 um.(90 edge)
2594 0 GRLEG_990d: CABAR(chipring) width == 0.20 um.(45 edge,error >)
2595 0 GRLEG_990d: CABAR(chipring) width == 0.20 um.(90 edge,error >)
2596 0 GRLEG_990d: CABAR(chipring) width == 0.20 um.(45 edge,error <)
2597 0 GRLEG_990d: CABAR(chipring) width == 0.20 um.(90 edge,error <)
2602 0 GRLEG_990e: V1B_RING width == 0.28 um.(45 edge,error >)
2603 0 GRLEG_990e: V1B_RING width == 0.28 um.(90 edge,error >)
2604 0 GRLEG_990e: V1B_RING width == 0.28 um.(45 edge,error <)
2605 0 GRLEG_990e: V1B_RING width == 0.28 um.(90 edge,error <)
2610 0 GRLEG_990e: V2B_RING width == 0.28 um.(45 edge,error >)
2611 0 GRLEG_990e: V2B_RING width == 0.28 um.(90 edge,error >)
2612 0 GRLEG_990e: V2B_RING width == 0.28 um.(45 edge,error <)
2613 0 GRLEG_990e: V2B_RING width == 0.28 um.(90 edge,error <)
2618 0 GRLEG_990e: V3B_RING width == 0.28 um.(45 edge,error >)
2619 0 GRLEG_990e: V3B_RING width == 0.28 um.(90 edge,error >)
2620 0 GRLEG_990e: V3B_RING width == 0.28 um.(45 edge,error <)
2621 0 GRLEG_990e: V3B_RING width == 0.28 um.(90 edge,error <)
2626 0 GRLEG_990e: V4B_RING width == 0.28 um.(45 edge,error >)
2627 0 GRLEG_990e: V4B_RING width == 0.28 um.(90 edge,error >)
2628 0 GRLEG_990e: V4B_RING width == 0.28 um.(45 edge,error <)
2629 0 GRLEG_990e: V4B_RING width == 0.28 um.(90 edge,error <)
2634 0 GRLEG_990e: V5B_RING width == 0.28 um.(45 edge,error >)
2635 0 GRLEG_990e: V5B_RING width == 0.28 um.(90 edge,error >)
2636 0 GRLEG_990e: V5B_RING width == 0.28 um.(45 edge,error <)
2637 0 GRLEG_990e: V5B_RING width == 0.28 um.(90 edge,error <)
2642 0 GRLEG_990j: FTBAR(chipring) width == 1.24 um.(45 edge,error >)
2643 0 GRLEG_990j: FTBAR(chipring) width == 1.24 um.(90 edge,error >)
2644 0 GRLEG_990j: FTBAR(chipring) width == 1.24 um.(45 edge,error <)
2645 0 GRLEG_990j: FTBAR(chipring) width == 1.24 um.(90 edge,error <)
2646 0 GRLEG_991: RX not within BP(chipring) found!
2648 0 GRLEG_991: RX must be within BP(chipring) >= 0.22 um.
2650 0 GRLEG_991: RX must be within BP(chipring) >= 0.22 um.
2651 0 GRLEG_992: CABAR not within RX(chipring) found!
2653 0 GRLEG_992: CABAR must be within RX(chipring) >= 0.44 um.
2655 0 GRLEG_992: CABAR must be within RX(chipring) >= 0.44 um.
2656 0 GRLEG_993: CABAR not within M1(chipring) found!
2658 0 GRLEG_993: CABAR must be within M1(chipring) >= 0.44 um.
2660 0 GRLEG_993: CABAR must be within M1(chipring) >= 0.44 um.
2661 0 GRLEG_994a: V1BAR not within M1(chipring) found!
2663 0 GRLEG_994a: V1BAR must be within M1(chipring) >= 0.40 um.
2665 0 GRLEG_994a: V1BAR must be within M1(chipring) >= 0.40 um.
2666 0 GRLEG_994b: V2BAR not within M2(chipring) found!
2668 0 GRLEG_994b: V2BAR must be within M2(chipring) >= 0.40 um.
2670 0 GRLEG_994b: V2BAR must be within M2(chipring) >= 0.40 um.
2671 0 GRLEG_994c: V3BAR not within M3(chipring) found!
2673 0 GRLEG_994c: V3BAR must be within M3(chipring) >= 0.40 um.
2675 0 GRLEG_994c: V3BAR must be within M3(chipring) >= 0.40 um.
2676 0 GRLEG_994d: V4BAR not within M4(chipring) found!
2678 0 GRLEG_994d: V4BAR must be within M4(chipring) >= 0.40 um.
2680 0 GRLEG_994d: V4BAR must be within M4(chipring) >= 0.40 um.
2681 0 GRLEG_994d1: V5BAR not within M5(chipring) found!
2683 0 GRLEG_994d1: V5BAR must be within M5(chipring) >= 0.40 um.
2685 0 GRLEG_994d1: V5BAR must be within M5(chipring) >= 0.40 um.
2686 0 GRLEG_994e: FTBAR not within MT(chipring) found!
2688 0 GRLEG_994e: FTBAR must be within MT(chipring) >= 1.00 um.
2690 0 GRLEG_994e: FTBAR must be within MT(chipring) >= 1.00 um.
2692 0 GRLEG_994f: FTBAR not within AM(chipring) found!
2694 0 GRLEG_994f: FTBAR must be within AM(chipring) >= 1.00 um.
2696 0 GRLEG_994f: FTBAR must be within AM(chipring) >= 1.00 um.
2698 0 GRLEG_994f: FTBAR not within E1(chipring) found!
2700 0 GRLEG_994f: FTBAR must be within E1(chipring) >= 1.00 um.
2702 0 GRLEG_994f: FTBAR must be within E1(chipring) >= 1.00 um.
2704 0 GRLEG_994f: FTBAR not within ML(chipring) found!
2706 0 GRLEG_994f: FTBAR must be within ML(chipring) >= 0.60 um.
2708 0 GRLEG_994f: FTBAR must be within ML(chipring) >= 0.60 um.
2710 0 GRLEG_994f: FTBAR not within MZ(chipring) found!
2712 0 GRLEG_994f: FTBAR must be within MZ(chipring) >= 1.00 um.
2714 0 GRLEG_994f: FTBAR must be within MZ(chipring) >= 1.00 um.
2720 0 GRLEG_995a: V1BAR not within M2(chipring) found!
2722 0 GRLEG_995a: V1BAR must be within M2(chipring) >= 0.40 um.
2724 0 GRLEG_995a: V1BAR must be within M2(chipring) >= 0.40 um.
2730 0 GRLEG_995b: V1BAR not within MT(chipring) found!
2732 0 GRLEG_995b: V1BAR must be within MT(chipring) >= 0.40 um.
2734 0 GRLEG_995b: V1BAR must be within MT(chipring) >= 0.40 um.
2740 0 GRLEG_996a: V2BAR not within M3(chipring) found!
2742 0 GRLEG_996a: V2BAR must be within M3(chipring) >= 0.40 um.
2744 0 GRLEG_996a: V2BAR must be within M3(chipring) >= 0.40 um.
2750 0 GRLEG_996b: V2BAR not within MT(chipring) found!
2752 0 GRLEG_996b: V2BAR must be within M3(chipring) >= 0.40 um.
2754 0 GRLEG_996b: V2BAR must be within M3(chipring) >= 0.40 um.
2760 0 GRLEG_996c: V3BAR not within M4(chipring) found!
2762 0 GRLEG_996c: V3BAR must be within M4(chipring) >= 0.400 um.
2764 0 GRLEG_996c: V3BAR must be within M4(chipring) >= 0.400 um.
2770 0 GRLEG_996d: V3BAR not within MT(chipring) found!
2772 0 GRLEG_996d: V4BAR must be within MT(chipring) >= 0.400 um.
2774 0 GRLEG_996d: V4BAR must be within MT(chipring) >= 0.400 um.
2780 0 GRLEG_996e: V4BAR not within MT(chipring) found!
2782 0 GRLEG_996e: V4BAR must be within MT(chipring) >= 0.400 um.
2784 0 GRLEG_996e: V4BAR must be within MT(chipring) >= 0.400 um.
2790 0 GRLEG_996f: V4BAR not within M5(chipring) found!
2792 0 GRLEG_996f: V5BAR must be within M5(chipring) >= 0.400 um.
2794 0 GRLEG_996f: V5BAR must be within M5(chipring) >= 0.400 um.
2800 0 GRLEG_996g: V5BAR not within MT(chipring) found!
2802 0 GRLEG_996g: V5BAR must be within MT(chipring) >= 0.400 um.
2804 0 GRLEG_996g: V5BAR must be within MT(chipring) >= 0.400 um.
2805 0 GRLEG_996h: E2 not within E1(chipring) found!
2807 0 GRLEG_996h: E2 must be within E1(chipring) >= 0.60 um.
2809 0 GRLEG_996h: E2 must be within E1(chipring) >= 0.60 um.
2810 0 GRLEG_996j: E2 not within MA(chipring) found!
2812 0 GRLEG_996j: E2 must be within MA(chipring) >= 1.760 um.
2814 0 GRLEG_996j: E2 must be within MA(chipring) >= 1.760 um.
2821 0 GRLEG_999: RX(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2828 0 GRLEG_999: RX(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2835 0 GRLEG_999: M1(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2842 0 GRLEG_999: M1(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2850 0 GRLEG_999: M2(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2858 0 GRLEG_999: M2(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2866 0 GRLEG_999: M3(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2874 0 GRLEG_999: M3(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2882 0 GRLEG_999: M4(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2890 0 GRLEG_999: M4(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2898 0 GRLEG_999: M5(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2906 0 GRLEG_999: M5(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2908 0 GRLEG_999: RX(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2910 0 GRLEG_999: RX(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2912 0 GRLEG_999: M1(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2914 0 GRLEG_999: M1(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2916 0 GRLEG_999: M2(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2918 0 GRLEG_999: M2(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2920 0 GRLEG_999: M3(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2922 0 GRLEG_999: M3(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2924 0 GRLEG_999: M4(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2926 0 GRLEG_999: M4(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2928 0 GRLEG_999: M5(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2930 0 GRLEG_999: M5(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2944 0 GRLEG_999a: CHIPEDGE is not bounded at X=0 on the left or not bounded at Y=0 on the bottom
2946 0 ERROR: CHIPEDGE maximum x dimension (mm) = 18.76 mm 
2950 0 ERROR: CHIPEDGE maximum y dimension (mm) = 20.76 mm 
2966 0 GRLEG_999a: OP must be within CHIPEDGE >= 11.06 um
2975 0 GRLEG_999a: PI must be within CHIPEDGE >= 11.06 um
2984 0 GRLEG_999a: NW must be within CHIPEDGE >= 11.06 um
2993 0 GRLEG_999a: NS must be within CHIPEDGE >= 11.06 um
3002 0 GRLEG_999a: PC must be within CHIPEDGE >= 11.06 um
3011 0 GRLEG_999a: RX must be within CHIPEDGE >= 11.06 um
3020 0 GRLEG_999a: CA must be within CHIPEDGE >= 11.06 um
3029 0 GRLEG_999a: CABAR must be within CHIPEDGE >= 11.06 um
3038 0 GRLEG_999a: RN must be within CHIPEDGE >= 11.06 um
3047 0 GRLEG_999a: PR must be within CHIPEDGE >= 11.06 um
3056 0 GRLEG_999a: NR must be within CHIPEDGE >= 11.06 um
3065 0 GRLEG_999a: BB must be within CHIPEDGE >= 11.06 um
3074 0 GRLEG_999a: JD must be within CHIPEDGE >= 11.06 um
3083 0 GRLEG_999a: RR must be within CHIPEDGE >= 11.06 um
3092 0 GRLEG_999a: RP must be within CHIPEDGE >= 11.06 um
3101 0 GRLEG_999a: DG must be within CHIPEDGE >= 11.06 um
3110 0 GRLEG_999a: TG must be within CHIPEDGE >= 11.06 um
3119 0 GRLEG_999a: M1 must be within CHIPEDGE >= 11.06 um
3128 0 GRLEG_999a: K1 must be within CHIPEDGE >= 11.06 um
3137 0 GRLEG_999a: V1 must be within CHIPEDGE >= 11.06 um
3146 0 GRLEG_999a: V1BAR must be within CHIPEDGE >= 11.06 um
3155 0 GRLEG_999a: M2 must be within CHIPEDGE >= 11.06 um
3164 0 GRLEG_999a: V2 must be within CHIPEDGE >= 11.06 um
3173 0 GRLEG_999a: V2BAR must be within CHIPEDGE >= 11.06 um
3182 0 GRLEG_999a: M3 must be within CHIPEDGE >= 11.06 um
3191 0 GRLEG_999a: V3 must be within CHIPEDGE >= 11.06 um
3200 0 GRLEG_999a: V3BAR must be within CHIPEDGE >= 11.06 um
3209 0 GRLEG_999a: M4 must be within CHIPEDGE >= 11.06 um
3218 0 GRLEG_999a: V4 must be within CHIPEDGE >= 11.06 um
3227 0 GRLEG_999a: V4BAR must be within CHIPEDGE >= 11.06 um
3236 0 GRLEG_999a: M5 must be within CHIPEDGE >= 11.06 um
3245 0 GRLEG_999a: V5 must be within CHIPEDGE >= 11.06 um
3254 0 GRLEG_999a: V5BAR must be within CHIPEDGE >= 11.06 um
3263 0 GRLEG_999a: QT must be within CHIPEDGE >= 11.06 um
3272 0 GRLEG_999a: HT must be within CHIPEDGE >= 11.06 um
3281 0 GRLEG_999a: FT must be within CHIPEDGE >= 11.06 um
3290 0 GRLEG_999a: FTBAR must be within CHIPEDGE >= 11.06 um
3299 0 GRLEG_999a: E2 must be within CHIPEDGE >= 11.06 um
3308 0 GRLEG_999a: DV must be within CHIPEDGE >= 11.06 um
3317 0 GRLEG_999a: LV must be within CHIPEDGE >= 11.06 um
3326 0 GRLEG_999a: TV must be within CHIPEDGE >= 11.06 um
3335 0 GRLEG_999a: JS must be within CHIPEDGE >= 11.06 um
3344 0 GRLEG_999a: DEGEN must be within CHIPEDGE >= 11.06 um
3353 0 GRLEG_999a: PHGEN must be within CHIPEDGE >= 11.06 um
3362 0 GRLEG_999a: DFGEN must be within CHIPEDGE >= 11.06 um
3367 0 GRLEG_999a: Background enclosing a pad must contain CHIPEDGE!
3376 0 GRLEG_999b: BP must be within CHIPEDGE >= 9.28 um
3472 0 GRLEG_999c: AM(ring) must be within CHIPEDGE == 11.06 um.(error <)
3474 0 GRLEG_999c: AM(ring) must be within CHIPEDGE == 11.06 um.(error <)
3476 0 GRLEG_999c: E1(ring) must be within CHIPEDGE == 11.06 um.(error <)
3478 0 GRLEG_999c: E1(ring) must be within CHIPEDGE == 11.06 um.(error <)
3480 0 GRLEG_999c: MA(ring) must be within CHIPEDGE == 11.06 um.(error <)
3482 0 GRLEG_999c: MA(ring) must be within CHIPEDGE == 11.06 um.(error <)
3484 0 GRLEG_999c: ML(ring) must be within CHIPEDGE == 11.06 um.(error <)
3486 0 GRLEG_999c: ML(ring) must be within CHIPEDGE == 11.06 um.(error <)
3488 0 GRLEG_999c: MT(ring) must be within CHIPEDGE == 11.06 um.(error <)
3490 0 GRLEG_999c: MT(ring) must be within CHIPEDGE == 11.06 um.(error <)
3492 0 GRLEG_999c: MZ(ring) must be within CHIPEDGE == 11.06 um.(error <)
3494 0 GRLEG_999c: MZ(ring) must be within CHIPEDGE == 11.06 um.(error <)
3495 0 GRLEG_999c: AM(ring) must be within CHIPEDGE == 11.06 um.(error >)
3496 0 GRLEG_999c: E1(ring) must be within CHIPEDGE == 11.06 um.(error >)
3497 0 GRLEG_999c: MA(ring) must be within CHIPEDGE == 11.06 um.(error >)
3498 0 GRLEG_999c: ML(ring) must be within CHIPEDGE == 11.06 um.(error >)
3499 0 GRLEG_999c: MT(ring) must be within CHIPEDGE == 11.06 um.(error >)
3500 0 GRLEG_999c: MZ(ring) must be within CHIPEDGE == 11.06 um.(error >)
3501 0 GRLEG_999e: NW not allowed in chip Chip guardring area!
3502 0 GRLEG_999e: OP not allowed in chip Chip guardring area!
3503 0 GRLEG_999e: PC not allowed in chip Chip guardring area!
3504 0 GRLEG_999e: DI not allowed in chip Chip guardring area!
3505 0 GRLEG_999e: NS not allowed in chip Chip guardring area!
3506 0 GRLEG_999e: PI not allowed in chip Chip guardring area!
3508 0 GRLEG_999e: BP must be within chipring
3510 0 GRLEG_999e: CABAR must be within chipring
3512 0 GRLEG_999e: M1 must be within chipring
3514 0 GRLEG_999e: V1BAR must be within chipring
3516 0 GRLEG_999e: RX must be within chipring
3519 0 GRLEG_999e: M2 must be within chipring
3523 0 GRLEG_999e: V2BAR must be within chipring
3526 0 GRLEG_999e: M3 must be within chipring
3530 0 GRLEG_999e: V3BAR must be within chipring
3533 0 GRLEG_999e: M4 must be within chipring
3537 0 GRLEG_999e: V4BAR must be within chipring
3540 0 GRLEG_999e: M5 must be within chipring
3544 0 GRLEG_999e: V5BAR must be within chipring
3548 0 GRLEG_999e: MT must be within chipring
3555 0 GRLEG_999e: FT/FTBAR must be within chipring
3559 0 GRLEG_999e: E1 must be within chipring
3563 0 GRLEG_999e: E2 must be within chipring
3566 0 GRLEG_999e: MA must be within chipring
3569 0 GRLEG_999e: ML must be within chipring
3572 0 GRLEG_999e: AM must be within chipring
3575 0 GRLEG_999e: MZ must be within chipring
3580 0 GRLEG_1000: GUARDRING IS NOT CONNECTED TO A PAD! (AM)
3585 0 GRLEG_1000: GUARDRING IS NOT CONNECTED TO A PAD! (MA)
3590 0 GRLEG_1000: GUARDRING IS NOT CONNECTED TO A PAD! (ML)
3595 0 GRLEG_1000: GUARDRING IS NOT CONNECTED TO A PAD! (MZ)
3599 0 GRLEG_1001: DATA_EXTENT touching (MPW_EDGE,GUARDEDGE,GUARDRNG) is prohibited
3600 0 GR1: (PC over RX)(NFET) width >= 0.180 um.
3601 0 GR2: (PC over RX)(PFET) width >= 0.180 um.
3603 0 GR3: (PC over RX)(NFET) width for 45 deg >= 0.196 um.
3605 0 GR4: (PC over RX)(PFET) width for 45 deg >= 0.196 um.
3609 0 GR10: RX width under PC for NFET device >= 0.220 um.
3620 0 GR40b: RX space if both RX shapes are wider than 50.0um >= 2.00 um (space).
3622 0 GR40b: RX space if both RX shapes are wider than 50.0um >= 2.00 um (notch).
3624 0 GR11: RX width under PC for PFET device >= 0.220 um.
3625 0 GR50b: RX width (max) <= 200.000 um.
3626 0 GR50: RX width (min) >= 0.220 um.
3627 0 GR51: RX area >= 0.160 sq.um.
3629 0 GR52: RX space >= 0.260 um.
3631 0 GR52: RX notch >= 0.260 um.
3632 0 GRCPRX4: RX straddling NS found!
3634 0 GRCPRX4: RX within NS >= 0.500 um.
3643 0 GRRX8b: (BF not touching NW) to adjacent NW >= 1.140 um.
3644 0 GRRX8d: ((BF touch NW) touch NWASP) to adj (NW over NWASP) >= 0.700 um.
3655 0 GRRX23: (RX(over BB), not over IND_FILT,not over PC) must be covered by {PD,SBD,RN,JD, SCHKY}
3684 0 GR100: PC width >= 0.180 um.
3688 0 GR101a: PC area >= 0.203 sq. um.
3689 0 GR101b: PC enclosed area >= 0.291 sq. um.
3698 0 GR102a: (PC(NOT END) to PC(NOT END) space) (not over RX) >= 0.240 um.
3702 0 GR102a: (PC(NOT END) to PC(NOT END) notch) (not over RX) >= 0.240 um.
3708 0 GR102b: (PCEND to PC space) (not over RX)>= 0.180 um.
3715 0 GR102b: (PCEND to PCEND space) (not over RX) >= 0.180 um.
3718 0 GR104a: PC(over RX) space >= 0.240 um.
3721 0 GR104b: PC(over RX) space >= 0.240 um.
3727 0 GR110: RX overlap past PC >= 0.280 um.
3729 0 GR110: RX overlap past PC >= 0.280 um.(coincident)
3732 0 GR110: RX overlap past PC >= 0.280 um.(45 deg. gate)
3734 0 GR111: PC overlap past RX >= 0.240 um.
3736 0 GR111: PC overlap past RX >= 0.240 um.(coincident)
3750 0 GR112: PC overlap past RX (within 0.08 of RX corner) >= 0.300 um.
3753 0 GR114: PC to RX corner >= 0.060 um.
3754 0 GR114: PC abutting RX corner found!
3765 0 GR115: PC corner to RX >= 0.080 um.
3766 0 GR115: RX abutting PC corner found!
3823 0 GR119: PC Vertex within RX >= 0.280 um.
3852 0 GR120a: Non 45 degree PC vertices over RX found!(90 degree)
3859 0 GR120a: Non 45 degree PC vertices over RX found!(non 45)
3861 0 GR120b: Dist between inside corners of 45 degree gate >= 0.080 um.
3863 0 GR120c: (PC over RX) notch >= 0.460 um.
3866 0 GR121: PC intersecting RX at other than 90 degrees found!
3910 0 GR123a: 45 degree outside (RX not covered by (PC not touching CA)) vertice under (PC not under GRLOGIC) found!
3912 0 GR123a: 90 degree inside (RX not covered by (PC not touching CA)) vertice under (PC not under GRLOGIC) found!
3920 0 GR123a: 90 degree outside (RX not covered by (PC not touching CA)) vertice under (PC not under GRLOGIC) found!
3923 0 GR123b: Dist between inside corners of (RX under PC) >= 0.080 um.
3928 0 GR125: (PC over RX) dividing RX into less than 2 diffusions found!
3930 0 GR130b: (PC not intersecting RX) to RX >= 0.080 um.
3933 0 GRBB131: ((NW not over MOSVAR ) touching GRLOGIC) cannot touch a BB hole.
3935 0 GR132: (PC that intersects RX) area <= 320.000 sq.um.
3936 0 GR200: CA width and length == 0.200 um.(error <)
3937 0 GR200: CA width and length == 0.200 um.(error >)
3941 0 GR201: Non-rectangular CA found!
3942 0 GR201: 45 degree CA or CABAR found
3944 0 GR203a: CA space >= 0.240 um.
3946 0 GR204: CA within RX >= 0.100 um.
3948 0 GR204a: CABAR within RX >= 0.200 um.
3949 0 GR207: CA(over RX) to adjacent PC >= 0.160 um.
3952 0 GR208: CA(over PC) to adjacent RX >= 0.160 um.
3953 0 GR208a: CABAR(over PC) to adjacent RX >= 0.200 um.
3955 0 GR209: CA within PC >= 0.060 um.
3957 0 GR209a: CABAR within PC >= 0.160 um.
3958 0 GR211: {CA,CABAR} over (PC over RX) found!
3960 0 GR212: {CA,CABAR} not over {RX or PC} found!
3961 0 GR220: CABAR width == 0.200 um.(error >)
3962 0 GR220: CABAR width == 0.200 um.(error <)
3964 0 GRLEG_221: Non-rectangular CABAR found!
3965 0 GRLEG_221: CABAR length (min) >= 0.600 um.
3966 0 GRLEG_222: CABAR length (max) <= 5.000 um.
3967 0 GR223c: CA touching CABAR found!
3969 0 GR223a: CABAR space >= 0.360 um.
3971 0 GR223b: CABAR space (run > 2.5) >= 0.520 um.
3972 0 GR223c: CABAR to adjacent CA >= 0.280 um.
3974 0 GR225: CABAR(over RX) to adjacent PC >= 0.240 um.
3977 0 GRLEG_228: CABAR outside of (Resistors or Chip Guardring) found!
3978 0 GR250a: Non-orthagonal NW shapes found!
3979 0 GR250: NW(drawn or generated) width >= 0.700 um.
3983 0 GR252c: RX shape between (NW shapes < 1.28 um. apart) found!
3984 0 GRNWASP1: NW straddling NWASP found!
3986 0 GR252a: NW(not over NWASP) space >= 1.280 um.
3987 0 GR252a: NW(not over NWASP) to NW(over NWASP) space >= 1.280 um.
3989 0 GR252b: NW(over NWASP) space (run  < 0.70) >= 1.280 um.
3991 0 GR252b: NW(over NWASP) space (run >= 0.70) >= 0.840 um.
3993 0 GR252b: NW notch (run  < 0.70) >= 1.280 um.
3995 0 GR252b: NW notch (run >= 0.70) >= 0.840 um.
4002 0 GR260: (RX within BP) straddling NW found!
4004 0 GR260: (RX within BP) within NW >= 0.420 um.
4009 0 GR260a: (RX within BP) within NW(>=40.0) >= 0.520 um.
4018 0 GRCP260: (RX(P+) not touching NW) must be within BB >= 1.280 um.
4020 0 GRCP260c: RX N contact (RX not over (BP or (SCHKY over NW))) within BB (for junction isolation) >= 1.280 um.
4023 0 GRCP260d: RX N contact ((RX over SCHKY) not over BP) within BB >= 0.140
4026 0 GR261f: RX(NWcont) overlap of NW >= 0.280 um.
4036 0 GR262: RX(NWcont) overlap area with NW >= 0.150 sq.um.
4037 0 GR262b: (RX within RN) intersect area with BB >= 0.150 sq.um.
4038 0 GR262f: RX(NWcont) overlap area with NW >= 0.240 sq.um.
4039 0 GR261: RX(NWcont) overlap of NW >= 0.460 um.
4042 0 GR265: RX(outside BP) to adjacent NW (diff net) >= 0.420 um.
4043 0 GR265a: RX(outside BP) to adjacent NW(>=40.0) >= 0.520 um.
4045 0 GR265b: RX(outside BP) to adjacent NS (diff net) >= 2.320 um.
4047 0 GRCP265b: ((RX outside BP) not over PD) to adj BB (diff net) >= 0.420 um.
4048 0 GR266: (RX(in BP) outside NW) to adjacent NW >= 0.080 um.
4049 0 GRCP266c: (RX(in BP) no NW) to BB space >= 0.400 um.
4095 0 GR268: RX(in BP) to RX(not BP) (in same NW) space <= 53.000 um.
11530 0 GR268b: RX(N+ Jct) to Substrate Contact space <= 53.000 um.
11536 0 GRBB268: (RX over PD) to RX(not PD) (same BB) space <= 53.000 um.
11542 0 GR268g: NW(hole) without a substrate contact found!
11548 0 GR268g: BB(hole) without a substrate contact found!
11553 0 GR268g: BF(hole) without a substrate contact found!(generated BF)
11558 0 GR268g: BFMOAT(hole) without a substrate contact found!
11560 0 GR269: (PC over RX (where RX Straddles NW)) straddling NW found!
11562 0 GR269: (PC over RX (where RX Straddles NW)) to NW space >= 0.700 um.
11564 0 GR269a: RX(NWcont) overlap past (NW not over GRLOGIC ) >= 0.700 um.
11568 0 GRNW4: (NW not over SCHKY) overlapping BB found!
11569 0 GRNW4: NW to adjacent BB >= 1.760 um.
11571 0 GRVTSENS00: (PC over RX) straddling VTSENS found!
11573 0 GRVTSENS01: ((PC over RX) over VTSENS) to BB space >= 3.00 um.
11574 0 GRVTSENS01: ((PC over RX) over VTSENS) to BFMOAT space >= 3.00 um.
11575 0 GRVTSENS01: ((PC over RX) over VTSENS) to MOSVAR space >= 3.00 um.
11576 0 GRVTSENS01: ((PC over RX) over VTSENS) to NW space >= 3.00 um.
11577 0 GRVTSENS01: ((PC over RX) over VTSENS) to ZEROVT space >= 3.00 um.
11579 0 GRVTSENS02: (((PC over RX) over BP) over VTSENS) straddling PI found!
11581 0 GRVTSENS02: (((PC over RX) over BP) over VTSENS) within NW >= 2.30 um.
11583 0 GRVTSENS02: (((PC over RX) over BP) over VTSENS) within PI >= 2.30 um.
11584 0 GR290: NR width >= 0.640 um.
11585 0 GR291: Non-orthogonal NR shape found!
11587 0 GR292: NR to NR  space >= 0.540 um.
11589 0 GR292: NR to NR  notch >= 0.540 um.
11593 0 GR294a: [(PC intersect RX) not within NW] to NR  space >= 0.260 um.
11594 0 GR294b: [(PC intersect RX) not within NW] straddling NR found!
11598 0 GR294b: [(PC intersect RX) not within NW] within NR >= 0.260 um.
11600 0 GR299b: NR overlap past NW >= 1.400 um.
11604 0 GRNR10: NR touching (BB, MOSVAR, PD, DI) found!
11605 0 GRNR11 : NR to ZEROVT >= 1.400 um.
11606 0 GRNR11: NR touching ZEROVT found!
11607 0 GRNR12 : NR to PCFUSE >= 1.400 um.
11608 0 GRNR12: NR touching PCFUSE found!
11610 0 GRNR13: NR not touching (PC over RX) found!
11611 0 GRLW00: PR width >= 0.640 um.
11612 0 GRLW01: Non-orthogonal PR shape found!
11614 0 GRLW02: PR to PR  space >= 0.540 um.
11618 0 GRLW04a: [(PC intersect RX) within NW] to PR  space >= 0.260 um.
11619 0 GRLW04b: [(PC intersect RX) within NW] straddling PR found!
11623 0 GRLW04b: [(PC intersect RX) within NW] within PR >= 0.260 um.
11624 0 GRLW09: PR overlap past NW >= 0.860 um.
11628 0 GRLW10: PR touching (BB, MOSVAR, PD, DI) found!
11629 0 GRLW11 : PR to ZEROVT >= 1.400 um.
11630 0 GRLW11: PR touching ZEROVT found!
11631 0 GRLW12 : PR to PCFUSE >= 1.400 um.
11632 0 GRLW12: PR touching PCFUSE found!
11634 0 GRLW13: PR not touching (PC over RX) found!
11640 0 GR350: BP width >= 0.340 um.
11647 0 GR351a: BP area >= 0.387 sq.um.
11648 0 GR351b: BP enclosed area >= 0.387 sq.um.
11651 0 GR352: BP space >= 0.340 um.
11661 0 GR353: ((RX over BP) over NW) within BP >= 0.140 um.
11669 0 GR353: ((RX over BP) over NW) within BP (coincident) >= 0.140 um.
11686 0 GR354a: ((RX(sub cont) not GRLOGIC) not (NW +0.42)) within BP >= 0.000 um.
11688 0 GR354b: (RX(sub cont) over (NW +0.42)) within BP >= 0.140 um.
11704 0 GR355: (RX(not over BP)not over NW) to BP space >= 0.140 um.
11710 0 GR356b: (RX(nw cont) not over (NW -0.42)) to adj BP >= 0.140 um.
11712 0 GR357: Layout will cause: BH to NW space >= 0.440 um.
11714 0 GR357: Layout will cause: BH to BB space >= 0.440 um.
11716 0 GR357: Layout will cause: BH to MOSVAR space >= 0.440 um.
11718 0 GR357a: Layout will cause: BH width >= 0.440 um.
11721 0 GR357b: Layout will cause: BH space >= 0.440 um.
11723 0 GR358b: BP to PD space >= 0.340 um.
11725 0 GR358c: Layout will cause: BN to PD space >= 0.340 um.
11727 0 GR358d: Layout will cause: PH width >= 0.440 um.
11729 0 GR358e: Layout will cause: BN width >= 0.340 um.
11732 0 GR358f: Layout will cause: BN space >= 0.340 um.
11739 0 GR358g: Layout will cause: BF width >= 0.980 um.
11740 0 GR358g: Layout will cause: BF width >= 0.980 um.
11742 0 GR358h: Layout will cause: BF space (not over (GRLOGIC or NW or NWASP)) >= 1.000 um.
11744 0 GR358h: Layout will cause: BF space (not over (GRLOGIC or NW or NWASP)) >= 1.000 um.
11747 0 GR358i: Layout will cause: PH space >= 0.440 um.
11749 0 GR358j: Layout will cause: DE width >= 0.440 um.
11752 0 GR358k: Layout will cause: DE space >= 0.440 um.
11754 0 GR358m: Layout will cause: DF width >= 0.440 um.
11757 0 GR358n: Layout will cause: DF space >= 0.440 um.
11767 0 GR370: (PC over RX) to BP space >= 0.360 um.
11768 0 GR370: (PC over RX) to BP space (gate end)>= 0.360 um.
11769 0 GR370b: (PC over RX) touching PD found!
11770 0 GR370a: (PC over RX) to BB space >= 0.500 um.
11771 0 GR370b: (PC over RX) to PD >= 0.500 um.
11772 0 GR371: (PC over RX) straddling BP found!
11774 0 GR371: (PC over RX) within BP >= 0.360 um.
11775 0 GRBP3: BP touching BB found!
11779 0 GR372: (BP overlap of RX) not over NW >= 0.220 um.
11780 0 GR372a: Substrate contact area >= 0.147 sq.um.
11783 0 GR373: (RX overlap past BP) over NW  >= 0.220 um.
11784 0 GR373a: Well contact area >= 0.147 sq.um.
11785 0 GR374: RX straddling NW (butted n-well cont) found!
11787 0 GR374: RX within NW (butted n-well cont) >= 0.120 um.
11790 0 GR378: (BP inter RX) to adj ((PC intersect RX) not in BP) >= 0.280 um.
11793 0 GR379: (BP inter RX) overlap past ((PC intersect RX) in BP) >= 0.280 um.
11799 0 GR380: DI must be within BP == 0.040 um. (error >)
11800 0 GR380: DI outside of BP found.
11801 0 GR380a: NW(touching DI) touching JD found!
11802 0 GR380c: NW(touching DI) touching BB found!
11803 0 GR380c: NW(touching DI) touching PI found!
11804 0 GR380d: NW(touching DI) touching RP found!
11805 0 GR380d: NW(touching DI) touching RR found!
11806 0 GR380e: NW(touching DI) touching DG found!
11807 0 GR380e: NW(touching DI) touching OP found!
11808 0 GR380e: NW(touching DI) touching PC found!
11810 0 GR380g: BP(touching DI) touching PD found!
11812 0 GR380: DI must be within BP == 0.040 um. (error <)
11813 0 GR380a: NW(touching DI) to JD space >= 5.000 um.
11814 0 GR380d: NW(touching DI) to RP space >= 2.500 um.
11815 0 GR380d: NW(touching DI) to RR space >= 2.500 um.
11817 0 GR381: RX straddling DI found!
11821 0 GR381b: RX within DI <= 0.340 um.
11823 0 GR381: RX within DI >= 0.100 um.
11830 0 GR382b: RX(NWcont) to DI space <= 0.540 um.
11831 0 GR382b: DI not within an RX(NWcont) hole found!
11833 0 GR383: DI not enclosing an RX shape found!
11835 0 GR385a: RX(not GRLOGIC) width (max) (when RX touches DI) <= 2.000 um.
11836 0 GR385: RX width (min) (when RX touches DI) >= 1.000 um.
11837 0 GR387: RX(touching DI) not within NW found!
11852 0 GR387b: ((NW(touching DI) expanded by 0.36um) edges) must be covered by ((((RX touching CA) not touching PC) over BP) not over (NW or BB))!
11854 0 GR388: (RX(NWcont) over NW(touching DI)) to BP space >= 0.140 um.
11863 0 GR389: (RX(sxcont) over (NW(touch DI) +1.0)) within BP >= 0.140 um.
11879 0 GRDIPI00: DIPI must be exact space to BP, with touching prohibited == 0.04 um.
11896 0 GRDIPI00a: (PI touching DIPI) to JD (((PI touching DIPI) touching JD) prohibited) >= 1.00 um.
11897 0 GRDIPI00c: DIPI must be covered by PI
11908 0 GRDIPI00d: (PI touching DIPI) minimum space to (RR or RP). (PI touching DIPI) touching (RR or RP) is prohibited.>= 2.50 um.
11926 0 GRDIPI00e: DIPI touching {NW, BP,PC, OP, BB, PD, MOSVAR, NR, PR, DG, TG, ZEROVT} is prohibited
11940 0 GRDIPI00f: (PI touching DIPI) touching (PC over RX) is prohibited.
11954 0 GRDIPI00g: (BP touching (PI touching DIPI)) touching PD is prohibited.
11956 0 GRDIPI01: RX minimum within DIPI >= 0.10 um.
11961 0 GRDIPI01b: RX maximum within DIPI <= 0.34 um.
11975 0 GRDIPI02b: RX isolated p-well contact maximum space to DIPI <= 0.54 um.
11989 0 GRDIPI02c: RX isolated p-well contact touching (DIPI sized by +0.54 um) maximum space to (RX n-well contact over PI) <= 1.00 um.
11991 0 GRDIPI03: DIPI must enclose RX.
11993 0 GRDIPI05: RX minimum width (when RX is within DIPI) >= 1.00 um.
11998 0 GRDIPI5a: (RX not over GRLOGIC) maximum width - (when RX is within DIPI) <= 2.00 um.
12001 0 GRDIPI07: (RX within DIPI) must be within ((PI not over NW) not over BP)
12021 0 GRDIPI07b: [(NW not over PI) touching (PI touching DIPI)] maximum space to (RX substrate contact not over PI) <= 1.00 um.
12024 0 GRDIPI08: [RX p-well contact over (PI touching DIPI)] minimum within BP >= 0.14 um.
12035 0 GRDIPI09: {RX substrate contact over [((NW not over PI) touching (PI touching DIPI)) sized by +1.00 mm]} minimum within BP >= 0.14 um.
12043 0 GR710: (OP intersect RX) length >= 0.480 um.
12044 0 GR711: (OP intersect RX) width >= 0.280 um.
12048 0 GR712: (OP intersect PC) length >= 1.060 um.
12067 0 GR713a: (OP intersect PC) not over (RR intersect (non rectangular (PC under OP))) width >= 0.280 um.
12076 0 GR713b: (OP intersect PC) over (RR intersect (non rectangular (PC under OP))) width >= 0.180 um.
12080 0 GR713c: (OP intersect PC) over (RR intersect (non rectangular (PC under OP))) width <= 0.320 um.
12083 0 GR715a: ((RX touching OP) outside BP) touching NW found!
12084 0 GR715b: ((RX touching OP) inside BP) not within NW found!
12085 0 GR715f: RX(over OP) touching BB found!
12086 0 GR715a: ((RX touching OP) outside BP) to NW space >= 0.420 um.
12088 0 GR715b: ((RX touching OP) inside BP) within NW >= 0.420 um.
12089 0 GR716a: (RX touching OP) straddling NW found!
12090 0 GR716a: (RX touching OP) straddling BB found!
12092 0 GR716b: ((OP intersect RX) touching NW ) not touching BP found!
12094 0 GR716c: ((OP intersect RX) not touching NW ) touching BP found!
12095 0 GR717b: (PC intersect OP) straddling NW found!
12096 0 GR717a: (PC intersect OP) to NW space >= 0.600 um.
12098 0 GR717b: (PC intersect OP) within NW >= 0.860 um.
12099 0 GR725: OP width >= 0.480 um.
12101 0 GR726: OP space >= 0.480 um.
12103 0 GR726: OP notch >= 0.480 um.
12107 0 GR729a: OP area >= 0.720 sq.um.
12108 0 GR729b: OP enclosed area >= 0.720 sq.um.
12110 0 GR727: OP overlap past RX >= 0.180 um.
12111 0 GR728: OP to RX space >= 0.160 um.
12113 0 GR730: OP overlap past PC >= 0.200 um.
12114 0 GR731: OP to PC space>= 0.260 um.
12119 0 GROP9a: (OP over RP) overlap of PD == 0.380 um.(error >)
12120 0 GROP9a: (OP over RR) overlap of PD == 0.380 um.(error >)
12121 0 GROP9: OP to adjacent PD >= 0.440 um.
12122 0 GROP9a: (OP over RP) overlap of PD == 0.380 um.(error <)
12123 0 GROP9a: (OP over RR) overlap of PD == 0.380 um.(error <)
12124 0 GR732: CA/CABAR over OP found!
12125 0 GR733: CA to OP space >= 0.180 um.
12126 0 GR733a: CABAR to OP space >= 0.360 um.
12130 0 GR734a: (RX touching OP) straddling BP found!!
12134 0 GR734a: (RX touching OP) within BP >= 0.220um
12137 0 GR734b: (RX touching OP) to BP space >= 0.220 um.
12140 0 GR735a2: (PC touching OP) not within {BP or BB} found!
12144 0 GR735a2: (PC touching OP) within BP >= 0.300 um.
12148 0 GR735a2: (PC touching OP) within BB >= 0.300 um.
12151 0 GR735b: (PC touching OP) to BP space >= 0.300 um.
12154 0 GR736: (OP not over (ESDUMMy , ESD_CDM)) over (PC intersect RX) found!
12162 0 GR736a: RX(touching OP) touching PC found!
12170 0 GR736a1: (RX(touching OP) not touching PC) touching SBLK found!
12178 0 GR736a2: PC(touching OP) touching SBLK found!
12187 0 GR736a3: SBLK must touch OP
12196 0 GR737:  OP touching (DG not over (ESDUMMY or ESD_CDM)) not allowed!
12205 0 GR737a: PC(touching OP) touching DG found!
12207 0 GR738a: Non-rectangular (OP intersect RX) found!
12211 0 GR738b: Non-rectangular (OP intersect (PC not over RR)) found!
12212 0 GR738c_TF: Non-orthogonal  (OP intersect PC) found!
12214 0 GR739a: RX overlap past OP >= 0.620 um.
12216 0 GR739b: PC overlap past OP >= 0.580 um.
12217 0 GROP20: OP to adjacent RN >= 0.600 um.
12225 0 GROP24: OP touching RX(over RN) found!
12228 0 GROP29: PC(touching OP) touching RX found!
12230 0 GROP30: ((PC over OP) over NW) to RX space >= 0.380 um.
12231 0 GROP31: (PC touching OP) to RN must be>= 0.3um !
12242 0 GROP31: (PC touching OP) cannot touch RN !
12246 0 GROP32: ((RX over OP) not over GRLOGIC) to (NR or PR) space >= 0.260 um.
12247 0 GROP32: ((RX over OP) not over GRLOGIC) touching (NR or PR) found!
12258 0 GRPCR20a: (PCtouching OP) touching NS found !
12261 0 GRSBLK4: SBLK not covered by (ESDUMMY or ESD_CDM) found!!
12263 0 GRPBR19: More than ONE set of contacts found on a PC resistor!
12265 0 GRPBR19: More than ONE set of contacts found on a RX resistor!
12268 0 GRPBR29: PC(touching OP, not GRLOGIC) within NW >= 2.000 um.
12271 0 GRPBR31: PC(touching OP, touching BB) within BB >= 2.000 um.
12274 0 GRPBR33: PC(touch OP, no touch NW, not GRLOGIC) to adjacent NW >= 2.000 um.
12276 0 GRPBR35: PC(touching OP, not touching BB) to adjacent BB >= 2.000 um.
12277 0 GRRR1: RR width >= 0.800 um.
12279 0 GRRR2: RR space >= 0.800 um.
12281 0 GRRR2: RR notch >= 0.800 um.
12282 0 GRRR3: RR touching RP found!
12283 0 GRRR3: RR to RP space >= 0.800 um.
12284 0 GRRR4: PC straddling RR found!
12286 0 GRRR4: PC within RR >= 0.260 um.
12287 0 GRRR5: RR to adjacent PC >= 0.280 um.
12288 0 GRRR6: RR to (PC over RX) space >= 0.500 um.
12289 0 GRRR7: RR touching RX found!
12290 0 GRRR7: RR to adjacent RX >= 0.280 um.
12292 0 GRRR8: BP within RR >= 0.000 um.
12294 0 GRRR9: BP(touching RR) touching BB found!
12296 0 GRRR9: BP(touching RR) touching PC(not touching RR) found!
12298 0 GRRR10: PC(not touching OP) touching RR found!
12300 0 GRRR11: (CA/CABAR over RR) not covered by PD found!
12301 0 GRRP1: RP width >= 0.800 um.
12303 0 GRRP2: RP space >= 0.800 um.
12305 0 GRRP2: RP notch >= 0.800 um.
12306 0 GRRP4: PC straddling RP found!
12308 0 GRRP4: PC within RP >= 0.260 um.
12309 0 GRRP5: RP to adjacent PC >= 0.280 um.
12310 0 GRRP6: RP to (PC over RX) space >= 0.500 um.
12311 0 GRRP7: RP touching RX found!
12312 0 GRRP7: RP to adjacent RX >= 0.280 um.
12314 0 GRRP8: BP within RP >= 0.000 um.
12316 0 GRRP9: BP(touching RP) touching BB found!
12318 0 GRRP9: BP(touching RP) touching PC(not touching RP) found!
12320 0 GRRP10: PC(not touching OP) touching RP found!
12322 0 GRRP11: (CA/CABAR over RP) not covered by PD found!
12325 0 GRSERP1: (Non rectangular (PC intersect OP)) must touch RR.
12335 0 GRSERP7: (((PC over OP) over RR) over (Non rectangular (PC intersect OP)) notches == 0.240.
12338 0 GRSERP10: (CA touching (PC touching (Non rectangular (PC intersect OP)))) to OP space >= 0.320.
12345 0 GRSERP11: (CA touching (PC touching (Non rectangular (PC intersect OP)))) must be within (OP expanded by 0.52) >= 0.0000 um.
12350 0 GRSERP12: (CA touching (PC touching (Non rectangular (PC intersect OP)))) expanded by 0.31 per edge) must be within (PD not over OP) >= 0.0000 um.
12352 0 GRSERP13: (PD touching (PC touching (Non rectangular (PC intersect OP)))) abutting OP is prohibited.
12353 0 GRSERP13: (PD touching (PC touching (Non rectangular (PC intersect OP)))) must touch OP.
12355 0 GRSERP15: (CA touching (PC touching (Non rectangular (PC intersect OP)))) within PD >= 0.340 um.
12359 0 GRSERP16: (RR touching (Non rectangular (PC intersect OP)))  cannot touch (RR touching (rectangular (PC intersect OP))).
12360 0 GRKX1: K1 width (min) >= 5.000 um.
12361 0 GRKX2: V1 straddling K1 found!
12363 0 GRKX2: V1 within K1 >= 0.5000 um.
12365 0 GRKX3: K1 space >= 5.500 um.
12366 0 GRKX4: K1 touching M1 found!
12367 0 GRKX4: K1 to M1 space >= 1.000 um.
12378 0 GRKX5: More than ONE set of contacts found on a K1 resistor!
12404 0 GRKX6: K1 width (max) <= 30.000 um.
12406 0 GRKX8: Non-rectangular K1 found!
12407 0 GRKX8: 45 degree K1 found!
12418 0 GRKX9: V1(touching K1) space == 0.28 um. (error >)
12426 0 GRKX10: K1/M2 intersection only enclosing one V1 shape found!
12428 0 GRKX10: K1/MT intersection only enclosing one V1 shape found!
12429 0 GRKX11: K1 touching OP found!
12433 0 GRDG0: DGV must be within DG == 0.000 um.
12434 0 GRDG1: Non-orthagonal DG found!
12438 0 GRDG2b: Non-rectangular ((PC over RX) over DG) found!
12439 0 GRDG2b: 45 degree ((PC over RX) over DG) found!
12441 0 GRDG3: (PC touching DG) to RX space >= 0.080 um.
12442 0 GRDG4: (PC over RX) straddling DG found!
12444 0 GRDG4: (PC over RX) within DG >= 0.500 um.
12445 0 GRDG5: (PC over RX) to DG space >= 0.500 um.
12446 0 GRDG6: DG width >= 0.440 um.
12448 0 GRDG7: DG space >= 0.440 um.
12450 0 GRDG7: DG notch >= 0.440 um.
12459 0 GRDG8a: (((PC over RX) over DG) not over DGV) width for NFET >= 0.400 um.
12466 0 GRDG8b: (((PC over RX) over DG) not over DGV) width for PFET >= 0.400 um.
12473 0 GRDGV8a: (((PC over RX) over DG) over DGV) width for NFET >= 0.320 um.
12480 0 GRDGV8b: (((PC over RX) over DG) over DGV) width for PFET >= 0.320 um.
12482 0 GRDG8c: ((PC over RX) over DG) space >= 0.300 um.
12483 0 GRDG8d: (CA over RX) to adj ((PC over RX) over DG) space >= 0.160 um.
12485 0 GRDG9: DG overlap past NW >= 0.440 um.
12486 0 GRDG10 : DG to NR >= 0.700 um.
12487 0 GRDG10: DG touching NR found!
12488 0 GRDG11 : DG to PR >= 0.700 um.
12489 0 GRDG11: DG touching PR found!
12490 0 GRDG14: DG overlap of NW >= 0.440 um.
12491 0 GRDG15: DG to (OP intersect PC) space >= 0.700 um.
12493 0 GRDG16: NW overlap past DG >= 0.440 um.
12494 0 GRDG21: DG touching BB found!
12499 0 GRDG50: ((RX over PC) over DG) width >= 0.500 um.
12500 0 GRDG52: (RX touching DG) to RX space >= 0.380 um.
12505 0 GRDG110: (RX over DG) overlap past PC >= 0.380 um.
12508 0 GRDG260: (RX(P+) touching DG) within NW >= 0.560 um.
12511 0 GRDG265a: (RX(N+) touching DG) to adjacent NW >= 0.560 um.
12512 0 GRDG265a1: (RX(N+) touching DG) to adjacent BB >= 0.560 um.
12514 0 GRDG265b: RX(N+) to adjacent (NW touching DG) >= 0.560 um.
12536 0 GRDG268a: (RX(in BP)touch DG) to RX(not BP) (same NW) space <= 20.000 um.
12566 0 GRDG268b: (RX(no BP)touch DG) to Substrate Contact space <= 20.000 um.
15774 0 GRPD1: PD width >= 0.340 um.
15776 0 GRPD2a: PD space >= 0.340 um.
15778 0 GRPD2a: PD notch >= 0.340 um.
15780 0 GRPD3: PDHOLE width (for SBD anode) >= 0.700 um.
15787 0 GRPD4: PD to adj RX >= 0.360 um.
15789 0 GRPD5: RX intersect PD (SBD guardring) >= 0.320 um.
15793 0 GRPD6: RX(not over (SBD or BP2ND)) straddling PD found!
15796 0 GRPD6: RX(not over (SBD or BP2ND)) within PD >= 0.200 um.
15798 0 GRPD6a: PD overlap past RX(SBD guardring) >= 0.360 um.
15800 0 GRPD6b: RX(not over SBD) within PD >= 0.140 um.
15802 0 GRPD7: PD overlap past PC >= 0.280 um.
15803 0 GRPD9b: Non-orthogonal PD shape found!
15804 0 GRPD10a: PD to adjacent PC >= 0.280 um.
15806 0 GRPD10b: (PD over RR) to  PC >= 0.280 um.
15807 0 GRPD11: PD enclosed area >= 0.320 sq.um.
15810 0 GRPD14: CA(not over RN) not within PD(SBD) found!
15812 0 GRPD14: CA(not over RN) must be within PD(SBD) >= 0.280 um.
15814 0 GRPD15: (RX touching PD(touching SBD)) touching BP(drawn) found!
15817 0 GRPD16: PD(touching SBD) touching {PC or (RX not touching PD)} found!
15818 0 GRRN1: RN width >= 0.800 um.
15820 0 GRRN2: RN space >= 1.280 um.
15822 0 GRRN2: RN notch >= 1.280 um.
15823 0 GRRN3: RN to adjacent RX >= 0.420 um.
15824 0 GRRN4: RX straddling RN found!
15826 0 GRRN4: RX within RN >= 0.140 um.
15836 0 GRRN5a: (RX within RN) touching BP found!
15845 0 GRRN6: RN touching a P+ Junction found!
15846 0 GRRN7: RN touching a Substrate Contact found!
15847 0 GRRN10: (RN over RX) touching PD found!
15848 0 GRRN11: RN not within NS found!
15849 0 GRRN12: RN to NW space >= 1.280 um.
15851 0 GRRN13: (RN union NW) width >= 0.700 um.
15852 0 GRNS1: NS width >= 4.500 um.
15854 0 GRNS2: NS space >= 3.680 um.
15856 0 GRNS2: NS notch >= 3.680 um.
15857 0 GRNS4b: NS touching NW found!
15858 0 GRNS5: NS to adjacent NW space >= 3.680 um.
15863 0 GRCPNS7: NS within BB == 2.100 um.(error >)
15865 0 GRCPNS7: NS within BB == 2.100 um.(error <)
15866 0 GRNS9: NS not covered by BB found!
15867 0 GRNS10: NS to adjacent BB >= 5.200 um.
15869 0 GRNS15a: More than one (RX union NS) shape in the same BB found!
15871 0 GRNS16: NS not enclosing RX(over RN) found!
15873 0 GRNS21b: NS touching ((RX touching PD) not over SBD) found!
15875 0 GRNS21b: NS touching ((RX touching BP) not over SBD)found!
15876 0 GRNS21b: NS to (RX touching PD) space >= 2.760 um.
15877 0 GRNS21b: NS to (RX touching BP) space >= 2.760 um.
15879 0 GRNS26: NS not touching (JD (HAVAR) or PD hole (SBD)) found!
15893 0 GRBB1: ((BB not over SCHY) not abutting NW) width >= 2.760 um.
15894 0 GRBB1b: BB(touching SCHKY) width >= 0.980 um.
15895 0 GRBB1a: BB(abutting NW) width == 1.000 um.(error >)
15896 0 GRBB1a: BB(abutting NW) width == 1.000 um.(error <)
15903 0 GRBB2: (BB to BB space) not over NW (including notch)  >= 2.00
15905 0 GRBB2a: (BB to BB space) over NW (including notch)   >= 0.50
15906 0 GRBB6: (BB not over SCHKY) area >= 9.600 sq.um.
15907 0 GRBB6a: SCHKY must be covered by NW
15911 0 GRBB7: BB enclosed area >= 4.000 sq.um.
15913 0 GRBB34: BB over NW found!
15915 0 GRBB34: BB touching(singular) NW found!
15918 0 GRBB34a: BB touching more than one (union(union(NS, NW), RN)) shapes not allowed !
15919 0 GRBB35a: BB touching BP found!
15920 0 GRBB35: BB to adjacent BP >= 0.440 um.
15950 0 GRBB37: PD not within {[BB touch IND_FLT] or [(BP or BB) over (PC(res)+ 0.40)] or SBD or BP2ND or ((BB or BP) intersect (RR intersect (PC touching OP)expanded by 0.8))} found!
15954 0 GRBB38: (((RX not over SCHKY) touching BB) not over IND_FILT) must be touching NS
15955 0 GRBB41: PC straddling BB found!
15957 0 GRBB41: PC within BB >= 0.500 um.
15962 0 GRPBN10: PC(touching PD) not within {BP or BB} found!
15963 0 GRPBN10: PC(touching RR) not within {BP or BB} found!
15964 0 GRPBN10: PC(touching RP) not within {BP or BB} found!
15966 0 GRPBN10: PC(touch PD) must be within {BP or BB} >= 0.400 um.
15968 0 GRPBN10: PC(touch RR) must be within {BP or BB} >= 0.400 um.
15970 0 GRPBN10: PC(touch RP) must be within {BP or BB} >= 0.400 um.
15975 0 GRPBN11: (PC(touching CA/CABAR) intersect BB) not within {PD/RR/RP} found!
15976 0 GRPBN12: PC to adjacent BB space >= 0.320 um.
15977 0 GRTW01a: Non-orthagonal PI found!
15978 0 GRTW01: PI width >= 3.20 um.
15982 0 GRTW02: PI space (PI shapes touching the same NW ) >= 4.00 um.
15984 0 GRTW02: PI notch (PI shapes touching the same NW ) >= 4.00 um.
15994 0 GRTW02: PI space >= 4.30 um.
15995 0 GRTW03: PI touching RN found!
15996 0 GRTW03: PI touching NR found!
15997 0 GRTW03: PI touching PR found!
15998 0 GRTW03: PI touching DI found!
16000 0 GRTW03a: PI touching  (PD not over BP2ND) found!
16005 0 GRTW04: PI(edge) not covered by NW found!
16006 0 GRTW05: PI overlap of NW >= 1.00 um.
16008 0 GRTW06: NW overlap past PI >= 1.10 um.
16010 0 GRTW10a: PI touching NS found!
16013 0 GRTW10: (PI to adjacent BB) not over NW >= 3.20 um.
16014 0 GRTW10a: PI to adjacent NS >= 5.52 um.
16024 0 GRTW10b: all (BB over PI) edges must abut (NW or BP2ND)
16027 0 GRTW10a1: (PI to adjacent BB) over NW >= 1.10 um.
16029 0 GRTW10a1: (PI over NW) overlapping BB found!
16037 0 GRTW10a1: All (((PI touching BB) over NW) edges touching (PI over NW) hole) must abut BB.
16039 0 GRTW17a: (((RX over BP) over VTSENS) over NW) to PI space >= 1.000 um.
16050 0 GRTW18: PI to NW space >= 3.200 um.
16054 0 GRTW19: PI(not over NW) not touching a Pwell contact found!
16060 0 GRTW260: ((RX over BP) over NW) to (PI not over NW) space >= 0.420 um.
16062 0 GRTW265: (RX(not over BP) over PI) to adjacent (NW touching PI) >= 0.420 um.
16063 0 GRTW265a: ((RX(not over BP) touch DG) over PI) to adjacent (NW touching PI) >= 0.560 um.
16065 0 GRTW266: (RX(over BP) not over PI) to (NW touching PI) space >= 0.160 um.
16072 0 GR1a: (Gate over ZEROVT) width >= 0.70 um.
16076 0 GR1b: ((Gate over ZEROVT) over DG) width >= 0.80 um.
16082 0 GR10a: ((RX under PC) touching ZEROVT) width >= 3.00 um.
16085 0 GR122a: Polygonal (PC over RX) (bent gates) over ZEROVT found!
16086 0 GR280a: Non-orthagonal ZEROVT shapes found!
16087 0 GR280: ZEROVT width >= 2.40 um.
16089 0 GR282: ZEROVT space >= 1.88 um.
16091 0 GR282: ZEROVT notch >= 1.88 um.
16092 0 GR283: ZEROVT touching more than one RX shape found!
16093 0 GR284: ZEROVT not within RX found!
16098 0 GR284: ZEROVT must be within RX == 0.30 um. (error >)
16100 0 GR284: ZEROVT must be within RX == 0.30 um. (error <)
16104 0 GR286: BP touching ZEROVT found!
16105 0 GR288: ZEROVT to adjacent RX >= 1.30 um.
16106 0 GR289: ZEROVT touching NW found!
16109 0 GR289: ZEROVT to NW space >= 1.66 um.
16110 0 GR289a: ZEROVT to BB space >= 1.90 um.
16112 0 GR289a: ZEROVT touching BB found!
16114 0 GRZT1: ZEROVT overlap past (PC over RX) >= 0.92 um.
16139 0 GRZT2: ZEROVT vertices over (PC over RX) found!
16140 0 GRZT3: ZEROVT to adjacent DG >= 1.20 um.
16141 0 GRZT4: ZEROVT to adjacent (PC under OP) >= 1.32 um.
16142 0 GRZT5: ZEROVT touching JD found!
16143 0 GRZT5: ZEROVT touching RP found!
16144 0 GRZT5: ZEROVT touching RR found!
16145 0 GRZT5: ZEROVT to JD space >= 1.66 um.
16146 0 GRZT5: ZEROVT to RP space >= 1.66 um.
16147 0 GRZT5: ZEROVT to RR space >= 1.66 um.
16148 0 GRZT6: ZEROVT touching PI found!
16149 0 GRZT6: ZEROVT to PI space >= 3.00 um.
16159 0 GRZT9: ZEROVT touching OP found!
16160 0 GR790: BFMOAT width >= 10.000 um.
16161 0 GR792: BB to adjacent BFMOAT space >= 10.000 um.
16163 0 GR792: BFMOAT space >= 10.000 um.
16165 0 GR792: BFMOAT notch >= 10.000 um.
16166 0 GR793: BFMOAT to adjacent NW space >= 2.000 um.
16167 0 GR795: BFMOAT to adjacent RX space >= 1.000 um.
16168 0 GR796: BFMOAT to adjacent ZEROVT space >= 2.000 um.
16169 0 GR799: BB touching BFMOAT found!
16170 0 GR799: NW touching BFMOAT found!
16171 0 GR799: PC touching BFMOAT found!
16172 0 GR799: RX touching BFMOAT found!
16173 0 GR799: NS touching BFMOAT found!
16174 0 GR799: NR touching BFMOAT found!
16175 0 GR799: PR touching BFMOAT found!
16176 0 GR799: PI touching BFMOAT found!
16184 0 GR500b: M1 width (max) <= 35.000 um.
16185 0 GR500: M1 width (min) >= 0.240 um.
16189 0 GR501a: M1 area >= 0.172 sq.um.
16190 0 GR501b: M1 enclosed area >= 0.705 sq. um.
16192 0 GR502: M1 space >= 0.200 um.
16194 0 GR502: M1 notch >= 0.200 um.
16208 0 GR504:   M1(>1.48) to M1 (run >0) space >= 0.32 um.
16209 0 GR504b:  M1(>4.00) to M1 (run >0) space >= 0.60 um.
16212 0 GR504a:  M1(>1.60) to M1 (run >0) space >= 0.36 um.
16213 0 GR505a: CA not within M1 found!
16214 0 GR505b: CABAR not within M1 found!
16216 0 GR505a: CA must be within M1 >= 0.020 um.
16218 0 GR505b: CABAR must be within M1 >= 0.040 um.
16219 0 GR550: V1 width and length == 0.280 um. (error <)
16220 0 GR550: V2 width and length == 0.280 um. (error <)
16221 0 GR550: V3 width and length == 0.280 um. (error <)
16222 0 GR550: V4 width and length == 0.280 um. (error <)
16223 0 GR550: V5 width and length == 0.280 um. (error <)
16224 0 GR550: V1 width and length == 0.280 um. (error >)
16225 0 GR550: V2 width and length == 0.280 um. (error >)
16226 0 GR550: V3 width and length == 0.280 um. (error >)
16227 0 GR550: V4 width and length == 0.280 um. (error >)
16228 0 GR550: V5 width and length == 0.280 um. (error >)
16230 0 GR553a: V1 to V1 space >= 0.280 um.
16232 0 GR553a: V2 to V2 space >= 0.280 um.
16234 0 GR553a: V3 to V3 space >= 0.280 um.
16236 0 GR553a: V4 to V4 space >= 0.280 um.
16238 0 GR553a: V5 to V5 space >= 0.280 um.
16240 0 GR557: Non-rectangular V1 found!
16241 0 GR557: 45 degree V1 found!
16243 0 GR557: Non-rectangular V2 found!
16244 0 GR557: 45 degree V2 found!
16246 0 GR557: Non-rectangular V3 found!
16247 0 GR557: 45 degree V3 found!
16249 0 GR557: Non-rectangular V4 found!
16250 0 GR557: 45 degree V4 found!
16252 0 GR557: Non-rectangular V5 found!
16253 0 GR557: 45 degree V5 found!
16254 0 GRLEG_558: V1BAR outside of Chipring found! 
16255 0 GRLEG_558: V2BAR outside of Chipring found! 
16256 0 GRLEG_558: V3BAR outside of Chipring found! 
16257 0 GRLEG_558: V4BAR outside of Chipring found! 
16258 0 GRLEG_558: V5BAR outside of Chipring found! 
16259 0 GR560: V1BAR width == 0.20 um. (error >)
16260 0 GR560: V1BAR width == 0.20 um. (error <)
16261 0 GR560: V2BAR width == 0.20 um. (error >)
16262 0 GR560: V2BAR width == 0.20 um. (error <)
16263 0 GR560: V3BAR width == 0.20 um. (error >)
16264 0 GR560: V3BAR width == 0.20 um. (error <)
16265 0 GR560: V4BAR width == 0.20 um. (error >)
16266 0 GR560: V4BAR width == 0.20 um. (error <)
16267 0 GR560: V5BAR width == 0.20 um. (error >)
16268 0 GR560: V5BAR width == 0.20 um. (error <)
16269 0 GR566: V1 overlapping V1BAR found!
16270 0 GR566: V2 overlapping V2BAR found!
16271 0 GR566: V3 overlapping V3BAR found!
16272 0 GR566: V4 overlapping V4BAR found!
16273 0 GR566: V5 overlapping V5BAR found!
16274 0 GR566: V1BAR to V1 space >= 0.560 um.
16275 0 GR566: V2BAR to V2 space >= 0.560 um.
16276 0 GR566: V3BAR to V3 space >= 0.560 um.
16277 0 GR566: V4BAR to V4 space >= 0.560 um.
16278 0 GR566: V5BAR to V5 space >= 0.560 um.
16280 0 GR567: V1BAR to adjacent V1BAR >= 3.60 um.
16282 0 GR567: V2BAR to adjacent V2BAR >= 3.60 um.
16284 0 GR567: V3BAR to adjacent V3BAR >= 3.60 um.
16286 0 GR567: V4BAR to adjacent V4BAR >= 3.60 um.
16288 0 GR567: V5BAR to adjacent V5BAR >= 3.60 um.
16290 0 GR567b: V1BAR notch >= 1.80 um.
16292 0 GR567b: V2BAR notch >= 1.80 um.
16294 0 GR567b: V3BAR notch >= 1.80 um.
16296 0 GR567b: V4BAR notch >= 1.80 um.
16298 0 GR567b: V5BAR notch >= 1.80 um.
16306 0 GR570: V1(not over K1) must be within M1 >= -0.020 um.
16308 0 GR570c: V1BAR must be within M1 >= 0.08 um.
16309 0 GR570c: V1BAR not within M1 found!
16311 0 GR575a: V1 not within M2 found!
16313 0 GR575a1: V1 not within MT found!
16315 0 GR575ab: V1BAR not within M2 found!
16317 0 GR575ab: V1BAR must be within M2 >= 0.40 um.
16320 0 GR575a2: V1BAR must be within MT >= 0.40 um.
16321 0 GR575a2: V1BAR not within MT found!
16326 0 GR601b:  M2 enclosed area >= 0.705 sq.um.
16327 0 GR600:   M2 width >= 0.28 um.
16328 0 GR601a:  M2 area >= 0.3136 sq.um.
16330 0 GR602:   M2 space >= 0.28 um.
16342 0 GR604a: M2(>5.00) to M2 space  >= 0.60 um.
16346 0 GR604: M2(>1.60) to M2(>1.60) space >= 0.40 um.
16351 0 GR601b:  M3 enclosed area >= 0.705 sq.um.
16352 0 GR600:   M3 width >= 0.28 um.
16353 0 GR601a:  M3 area >= 0.3136 sq.um.
16355 0 GR602:   M3 space >= 0.28 um.
16367 0 GR604a: M3(>5.00) to M3 space  >= 0.60 um.
16371 0 GR604: M3(>1.60) to M3(>1.60) space >= 0.40 um.
16376 0 GR601b:  M4 enclosed area >= 0.705 sq.um.
16377 0 GR600:   M4 width >= 0.28 um.
16378 0 GR601a:  M4 area >= 0.3136 sq.um.
16380 0 GR602:   M4 space >= 0.28 um.
16392 0 GR604a: M4(>5.00) to M4 space  >= 0.60 um.
16396 0 GR604: M4(>1.60) to M4(>1.60) space >= 0.40 um.
16401 0 GR601b:  M5 enclosed area >= 0.705 sq.um.
16402 0 GR600:   M5 width >= 0.28 um.
16403 0 GR601a:  M5 area >= 0.3136 sq.um.
16405 0 GR602:   M5 space >= 0.28 um.
16417 0 GR604a: M5(>5.00) to M5 space  >= 0.60 um.
16421 0 GR604: M5(>1.60) to M5(>1.60) space >= 0.40 um.
16422 0 GR610: V2 not within M2 found!
16423 0 GR610: V3 not within M3 found!
16424 0 GR610: V4 not within M4 found!
16425 0 GR610: V5 not within M5 found!
16427 0 GR610c: V2BAR must be within M2 >= 0.40 um.
16428 0 GR610c: V2BAR not within M2 found!
16430 0 GR610c: V3BAR must be within M3 >= 0.40 um.
16431 0 GR610c: V3BAR not within M3 found!
16433 0 GR610c: V4BAR must be within M4 >= 0.40 um.
16434 0 GR610c: V4BAR not within M4 found!
16436 0 GR610c: V5BAR must be within M5 >= 0.40 um.
16437 0 GR610c: V5BAR not within M5 found!
16439 0 GR611: V2 not within M3 found!
16441 0 GR611: V2 not within MT found!
16443 0 GR611: V3 not within M4 found!
16445 0 GR611: V3 not within MT found!
16447 0 GR611: V4 not within M5 found!
16449 0 GR611: V4 not within MT found!
16451 0 GR611: V5 not within MT found!
16453 0 GR611a: V2BAR not within M3 found!
16455 0 GR611a: V2BAR must be within M3 >= 0.40 um.
16458 0 GR611a: V2BAR must be within MT >= 0.40 um.
16459 0 GR611a: V2BAR not within MT found!
16461 0 GR611a: V3BAR not within M4 found!
16463 0 GR611a: V3BAR must be within M4 >= 0.40 um.
16466 0 GR611a: V3BAR must be within MT >= 0.40 um.
16467 0 GR611a: V3BAR not within MT found!
16469 0 GR611a: V4BAR not within M5 found!
16471 0 GR611a: V4BAR must be within M5 >= 0.40 um.
16474 0 GR611a: V4BAR must be within MT >= 0.40 um.
16475 0 GR611a: V4BAR not within MT found!
16477 0 GR611a: V5BAR must be within MT >= 0.40 um.
16478 0 GR611a: V5BAR not within MT found!
16507 0 GR612: M1/M2 intersection only enclosing one V1 shape found!
16508 0 GR612: M1/MT intersection only enclosing one V1 shape found!
16509 0 GR640: MT width >= 0.280 um.
16513 0 GR641a: MT area > 0.548 sq.um.
16514 0 GR641b: MT enclosed area >= 0.705 sq.um.
16516 0 GR642: MT space >= 0.280 um.
16518 0 GR642: MT notch >= 0.280 um.
16525 0 GR644:   MT(>1.60) to MT space >= 0.40 um.
16526 0 GR644a:  MT(>5.00) to MT space >= 0.60 um.
16527 0 GR644b:  MT(>35.00) to MT space >= 2.00 um.
16532 0 GR650a1: (LV not over (CRACKSTOP touching GUARDEDGE)) width >= 14.000 um.
16533 0 GR650a2: (LV over (CRACKSTOP touching GUARDEDGE)) width >= 9.000 um.
16534 0 GR650b1: (DV not over (CRACKSTOP touching GUARDEDGE)) width >= 14.000 um.
16535 0 GR650b2: (DV over (CRACKSTOP touching GUARDEDGE)) width >= 9.000 um.
16536 0 GR651a: LV area >= 550.000 sq.um.
16537 0 GR651b: DV area >= 480.000 sq.um.
16539 0 GR653b: DV space >= 11.000 um.
16541 0 GR653c: LV space >= 29.000 um.
16551 0 GR655b: (TV covered by (PADFILTR,CRACKSTOP)) width >= 4.20 um.
16552 0 GR655c: (TV not covered by (PADFILTR,CRACKSTOP)) width >= 14.00 um.
16553 0 GR656b: (TV covered by PADFILTR) area >= 103.000 um2.
16554 0 GR656c: (TV not covered by PADFILTR) area >= 480.000 um2.
16556 0 GR657b: (TV covered by PADFILTR) space >= 6.000 um.
16558 0 GR657c: (TV not covered by PADFILTR) space >= 8.000 um.
16562 0 GR658ab: TV within {GUARDEDGE,(CHIPEDGE not touching GUARDEDGE)} >= 12.000 um.
16564 0 GR658c: DV within {GUARDEDGE,(CHIPEDGE not touching GUARDEDGE)} >= 20.000 um.
16566 0 GR658c1: DV within {GUARDEDGE,(CHIPEDGE not touching GUARDEDGE)} >= 11.000 um.
16568 0 GR658d: LV within {GUARDEDGE,(CHIPEDGE not touching GUARDEDGE)} >= 29.000 um.
16570 0 GR658d1: LV within {GUARDEDGE,(CHIPEDGE not touching GUARDEDGE)} >= 11.000 um.
16571 0 GRBEOL1: DV found in C4 design!
16573 0 GRBEOL2: (MPW_EDGE touching DV) touching LV is prohibited!
16575 0 GRA500b: M1(over M1CHEXCL) width (max) <= 14.000 um.
16587 0 GRA504d: M1(over M1CHEXCL) (>11.50 wide) space >= 3.500 um.
16590 0 GRA504a: M1(over M1CHEXCL) (>2.40 and <=5.30) space >= 0.700 um.
16593 0 GRA504b: M1(over M1CHEXCL) (>5.30 and <=8.40) space >= 1.600 um.
16596 0 GRA504c: M1(over M1CHEXCL) (>8.40 and <=11.50) space >= 2.500 um.
16597 0 GRJD1: JD width >= 1.000 um.
16599 0 GRJD2: JD space >= 1.000 um.
16601 0 GRJD2: JD notch >= 1.000 um.
16602 0 GRJD3: RX straddling JD found!
16604 0 GRJD3: RX within JD >= 0.320 um.
16605 0 GRJD4: JD to PC space >= 1.040 um.
16606 0 GRJD4a: JD to RX space >= 0.580 um.
16607 0 GRJD5: JD touching OP found!
16608 0 GRJD5: JD touching PC found!
16609 0 GRJD5: JD touching RN found!
16610 0 GRJD5: JD touching RP found!
16611 0 GRJD5: JD touching RR found!
16613 0 GRJD6: JD touching (RX not touching NS) found!
16614 0 GRMOSVAR1: MOSVAR width >= 0.440 um.
16616 0 GRMOSVAR2: MOSVAR space >= 0.440 um.
16618 0 GRMOSVAR2: MOSVAR notch >= 0.440 um.
16625 0 GRMOSVAR3: MOSVAR touching DG found!
16626 0 GRMOSVAR3: MOSVAR touching NS found!
16627 0 GRMOSVAR3: MOSVAR touching RP found!
16628 0 GRMOSVAR3: MOSVAR touching RR found!
16629 0 GRMOSVAR3: MOSVAR touching (ZEROVT sized by +0.72) found!
16631 0 GRMOSVAR3a: (MOSVAR over NW) touching BP found!
16632 0 GRMOSVAR4: MOSVAR to BB space >= 0.440 um.
16633 0 GRMOSVAR4: MOSVAR to DG space >= 0.440 um.
16634 0 GRMOSVAR4: MOSVAR to NW space >= 0.440 um.
16635 0 GRMOSVAR4: MOSVAR to (ZEROVT sized by +0.72) space >= 0.440 um.
16636 0 GRMOSVAR5: MOSVAR to RX space >= 0.340 um.
16637 0 GRMOSVAR5a: MOSVAR to (PC over RX) space >= 0.500 um.
16642 0 GRMOSVAR6: ((RX not over BIPOLAR) touch MOSVAR) not within ((NW or PI)over MOSVAR) found!
16644 0 GRMOSVAR6: ((RX not over BIPOLAR) touch MOSVAR) must be within ((NW OR PI) over MOSVAR) >= 0.420 um.
16647 0 GRMOSVAR6a: ((RX over BIPOLAR)touch MOSVAR) not within ((NW or PI)over MOSVAR) found!
16649 0 GRMOSVAR6a: ((RX over BIPOLAR)touch MOSVAR) must be within ((NW OR PI) over MOSVAR) >= 0.340 um.
16657 0 GRMOSVAR8: (MOSVAR over PI) touching TG prohibited
16667 0 GRNCAP1: { NW touching [ (PC over RX) NOT over BP ]  } cannot touch ( BP over RX )
16670 0 GRPCAP1: (PC over RX) must be within BP >= 0.360 um.
16672 0 GRPCAP1: (PC over RX ) within BP >= 0.360 um.
16677 0 GRPCAP2: { ( PI  NOT over NW ) touching ( (PC over RX)  over BP ) } cannot touch ( RX  NOT over BP )
16684 0 GRVLNPN01: BIPOLAR cannot touch GRLOGIC
16698 0 GRVLNPN02: (((PC over RX) touching BIPOLAR) must be within MOSVAR >= 0.50 um.
16702 0 GRVLNPN03: BIPOLAR must touch (MOSVAR over (((PC over RX) over PI) not over BP))
16708 0 GRVLNPN04: BIPOLAR within (PI not over NW) == 0.56 um.
16710 0 GRVLNPN04: BIPOLAR within (PI not over NW) == 0.56 um (error <).
16716 0 GRVLNPN04b: (Union( NW,PI) touching BIPOLAR) overlap past BIPOLAR == 2.680 um (error>).
16718 0 GRVLNPN04b: (Union( NW,PI) touching BIPOLAR) overlap past BIPOLAR == 2.680 um (error<).
16729 0 GRVLNPN05: (PC over RX) width under BIPOLAR == 0.18um (error >).
16730 0 GRVLNPN05: (PC over RX) width under BIPOLAR == 0.18um (error <).
16743 0 GRVLNPN06: ((NW or PI) touching BIPOLAR) must be contained within a (P+ ring touching BPERI).
16748 0 GRVLNPN06: ((NW or PI) touching BIPOLAR) to a (P+ ring touching BPERI) must be =< 0.84um
16750 0 GRJC1: JC space >= 0.900 um.
16752 0 GRJC1: JC notch >= 0.900 um.
16753 0 GRJC2: JC width >= 1.380 um.
16754 0 GRJC2a: JC minimum area >= 6.000 um.
16755 0 GRJC3: JC not within PI found!
16757 0 GRJC3: JC must be within PI >= 1.940 um.
16758 0 GRJC4: JC to NW space >= 0.940 um.
16761 0 GRJC5: (RX not over BP) must be within JC >= 0.500 um.
16777 0 GRJC6: JC to (AS DG JD RR RP RN BB  NR PR PD OP PC ZEROVT MOSVAR SCHKY BIPOLAR) space >= 1.00 um.
16778 0 GRJC6: JC touch (AS DG JD RR RP RN BB  NR PR PD OP PC ZEROVT MOSVAR SCHKY BIPOLAR) found !
16785 0 GRJC7: ((JC not over (RX over BP)) touching more than one (RX not over BP) shape is prohibited.
16788 0 GRJC12: All JC Edges must abut or be covered by (RX over BP).
16791 0 GRJC8: (RX over BP) over JC) minimum  width >= 0.400 um.
16794 0 GRJC9: (RX over BP) over JC) maximum  width >= 0.500 um.
16796 0 GRJC10: ((RX not over BP) to (RX over BP)) over JC  for commom runlength > 0.0 == 0.28.(error < )
16799 0 GRJC10: ((RX not over BP) to (RX over BP)) over JC  for commom runlength > 0.0 == 0.28.(error > )
16802 0 GRJC11: (RX over BP) overlap past JC >= 0.500 um.
16804 0 GRJC13: Non-rectangular JC found!
16805 0 GRJC13: 45 degree JC found!
16807 0 GRJC14: Non-rectangular ((RX over BP) over JC) found!
16808 0 GRJC14: 45 degree ((RX over BP) over JC) found!
16825 0 GRJC15: ((PI not over NW) touching JC) touching (OP,PC,JD) is prohibited!
16834 0 GRJC16: ((PI not over NW) touching JC) cannot touch more than JC shape!
16835 0 GRJC942: DV terminal Pad to JC space >= 3.000 um.
16836 0 GRJC942: TV terminal Pad to JC space >= 3.000 um.
16843 0 GRJC951: DV terminal Pad touching JC found!
16850 0 GRJC951: LV terminal Pad touching JC found!
16857 0 GRJC990: BP in chip guard ring touching JC found!
16858 0 GRJCPN001: JC shape straddling LOGOBND not allowed
16861 0 GRBP2ND1: All BP2ND edges must abut (BB over PI).
16877 0 GRBP2ND2: BP2ND to (AS NS NW DG TG JD RR RP RN NR PR OP PC ZEROVT GRLOGIC SCHKY) space >= 1.00 um.
16878 0 GRBP2ND2: BP2ND touch (AS NS NW DG TG JD RR RP RN NR PR OP PC ZEROVT GRLOGIC SCHKY) found !
16881 0 GRBP2ND3: (RX not over PD) touching BP2ND width (min) >= 1.000 um.
16882 0 GRBP2ND350: BP2ND width (min) >= 0.340 um.
16883 0 GRBP2ND351a: BP2ND minimum area >= 0.387 sq.um.
16887 0 GRBP2ND351b: BP2ND enclosed area >= 0.387 sq.um.
16889 0 GRBP2ND352a: BP2ND space >= 0.340 um.
16891 0 GRBP2ND352a: BP2ND notch >= 0.340 um.
16892 0 GRBP2ND352b: BP2ND touching BP is prohibited.
16893 0 GRBP2ND352b: BP2ND to BP space >= 0.340 um.
16895 0 GRE1aa: E1(not under IND_FLT) width (max) <= 25.000 um.
16903 0 GRE1ab: E1(under (IND_FLT sized by 25 per edge)) width (max) <= 30.000 um.
16904 0 GRE1a: E1 width (min) >= 1.500 um.
16908 0 GRE1b: E1 (not IND) space >= 2.000 um.
16910 0 GRE1b: E1 (IND) space >= 2.000 um.
16911 0 GRE1b: E1 (IND) to E1 (not IND) space >= 2.000 um.
16913 0 GRE1e: FT not within E1 found!
16915 0 GRE1e: FT must be within E1 >= 1.000 um.
16917 0 GRE1f: FTBAR not within E1 found!
16919 0 GRE1f: FTBAR must be within E1 >= 1.000 um.
16920 0 GRE1g: E1 area >= 9.000 sq.um.
16938 0 GRE1S2: E1(>11.50) space >=  3.50 um.
16941 0 GRE1S1: E1(> 8.00 and <=11.50) space >=  2.50 um.
16975 0 GRE1A7: E1 enclosed area touching (E1 with width > 28.00 <= 30.00) >= 217.00 sq.um.
16976 0 GRE1A1: E1 enclosed area touching (E1 with width >  8.00 <= 11.50) >=  19.00 sq.um.
16977 0 GRE1A2: E1 enclosed area touching (E1 with width > 11.50 <= 14.00) >=  37.00 sq.um.
16978 0 GRE1A3: E1 enclosed area touching (E1 with width > 14.00 <= 17.50) >=  61.00 sq.um.
16979 0 GRE1A4: E1 enclosed area touching (E1 with width > 17.50 <= 21.00) >=  91.00 sq.um.
16980 0 GRE1A5: E1 enclosed area touching (E1 with width > 21.00 <= 24.50) >= 127.00 sq.um.
16981 0 GRE1A6: E1 enclosed area touching (E1 with width > 24.50 <= 28.00) >= 169.00 sq.um.
16982 0 GRE2a: E2 width (min) >= 2.000 um.
16984 0 GRE2b: E2 space >= 2.000 um.
16986 0 GRE2b: E2 notch >= 2.000 um.
16987 0 GRE2c: E2 area (min) >= 4.000 sq.um.
16988 0 GRE2d: E2 not within E1 found!
16990 0 GRE2d: E2 must be within E1 >= 0.600 um.
16991 0 GRE2e: E2 not within MA found!
16995 0 GRE2e: E2(not under IND) must be within MA >= 1.760 um.
16997 0 GRE2e: E2(under IND) must be within MA >= 1.760 um.
17005 0 GRE2f: E1/MA intersection only enclosing one small E2 shape found!
17014 0 GRE2f: E1/MA intersection with two small E2's not at minimum pitch found!
17015 0 GRFT1: FT width == 1.24 um.(error <)
17016 0 GRFT1: FT width == 1.24 um.(error >)
17018 0 GRFT2: FT space >= 2.000 um.
17029 0 GRFT3: FTBAR(outside IND_FLT) width == 1.24 um.(error >)
17038 0 GRFT3: FTBAR(over IND_FLT) width == 1.24 um.(error >)
17039 0 GRFT3: FTBAR(outside IND_FLT) width == 1.24 um.(error <)
17040 0 GRFT3: FTBAR(over IND_FLT) width == 1.24 um.(error <)
17041 0 GRFT4: FTBAR length (min) <= 1.260 um.
17042 0 GRLEG_FT5: FTBAR length (max) <= 20.000 um.
17043 0 GRFT6: FT touching FTBAR found!
17044 0 GRFT6: FT to FTBAR space >= 2.000 um.
17046 0 GRFT7: FTBAR space (run length <= 5.0) >= 2.000 um.
17048 0 GRFT8: FTBAR space (run length > 5.0) >= 4.000 um.
17049 0 GRFT9: FT not within MT found!
17051 0 GRFT9: FT must be within MT >= 1.000 um.
17052 0 GRFT10: FTBAR not within MT found!
17054 0 GRFT10: FTBAR must be within MT >= 1.000 um.
17056 0 GRLEG_FT11: Non-retangular FT found!
17058 0 GRLEG_FT11: Non-retangular FTBAR found!
17059 0 GRLEG_FT12: 45 degree FT found!
17060 0 GRLEG_FT12: 45 degree FTBAR found!
17063 0 GRAM1: AM width >= 2.000 um.
17065 0 GRAM1a: AM area >= 10.000 sq.um.
17068 0 GRAM2: AM to AM space >= 2.800 um.
17092 0 GRAM2a: AM space for AM edges over the same (((FT, FTBAR) not over (LOWCRNT, IND_FILT)) + 8.0um )
17116 0 GRAM2aa: AM space for AM edges (within ((FT,FTBAR) over IND_FILT) not over LOWCRNT +6.0 um.) >= 5.000 um.
17150 0 GRAM2b: (AM not over IND_FILT)(>10.00) to AM space >= 4.00 um.
17169 0 GRAM2c:  AM(>50.00) to AM space >= 5.00 um.
17172 0 GRAM2ba: AM over (IND_FILT +25.0)(>10.00 and <=25) to AM space >= 3.00 um.
17175 0 GRAM2b2: AM over (IND_FILT +50.0)(>25.00) to AM space >= 4.00 um.
17177 0 GRAM3: FT not within AM found!
17179 0 GRAM3: FTBAR not within AM found!
17181 0 GRAM3: FT must be within AM >= 1.000 um.
17183 0 GRAM3: FTBAR must be within AM >= 1.000 um.
17186 0 GRAM4: DV(within {GUARDEDGE,(CHIPEDGE not touching GUARDEDGE)}) not within AM found!
17189 0 GRAM4: LV(within {GUARDEDGE,(CHIPEDGE not touching GUARDEDGE)}) not within AM found!
17190 0 GRMA1: MA width >= 2.000 um.
17191 0 GRMA1a: MA minimum area >= 10.00 sq.um.
17193 0 GRMA2: MA space >= 2.800 um.
17217 0 GRMA2a: MA space (within (E2 not over (LOWCRNT, IND_FILT)) +8.0 um.) >= 5.000 um.
17241 0 GRMA2aa: MA space for MA edges (within (e2 over IND_FILT) not over LOWCRNT  +6.0 um.) >= 5.000 um.
17281 0 GRMA2b: (MA not over IND_FILT)(>10.00) to MA space >= 4.00 um.
17300 0 GRMA2c:  MA(>50.00) to MA space >= 5.00 um.
17303 0 GRMA2ba: MA over (IND_FILT +25.0)(>10.00 and <=25) to MA space >= 3.00 um.
17306 0 GRMA2b2: MA over (IND_FILT +50.0)(>25.00 and <=50) to MA space >= 4.00 um.
17309 0 GRMA4: DV(within {GUARDEDGE,(CHIPEDGE not touching GUARDEDGE)}) not within MA found!
17312 0 GRMA4: LV(within {GUARDEDGE,(CHIPEDGE not touching GUARDEDGE)}) not within MA found!
17315 0 GRML1: ML width >= 2.400 um.
17317 0 GRML2: ML space >= 2.400 um.
17319 0 GRML3: FT not within ML found!
17321 0 GRML3: FTBAR not within ML found!
17323 0 GRML3: FT must be within ML >= 0.600 um.
17325 0 GRML3: FTBAR must be within ML >= 0.600 um.
17328 0 GRML4: DV(within {GUARDEDGE,(CHIPEDGE not touching GUARDEDGE)}) not within ML found!
17331 0 GRML4: LV(within {GUARDEDGE,(CHIPEDGE not touching GUARDEDGE)}) not within ML found!
17334 0 GRMZ1: MZ width >= 2.00 um.
17336 0 GRMZ1a: MZ area >= 10.00 um.
17340 0 GRMZ2: MZ space >= 2.80 um.
17358 0 GRMZ2a: MZ space for MZ edges within ((FT,FTBAR) not over (LOWCRNT, IND_FILT) +8.0 um.) >= 5.000 um.
17376 0 GRMZ2aa: mz space for mz edges within ((((FT,FTBAR) over IND_FILT) not over LOWCRNT) +6.0 um.) >= 5.000 um.
17406 0 GRMZ2b: (MZ not over IND_FILT)(>10.00) to MZ space >= 4.00 um.
17425 0 GRMZ2c:  MZ(>50.00) to MZ space >= 5.00 um.
17428 0 GRMZ2ba: MA over (IND_FILT +25.0)(>10.00 and <=25) to MZ space >= 3.00 um.
17431 0 GRMZ2b2: MA over (IND_FILT +50.0)(>25.00 and <=50) to MZ space >= 4.00 um.
17433 0 GRMZ3: FT not within MZ found!
17435 0 GRMZ3: FTBAR not within MZ found!
17437 0 GRMZ3: FT must be within MZ >= 1.000 um.
17439 0 GRMZ3: FTBAR must be within MZ >= 1.000 um.
17442 0 GRMZ4: (TV within {GUARDEDGE,(CHIPEDGE not touching GUARDEDGE)} ) not within MZ found!
17445 0 GRMZ5: MZ touching (CHIPEDGE touching DV) is not allowed found!
17454 0 GRQCAP1d: QT width (max) <= 1,000.0 um.
17463 0 GRQCAP1d: HT width (max) <= 1,000.0 um.
17464 0 GRQCAP1: QT width >= 4.000 um.
17465 0 GRQCAP1a: HT width >= 4.000 um.
17466 0 GRQCAP1b: QT area (max per shape) <= 100,000.0 sq.um.
17467 0 GRQCAP1b: HT area (max per shape) <= 100,000.0 sq.um.
17469 0 GRQCAP2a: Non-rectangular QT shapes found!
17471 0 GRQCAP2a: Non-rectangular HT shapes found!
17474 0 GRQCAP2b: QT MIM aspect ratio > 3.0 found!
17477 0 GRQCAP2b: HT MIM aspect ratio > 3.0 found!
17479 0 GRQCAP2: QT space >= 2.200 um.
17481 0 GRQCAP2a1: HT space >= 3.600 um.
17482 0 GRQCAP3: QT not within MT found!
17483 0 GRQCAP3a: HT not within QT found!
17485 0 GRQCAP3: QT must be within MT >= 0.700 um.
17487 0 GRQCAP3a: HT must be within QT >= 0.700 um.
17491 0 GRQCAP4: QT(touching HT) not touching FT(outside of HT) found!
17492 0 GRQCAP4: FT straddling QT found!
17493 0 GRQCAP4b: FT straddling HT found!
17498 0 GRQCAP4a: (MT touching QT) touching V1 found!
17503 0 GRQCAP4a: (MT touching QT) touching V2 found!
17508 0 GRQCAP4a: (MT touching QT) touching V3 found!
17513 0 GRQCAP4a: (MT touching QT) touching V4 found!
17519 0 GRQCAP4a: (MT touching QT) touching V5 found!
17521 0 GRQCAP4: FT within QT >= 1.200 um.
17523 0 GRQCAP4b: FT within HT >= 1.200 um.
17524 0 GRQCAP4c: FT to HT space >= 1.000 um.
17525 0 GRQCAP5: FT to adjacent QT >= 1.000 um.
17526 0 GRQCAP5: FTBAR to adjacent QT >= 1.000 um.
17527 0 GRQCAP6: FTBAR touching QT found!
17533 0 GRQCAP8b: QT straddling BB(not touching (PC or DI or PI or MOSVAR)) found!
17534 0 GRQCAP8b: QT straddling NW(not touching (PC or DI or PI or MOSVAR)) found!
17536 0 GRQCAP8b: QT within BB(not touching (PC or DI or PI or MOSVAR)) >= 4.000 um.
17538 0 GRQCAP8b: QT within NW(not touching (PC or DI or PI or MOSVAR)) >= 4.000 um.
17546 0 GRQCAP10: (MT touching QT) to MT space >= 0.800!
17549 0 GRQCAP12b: QT(covered by NW) within NW >= 4.000 um.
17555 0 GRQCAP16: NS to adjacent QT(not touching {PC,RX}) >= 4.600 um.
17556 0 GRQCAP16b: NW to adjacent QT(not touching {NW,PC,RX}) >= 4.600 um.
17575 0 GRQCAP21: QT shapes must be covered by MIM_HK (if at least one QT touch MIM_HK).
17580 0 GRQCAP22: HT and MIM_HK cannot exist in the same design !!!
17589 0 GRQCAP22a: (MIM_HK not touching QT) found!
17590 0 GRQCAP23a: (Ratio of (FT over (QT touching MIMHK or MIMHD)) area to QT area) > 10.0% found !
17591 0 GRQCAP23b: (Ratio of (FT over HT) area to HT area) > 10.0% found !
17604 0 GRQCAP30: QT shapes must be covered by MIM_HD (if at least one QT touch MIM_HD).
17606 0 GRQCAP30: MIM_HD and HT can not exist in same design
17615 0 GRQCAP30a: (MIM_HD not covering QT) found!
17617 0 GRQCAP30a: (MIM_HD partly covering QT) found!
17627 0 GRQCAP33: MIM_HD touching MIM_HK found !!!
17631 0 GRQCAP34: MIM_HD MIM_HK cannot exist in the same design !!!
17644 0 GRIND10b: IND_FILT touching ( CHIPEDGE touching MZ )  found!!
17645 0 GRIND11: Invalid layer under IND_FLT found! (BN)
17646 0 GRIND11: Invalid layer under IND_FLT found! (BP)
17647 0 GRIND11: Invalid layer under IND_FLT found! (CABAR)
17648 0 GRIND11: Invalid layer under IND_FLT found! (LV)
17649 0 GRIND11: Invalid layer under IND_FLT found! (LVDUMMY)
17653 0 GRIND11: M1 straddling IND_FLT found!
17656 0 GRIND11: Invalid layer under IND_FLT found! (M2)
17659 0 GRIND11: Invalid layer under IND_FLT found! (M3)
17662 0 GRIND11: Invalid layer under IND_FLT found! (M4)
17665 0 GRIND11: Invalid layer under IND_FLT found! (M5)
17666 0 GRIND11: Invalid layer under IND_FLT found! (NS)
17667 0 GRIND11: Invalid layer under IND_FLT found! (NW)
17668 0 GRIND11: Invalid layer under IND_FLT found! (OP)
17669 0 GRIND11: Invalid layer under IND_FLT found! (QT)
17670 0 GRIND11: Invalid layer under IND_FLT found! (RN)
17673 0 GRIND11: Invalid layer under IND_FLT found! (RX)
17674 0 GRIND11: RX straddling IND_FLT found!
17682 0 GRIND11: Invalid layer under IND_FLT found! (MT)
17683 0 GRIND12: NS to IND_FILT space >= 4.600 um.
17684 0 GRIND13: AM(over IND_FLT) not covered by BB found!
17685 0 GRIND13: E1(over IND_FLT) not covered by BB found!
17686 0 GRIND13: MA(over IND_FLT) not covered by BB found!
17687 0 GRIND13: ML(over IND_FLT) not covered by BB found!
17688 0 GRIND16: (BB touch IND_FLT) touching BP found!
17690 0 GRIND16: (BB touch IND_FLT) touching (PC not touching IND_FLT) found!
17692 0 GRIND16: (BB touch IND_FLT) touching (RX not touching IND_FLT) found!
17697 0 GRIND23: SHORTED INDUCTOR COILS FOUND!
17702 0 GRIND23a: E1 over IND_FILT must match exactly E1_COIL!
17717 0 GRIND23b: M3 over IND_FILT must match exactly M3_COIL!
17720 0 GRIND23b: M4 over IND_FILT must match exactly M4_COIL!
17723 0 GRIND23b: M5 over IND_FILT must match exactly M5_COIL!
17726 0 GRIND23b: MT over IND_FILT must match exactly MT_COIL!
17739 0 GRTL1b: (AM over TLINE) width (max) <= 25.00 um.
17748 0 GRTL1b: (MA over TLINE) width (max) <= 25.00 um.
17757 0 GRTL1b: (ML over TLINE) width (max) <= 25.00 um.
17759 0 GRTL2a: TLINE overlap past AM >= 20.00 um.
17761 0 GRTL2a: TLINE overlap past MA >= 20.00 um.
17763 0 GRTL2a: TLINE overlap past ML >= 20.00 um.
17765 0 GRTL2b: AM overlap past TLINE >= 1.00 um
17767 0 GRTL2b: MA overlap past TLINE >= 1.00 um
17769 0 GRTL2b: ML overlap past TLINE >= 1.00 um
17778 0 GRTL3b: (AM over TLINE) length (min) >= 100.00 um.
17781 0 GRTL3b: (MA over TLINE) length (min) >= 100.00 um.
17784 0 GRTL3b: (ML over TLINE) length (min) >= 100.00 um.
17785 0 GRTL3a: (AM over TLINE) area (min) >= 400.00 sq.um.
17786 0 GRTL3a: (MA over TLINE) area (min) >= 400.00 sq.um.
17787 0 GRTL3a: (ML over TLINE) area (min) >= 400.00 sq.um.
17791 0 GRTL4b: (AM over TLINE) length (max) >= 1500.00 um.
17795 0 GRTL4b: (MA over TLINE) length (max) >= 1500.00 um.
17799 0 GRTL4b: (ML over TLINE) length (max) >= 1500.00 um.
17800 0 GRTL4a: (AM over TLINE) area (max) >= 37,500.00 sq.um.
17801 0 GRTL4a: (MA over TLINE) area (max) >= 37,500.00 sq.um.
17802 0 GRTL4a: (ML over TLINE) area (max) >= 37,500.00 sq.um.
17803 0 GRTL5: (AM over TLINE) not within BB found!
17804 0 GRTL5: (MA over TLINE) not within BB found!
17805 0 GRTL5: (ML over TLINE) not within BB found!
17807 0 GRTL5: (AM over TLINE) must be within BB >= 4.00 um.
17809 0 GRTL5: (AM over TLINE) must be within BB >= 4.00 um.
17811 0 GRTL5: (AM over TLINE) must be within BB >= 4.00 um.
17812 0 GRTL6a: Invalid layer under TLINE found! (M1)
17813 0 GRTL6a: Invalid layer under TLINE found! (M2)
17814 0 GRTL6a: Invalid layer under TLINE found! (M3)
17815 0 GRTL6a: Invalid layer under TLINE found! (M4)
17816 0 GRTL6a: Invalid layer under TLINE found! (M5)
17817 0 GRTL6a: Invalid layer under TLINE found! (MT)
17818 0 GRTL6a: Invalid layer under TLINE found! (NS)
17819 0 GRTL6a: Invalid layer under TLINE found! (NW)
17820 0 GRTL6a: Invalid layer under TLINE found! (PC)
17822 0 GRTL6a: Invalid layer under TLINE found! (RX)
17824 0 GRTL6b: (AM over TLINE) space >= 40.00 um.
17826 0 GRTL6b: (MA over TLINE) space >= 40.00 um.
17828 0 GRTL6b: (ML over TLINE) space >= 40.00 um.
17831 0 GRTL9: Non-rectangular (AM over TLINE) found!
17834 0 GRTL9: Non-rectangular (MA over TLINE) found!
17837 0 GRTL9: Non-rectangular (ML over TLINE) found!
17840 0 GRTL10: (AM over TLINE) touching (LV,DV,TV) found!
17843 0 GRTL10: (MA over TLINE) touching (LV,DV,TV) found!
17846 0 GRTL10: (ML over TLINE) touching (LV,DV,TV) found!
17849 0 GRTL10: (AM over TLINE) to (LV,DV,TV) space >= 4.00 um.
17852 0 GRTL10: (MA over TLINE) to (LV,DV,TV) space >= 4.00 um.
17855 0 GRTL10: (ML over TLINE) to (LV,DV,TV) space >= 4.00 um.
17864 0 GR780: PCING width == 0.160 um.(error > )
17865 0 GR780: PCING width == 0.160 um.(error < )
17867 0 GR781b: Cells named with 'IPCI' other than those containing PCING found!
17868 0 GR782: PCING to BONDPAD space >= 0.420 um.
17869 0 GR782: PCING to IND_FILT space >= 0.420 um.
17871 0 GR782: PCING to PCING space >= 0.420 um.
17872 0 GR782: PCING to PC    space >= 0.420 um.
17873 0 GR782: PCING to RX    space >= 0.420 um.
17874 0 GR782: PCING to CA    space >= 0.420 um.
17875 0 GR782: PCING to CABAR space >= 0.420 um.
17880 0 GR782: PCING touching (PC, RX, BONDPAD, IND_FILT or CA/CABAR) shapes found
17881 0 GR783: PCING arm length (from corner to end) >= 2.000 um.
17892 0 GR784: Union(CHIPEDGE,MPW_EDGE,CRACKSTOP) not enclosing any PCI shapes found!
17893 0 GR784: Union(CHIPEDGE,MPW_EDGE,CRACKSTOP) enclosing < 40 PCI shapes found!
17896 0 GRDM001: DS_MATCH minspace >= 0.100um.
17903 0 GRDM002: BB touching CHIPEDGE found!
17910 0 GRDM002: BFMOAT touching CHIPEDGE found!
17917 0 GRDM002: IND_FILT touching CHIPEDGE found!
17924 0 GRDM002: BONDPAD touching CHIPEDGE found!
17932 0 GRDM002: PCEXCLUD touching CHIPEDGE found!
17940 0 GRDM002: RXEXCLUD touching CHIPEDGE found!
17947 0 GRDM002: LOGOBND touching CHIPEDGE found!
17948 0 GRDM003: DS_MATCH area (max per shape) <= 400,000.0 sq.um.
17949 0 GRDMPN001: DS_MATCH straddling LOGOBND found!!.
17958 0 GREF01: PCFUSE width == 0.18 um.(error >)
17959 0 GREF01: PCFUSE width == 0.18 um.(error <)
17960 0 GREF02: PCFUSE length == 1.20 um.(error <)
17961 0 GREF02: PCFUSE length == 1.20 um.(error >)
17964 0 GREF03: Non-rectangular PCFUSE found!
17966 0 GREF03a: Non-rectangular (PC touching PCFUSE) found!
17967 0 GREF03: 45 degree PCFUSE found
17968 0 GREF03a: 45 degree (PC touching PCFUSE) found
17970 0 GREF04: PCFUSE space >= 2.50 um.
17971 0 GREF05: PCFUSE over BB found!
17972 0 GREF05: PCFUSE over BFMOAT found!
17973 0 GREF05: PCFUSE over CA found!
17974 0 GREF05: PCFUSE over DG found!
17975 0 GREF05: PCFUSE over K1 found!
17976 0 GREF05: PCFUSE over M1 found!
17977 0 GREF05: PCFUSE over M2 found!
17979 0 GREF05: PCFUSE over MT found!
17980 0 GREF05: PCFUSE over NS found!
17981 0 GREF05: PCFUSE over NW found!
17982 0 GREF05: PCFUSE over OP found!
17983 0 GREF05: PCFUSE over PC found!
17984 0 GREF05: PCFUSE over PI found!
17985 0 GREF05: PCFUSE over QT found!
17986 0 GREF05: PCFUSE over RP found!
17987 0 GREF05: PCFUSE over RR found!
17988 0 GREF05: PCFUSE over RX found!
17989 0 GREF05: PCFUSE over VNCAP_M1 found!
17990 0 GREF05: PCFUSE over VNCAP_M2 found!
17991 0 GREF05: PCFUSE over VNCAP_M3 found!
17992 0 GREF05: PCFUSE over VNCAP_M4 found!
17993 0 GREF05: PCFUSE over VNCAP_M5 found!
17994 0 GREF05: PCFUSE over VNCAP_MT found!
17995 0 GREF05: PCFUSE over JD found!
17997 0 GREF06: PCFUSE to BB space >= 2.50 um.
17998 0 GREF06: PCFUSE to BFMOAT space >= 2.50 um.
17999 0 GREF06: PCFUSE to DG space >= 2.50 um.
18000 0 GREF06: PCFUSE to K1 space >= 2.50 um.
18001 0 GREF06: PCFUSE to M2 space >= 2.50 um.
18002 0 GREF06: PCFUSE to MT space >= 2.50 um.
18003 0 GREF06: PCFUSE to NS space >= 2.50 um.
18004 0 GREF06: PCFUSE to NW space >= 2.50 um.
18005 0 GREF06: PCFUSE to OP space >= 2.50 um.
18006 0 GREF06: PCFUSE to PI space >= 2.50 um.
18007 0 GREF06: PCFUSE to QT space >= 2.50 um.
18008 0 GREF06: PCFUSE to RP space >= 2.50 um.
18009 0 GREF06: PCFUSE to RR space >= 2.50 um.
18010 0 GREF06: PCFUSE to RX space >= 2.50 um.
18011 0 GREF06: PCFUSE to V1 space >= 2.50 um.
18012 0 GREF06: PCFUSE to VNCAP_M1 space >= 2.50 um.
18013 0 GREF06: PCFUSE to VNCAP_M2 space >= 2.50 um.
18014 0 GREF06: PCFUSE to VNCAP_M3 space >= 2.50 um.
18015 0 GREF06: PCFUSE to VNCAP_M4 space >= 2.50 um.
18016 0 GREF06: PCFUSE to VNCAP_M5 space >= 2.50 um.
18017 0 GREF06: PCFUSE to VNCAP_MT space >= 2.50 um.
18018 0 GREF06: PCFUSE to JD space >= 2.50 um.
18019 0 GREF07a: PCFUSE not within BP found!
18020 0 GREF07b: (PC touching PCFUSE) not within BP found!
18022 0 GREF07a: PCFUSE must be within BP >= 0.30 um.
18024 0 GREF07b: (PC touching PCFUSE) must be within BP >= 0.30 um.
18031 0 GREF08a: PCFUSE abutting more than 1 anode found!
18032 0 GREF08a: PCFUSE abutting more than 1 cathode found!
18034 0 GREF08: PCFUSE (small end) not abutting a PC shape found!
18036 0 GREF08b: PCFUSE to (PC not touching PCFUSE) space >= 2.50 um.
18038 0 GREF09: PCFUSE to (M1 not touching (PC touch PCFUSE)) space >= 2.50 um.
18039 0 GREF10: (PC touching PCFUSE) not touching any CA's found!
18040 0 GREF10: (PC touching PCFUSE) touching less than 4 CA's found!
18041 0 GREF10: (PC touching PCFUSE) touching more than 4 CA's found!
18050 0 GREF11a: (PC touching PCFUSE) (anode) width == 1.18 um.(error >)
18051 0 GREF11a: (PC touching PCFUSE) (anode) width == 1.18 um.(error <)
18052 0 GREF11b: (PC touching PCFUSE) (anode) length == 1.74 um.(error <)
18053 0 GREF11b: (PC touching PCFUSE) (anode) length == 1.74 um.(error >)
18062 0 GREF12b: (PC touching PCFUSE) (cathode) length == 1.38 um.(error >)
18063 0 GREF12a: (PC touching PCFUSE) (cathode) width == 2.46 um.(error <)
18064 0 GREF12a: (PC touching PCFUSE) (cathode) width == 2.46 um.(error >)
18065 0 GREF12b: (PC touching PCFUSE) (cathode) length == 1.38 um.(error <)
18073 0 GREF13: (M1 touching (PC touching PCFUSE)) (anode) width <= 1.20 um.
18075 0 GREF14: (M1 touching (PC touching PCFUSE)) (cathode) width <= 2.50 um.
18076 0 GREF15: PCFUSE to (M1 touching (PC touching PCFUSE)) space >= 1.00 um.
18096 0 GREF16: PCFUSE not centered on PC anode found!
18098 0 GREF16: PCFUSE not centered on PC cathode found!
18099 0 GREF18: (BP touching PCFUSE) width >= 0.720 um.
18101 0 GREF19: (BP touching PCFUSE) touching BB found!
18102 0 GREF19: (BP touching PCFUSE) touching DG found!
18103 0 GREF19: (BP touching PCFUSE) touching MOSVAR found!
18104 0 GREF19: (BP touching PCFUSE) touching NW found!
18105 0 GREF19: (BP touching PCFUSE) touching (PC over OP)... found!
18106 0 GREF19: (BP touching PCFUSE) touching (ZEROVT + 0.72) found!
18107 0 GREF19: (BP touching PCFUSE) to BB space >= 0.44 um.
18108 0 GREF19: (BP touching PCFUSE) to DG space >= 0.44 um.
18109 0 GREF19: (BP touching PCFUSE) to MOSVAR space >= 0.44 um.
18110 0 GREF19: (BP touching PCFUSE) to NW space >= 0.44 um.
18111 0 GREF19: (BP touching PCFUSE) to (PC over OP)... space >= 0.44 um.
18112 0 GREF19: (BP touching PCFUSE) to (ZEROVT + 0.72) space >= 0.44 um.
18120 0 GREF19a: (BP touching PCFUSE) to TG, for minimum BH space >= 0.30 um.
18122 0 GREF20: (BP touching PCFUSE) touching (BP touching OP) found!
18125 0 GREF20: (BP touch PCFUSE) touch (BP touch (PC no touch PCFUSE)) found!
18127 0 GREF20: (BP touching PCFUSE) touching (BP touching RX) found!
18128 0 GRVNCAP1: VNCAPM1 minimum width >= 1.00 um !
18129 0 GRVNCAP1: VNCAPM2 minimum width >= 1.00 um !
18130 0 GRVNCAP1: VNCAPM3 minimum width >= 1.00 um !
18131 0 GRVNCAP1: VNCAPM4 minimum width >= 1.00 um !
18132 0 GRVNCAP1: VNCAPM5 minimum width >= 1.00 um !
18133 0 GRVNCAP1: VNCAPMT minimum width >= 1.00 um !
18140 0 GRVNCAP2: VNCAP_M1 area must be < 100,000 um2 (whole chip)
18141 0 GRVNCAP2: VNCAP_M2 area must be < 100,000 um2 (whole chip)
18142 0 GRVNCAP2: VNCAP_M3 area must be < 100,000 um2 (whole chip)
18143 0 GRVNCAP2: VNCAP_M4 area must be < 100,000 um2 (whole chip)
18144 0 GRVNCAP2: VNCAP_M5 area must be < 100,000 um2 (whole chip)
18145 0 GRVNCAP2: VNCAP_MT area must be < 100,000 um2 (whole chip)
18206 0 GRVNCAP3: (M1 over VNCAP_M1) width == 0.36 um.(error <)
18207 0 GRVNCAP3: (M2 over VNCAP_M2) width == 0.36 um.(error <)
18208 0 GRVNCAP3: (M3 over VNCAP_M3) width == 0.36 um.(error <)
18209 0 GRVNCAP3: (M4 over VNCAP_M4) width == 0.36 um.(error <)
18210 0 GRVNCAP3: (M5 over VNCAP_M5) width == 0.36 um.(error <)
18211 0 GRVNCAP3: (MT over VNCAP_MT) width == 0.36 um.(error <)
18212 0 GRVNCAP3: (M1 over VNCAP_M1) width == 0.36 um.(error >)
18213 0 GRVNCAP3: (M2 over VNCAP_M2) width == 0.36 um.(error >)
18214 0 GRVNCAP3: (M3 over VNCAP_M3) width == 0.36 um.(error >)
18215 0 GRVNCAP3: (M4 over VNCAP_M4) width == 0.36 um.(error >)
18216 0 GRVNCAP3: (M5 over VNCAP_M5) width == 0.36 um.(error >)
18217 0 GRVNCAP3: (MT over VNCAP_MT) width == 0.36 um.(error >)
18226 0 GRVNCAP3a: (M1 over VNCAPM1) width == 1.0 um.(error >)
18235 0 GRVNCAP3a: (M2 over VNCAPM2) width == 1.0 um.(error >)
18244 0 GRVNCAP3a: (M3 over VNCAPM3) width == 1.0 um.(error >)
18253 0 GRVNCAP3a: (M4 over VNCAPM4) width == 1.0 um.(error >)
18262 0 GRVNCAP3a: (M5 over VNCAPM5) width == 1.0 um.(error >)
18271 0 GRVNCAP3a: (MT over VNCAPMT) width == 1.0 um.(error >)
18278 0 GRVNCAP3a: (M1 over VNCAP_M1) width == 1.0 um.(error <)
18279 0 GRVNCAP3a: (M2 over VNCAP_M2) width == 1.0 um.(error <)
18280 0 GRVNCAP3a: (M3 over VNCAP_M3) width == 1.0 um.(error <)
18281 0 GRVNCAP3a: (M4 over VNCAP_M4) width == 1.0 um.(error <)
18282 0 GRVNCAP3a: (M5 over VNCAP_M5) width == 1.0 um.(error <)
18283 0 GRVNCAP3a: (MT over VNCAP_MT) width == 1.0 um.(error <)
18284 0 GRVNCAP4a: M1 over VNCAPM1 space (for common run length <= 0.36) == 0.40um (error <)
18285 0 GRVNCAP4a: M2 over VNCAPM2 space (for common run length <= 0.36) == 0.40um (error <)
18286 0 GRVNCAP4a: M3 over VNCAPM3 space (for common run length <= 0.36) == 0.40um (error <)
18287 0 GRVNCAP4a: M4 over VNCAPM4 space (for common run length <= 0.36) == 0.40um (error <)
18288 0 GRVNCAP4a: M5 over VNCAPM5 space (for common run length <= 0.36) == 0.40um (error <)
18289 0 GRVNCAP4a: MT over VNCAPMT space (for common run length <= 0.36) == 0.40um (error <)
18291 0 GRVNCAP4b: M1 over VNCAPM1 space (for common run length > 0.36) == 0.32um (error <)
18293 0 GRVNCAP4b: M2 over VNCAPM2 space (for common run length > 0.36) == 0.32um (error <)
18295 0 GRVNCAP4b: M3 over VNCAPM3 space (for common run length > 0.36) == 0.32um (error <)
18297 0 GRVNCAP4b: M4 over VNCAPM4 space (for common run length > 0.36) == 0.32um (error <)
18299 0 GRVNCAP4b: M5 over VNCAPM5 space (for common run length > 0.36) == 0.32um (error <)
18301 0 GRVNCAP4b: MT over VNCAPMT space (for common run length > 0.36) == 0.32um (error <)
18310 0 GRVNCAP4a: M1 over VNCAPM1 space (for common run length <= 0.36) == 0.40um (error >)
18319 0 GRVNCAP4a: M2 over VNCAPM2 space (for common run length <= 0.36) == 0.40um (error >)
18328 0 GRVNCAP4a: M3 over VNCAPM3 space (for common run length <= 0.36) == 0.40um (error >)
18337 0 GRVNCAP4a: M4 over VNCAPM4 space (for common run length <= 0.36) == 0.40um (error >)
18346 0 GRVNCAP4a: M5 over VNCAPM5 space (for common run length <= 0.36) == 0.40um (error >)
18355 0 GRVNCAP4a: MT over VNCAPMT space (for common run length <= 0.36) == 0.40um (error >)
18360 0 GRVNCAP4b: M1 over VNCAPM1 space (for common run length > 0.36) == 0.32um (error >)
18365 0 GRVNCAP4b: M2 over VNCAPM2 space (for common run length > 0.36) == 0.32um (error >)
18370 0 GRVNCAP4b: M3 over VNCAPM3 space (for common run length > 0.36) == 0.32um (error >)
18375 0 GRVNCAP4b: M4 over VNCAPM4 space (for common run length > 0.36) == 0.32um (error >)
18380 0 GRVNCAP4b: M5 over VNCAPM5 space (for common run length > 0.36) == 0.32um (error >)
18385 0 GRVNCAP4b: MT over VNCAPMT space (for common run length > 0.36) == 0.32um (error >)
18387 0 GRVNCAP6a: (V1 intersect VNCAPM1) space (different-net, edge to edge) > 0.46 um.
18389 0 GRVNCAP6a: (V2 intersect VNCAPM2) space (different-net, edge to edge) > 0.46 um.
18391 0 GRVNCAP6a: (V3 intersect VNCAPM3) space (different-net, edge to edge) > 0.46 um.
18393 0 GRVNCAP6a: (V4 intersect VNCAPM4) space (different-net, edge to edge) > 0.46 um.
18395 0 GRVNCAP6a: (V5 intersect VNCAPM5) space (different-net, edge to edge) > 0.46 um.
18397 0 GRVNCAP6a: (FT intersect VNCAPMT) space (different-net, edge to edge) > 0.46 um.
18398 0 GRVNCAP8a: (M1 intersect VNCAPM1) touching CA/CABAR found !
18401 0 GRVNCAP8b: ((M2 intersect VNCAPM2) not over VNCAPM1) touching V1 found !
18404 0 GRVNCAP8b: ((MT intersect VNCAPMT) not over VNCAPM1) touching V1 found !
18407 0 GRVNCAP8b: ((M3 intersect VNCAPM3) not over VNCAPM2) touching V2 found !
18410 0 GRVNCAP8b: ((MT intersect VNCAPMT) not over VNCAPM2) touching V2 found !
18413 0 GRVNCAP8b: ((M4 intersect VNCAPM4) not over VNCAPM3) touching V3 found !
18416 0 GRVNCAP8b: ((MT intersect VNCAPMT) not over VNCAPM3) touching V3 found !
18419 0 GRVNCAP8b: ((M5 intersect VNCAPM5) not over VNCAPM4) touching V4 found !
18422 0 GRVNCAP8b: ((MT intersect VNCAPMT) not over VNCAPM4) touching V4 found !
18425 0 GRVNCAP8b: ((MT intersect VNCAPMT) not over VNCAPM5) touching V5 found !
18428 0 GRVNCAP9a: ((M1 intersect VNCAPM1) not over VNCAPM2) touching V1 found !
18431 0 GRVNCAP9a: ((M1 intersect VNCAPM1) not over VNCAPMT) touching V1 found !
18434 0 GRVNCAP9a: ((M2 intersect VNCAPM2) not over VNCAPM3) touching V2 found !
18437 0 GRVNCAP9a: ((M2 intersect VNCAPM2) not over VNCAPMT) touching V2 found !
18440 0 GRVNCAP9a: ((M3 intersect VNCAPM3) not over VNCAPM4) touching V3 found !
18443 0 GRVNCAP9a: ((M3 intersect VNCAPM3) not over VNCAPMT) touching V3 found !
18446 0 GRVNCAP9a: ((M4 intersect VNCAPM4) not over VNCAPM5) touching V4 found !
18449 0 GRVNCAP9a: ((M4 intersect VNCAPM4) not over VNCAPMT) touching V4 found !
18452 0 GRVNCAP9a: ((M5 intersect VNCAPM5) not over VNCAPMT) touching V5 found !
18453 0 GRVNCAP9a: VNCAPMT touching FT not allowed !
18454 0 GRVNCAP9a: VNCAPMT touching FTBAR not allowed !
18456 0 GRVNCAP9b: ((M2 intersect VNCAPM2) touching {FT, FTBAR}) found !
18457 0 GRVNCAP9b: ((M3 intersect VNCAPM3) touching {FT, FTBAR}) found !
18458 0 GRVNCAP9b: ((M4 intersect VNCAPM4) touching {FT, FTBAR}) found !
18459 0 GRVNCAP9b: ((M5 intersect VNCAPM5) touching {FT, FTBAR}) found !
18460 0 GRVNCAP9b: ((MT intersect VNCAPMT) touching {FT, FTBAR}) found !
18461 0 GRVNCAP10: VNCAPM1 touching PCFUSE found !
18462 0 GRVNCAP10: VNCAPM2 touching PCFUSE found !
18463 0 GRVNCAP10: VNCAPM3 touching PCFUSE found !
18464 0 GRVNCAP10: VNCAPM4 touching PCFUSE found !
18465 0 GRVNCAP10: VNCAPM5 touching PCFUSE found !
18466 0 GRVNCAP10: VNCAPMT touching PCFUSE found !
18467 0 GRVNCAP10: VNCAPM1 touching K1 found !
18468 0 GRVNCAP10: VNCAPM2 touching K1 found !
18469 0 GRVNCAP10: VNCAPM3 touching K1 found !
18470 0 GRVNCAP10: VNCAPM4 touching K1 found !
18471 0 GRVNCAP10: VNCAPM5 touching K1 found !
18472 0 GRVNCAP10: VNCAPMT touching K1 found !
18473 0 GRVNCAP10: VNCAPM1 touching TLINE found !
18474 0 GRVNCAP10: VNCAPM2 touching TLINE found !
18475 0 GRVNCAP10: VNCAPM3 touching TLINE found !
18476 0 GRVNCAP10: VNCAPM4 touching TLINE found !
18477 0 GRVNCAP10: VNCAPM5 touching TLINE found !
18478 0 GRVNCAP10: VNCAPMT touching TLINE found !
18479 0 GRVNCAP10: VNCAPM1 touching BONDPAD found !
18480 0 GRVNCAP10: VNCAPM2 touching BONDPAD found !
18481 0 GRVNCAP10: VNCAPM3 touching BONDPAD found !
18482 0 GRVNCAP10: VNCAPM4 touching BONDPAD found !
18483 0 GRVNCAP10: VNCAPM5 touching BONDPAD found !
18484 0 GRVNCAP10: VNCAPMT touching BONDPAD found !
18485 0 GRVNCAP10: VNCAPM1 touching LOGOBND found !
18486 0 GRVNCAP10: VNCAPM2 touching LOGOBND found !
18487 0 GRVNCAP10: VNCAPM3 touching LOGOBND found !
18488 0 GRVNCAP10: VNCAPM4 touching LOGOBND found !
18489 0 GRVNCAP10: VNCAPM5 touching LOGOBND found !
18490 0 GRVNCAP10: VNCAPMT touching LOGOBND found !
18491 0 GRVNCAP10: VNCAPM1 touching IND_FILT found !
18492 0 GRVNCAP10: VNCAPM2 touching IND_FILT found !
18493 0 GRVNCAP10: VNCAPM3 touching IND_FILT found !
18494 0 GRVNCAP10: VNCAPM4 touching IND_FILT found !
18495 0 GRVNCAP10: VNCAPM5 touching IND_FILT found !
18496 0 GRVNCAP10: VNCAPMT touching IND_FILT found !
18497 0 GRVNCAP10: VNCAPM1 to adj. PCFUSE space >= 5.00 um.
18498 0 GRVNCAP10: VNCAPM2 to adj. PCFUSE space >= 5.00 um.
18499 0 GRVNCAP10: VNCAPM3 to adj. PCFUSE space >= 5.00 um.
18500 0 GRVNCAP10: VNCAPM4 to adj. PCFUSE space >= 5.00 um.
18501 0 GRVNCAP10: VNCAPM5 to adj. PCFUSE space >= 5.00 um.
18502 0 GRVNCAP10: VNCAPMT to adj. PCFUSE space >= 5.00 um.
18503 0 GRVNCAP10: VNCAPM1 to adj. K1 space >= 5.00 um.
18504 0 GRVNCAP10: VNCAPM2 to adj. K1 space >= 5.00 um.
18505 0 GRVNCAP10: VNCAPM3 to adj. K1 space >= 5.00 um.
18506 0 GRVNCAP10: VNCAPM4 to adj. K1 space >= 5.00 um.
18507 0 GRVNCAP10: VNCAPM5 to adj. K1 space >= 5.00 um.
18508 0 GRVNCAP10: VNCAPMT to adj. K1 space >= 5.00 um.
18509 0 GRVNCAP10: VNCAPM1 to adj. TLINE space >= 5.00 um.
18510 0 GRVNCAP10: VNCAPM2 to adj. TLINE space >= 5.00 um.
18511 0 GRVNCAP10: VNCAPM3 to adj. TLINE space >= 5.00 um.
18512 0 GRVNCAP10: VNCAPM4 to adj. TLINE space >= 5.00 um.
18513 0 GRVNCAP10: VNCAPM5 to adj. TLINE space >= 5.00 um.
18514 0 GRVNCAP10: VNCAPMT to adj. TLINE space >= 5.00 um.
18515 0 GRVNCAP10: VNCAPM1 to adj. BONDPAD space >= 5.00 um.
18516 0 GRVNCAP10: VNCAPM2 to adj. BONDPAD space >= 5.00 um.
18517 0 GRVNCAP10: VNCAPM3 to adj. BONDPAD space >= 5.00 um.
18518 0 GRVNCAP10: VNCAPM4 to adj. BONDPAD space >= 5.00 um.
18519 0 GRVNCAP10: VNCAPM5 to adj. BONDPAD space >= 5.00 um.
18520 0 GRVNCAP10: VNCAPMT to adj. BONDPAD space >= 5.00 um.
18521 0 GRVNCAP10: VNCAPM1 to adj. LOGOBND space >= 5.00 um.
18522 0 GRVNCAP10: VNCAPM2 to adj. LOGOBND space >= 5.00 um.
18523 0 GRVNCAP10: VNCAPM3 to adj. LOGOBND space >= 5.00 um.
18524 0 GRVNCAP10: VNCAPM4 to adj. LOGOBND space >= 5.00 um.
18525 0 GRVNCAP10: VNCAPM5 to adj. LOGOBND space >= 5.00 um.
18526 0 GRVNCAP10: VNCAPMT to adj. LOGOBND space >= 5.00 um.
18527 0 GRVNCAP10: VNCAPM1 to adj. IND_FILT space >= 5.00 um.
18528 0 GRVNCAP10: VNCAPM2 to adj. IND_FILT space >= 5.00 um.
18529 0 GRVNCAP10: VNCAPM3 to adj. IND_FILT space >= 5.00 um.
18530 0 GRVNCAP10: VNCAPM4 to adj. IND_FILT space >= 5.00 um.
18531 0 GRVNCAP10: VNCAPM4 to adj. IND_FILT space >= 5.00 um.
18532 0 GRVNCAP10: VNCAPMT to adj. IND_FILT space >= 5.00 um.
18534 0 GRVNCAP11b: (V2 over VNCAPM2) must be coincident with (V1 over VNCAPM1)
18536 0 GRVNCAP11b: (V3 over VNCAPM3) must be coincident with (V2 over VNCAPM2)
18538 0 GRVNCAP11b: (V4 over VNCAPM4) must be coincident with (V3 over VNCAPM3)
18540 0 GRVNCAP11b: (V5 over VNCAPM5) must be coincident with (V4 over VNCAPM4)
18542 0 GRVNCAP12: (M2 over VNCAPM2) must be coincident with (M1 over VNCAPM1)
18544 0 GRVNCAP12: (M3 over VNCAPM3) must be coincident with (M2 over VNCAPM2)
18546 0 GRVNCAP12: (M4 over VNCAPM4) must be coincident with (M3 over VNCAPM3)
18548 0 GRVNCAP12: (M5 over VNCAPM5) must be coincident with (M4 over VNCAPM4)
18550 0 GRVNCAP12: (MT over VNCAPMT) must be coincident with (M5 over VNCAPM5)
18555 0 GRVNCAP13: ((NW or BB) not touching (PC or RX)) overlap past (M1 over VNCAPM1) >= 5.0um.
18557 0 GRVNCAP13: ((NW or BB) not touching (PC or RX)) overlap past (M2 over VNCAPM2) >= 5.0um.
18559 0 GRVNCAP13: ((NW or BB) not touching (PC or RX)) overlap past (M3 over VNCAPM3) >= 5.0um.
18561 0 GRVNCAP13: ((NW or BB) not touching (PC or RX)) overlap past (M4 over VNCAPM4) >= 5.0um.
18563 0 GRVNCAP13: ((NW or BB) not touching (PC or RX)) overlap past (M5 over VNCAPM5) >= 5.0um.
18565 0 GRVNCAP13: ((NW or BB) not touching (PC or RX)) overlap past (MT over VNCAPMT) >= 5.0um.
18566 0 GRVNCAP15: (M1 intersect VNCAPM1) must be rectangular
18567 0 GRVNCAP15: (M2 intersect VNCAPM2) must be rectangular
18568 0 GRVNCAP15: (M3 intersect VNCAPM3) must be rectangular
18569 0 GRVNCAP15: (M4 intersect VNCAPM4) must be rectangular
18570 0 GRVNCAP15: (M5 intersect VNCAPM5) must be rectangular
18571 0 GRVNCAP15: (MT intersect VNCAPMT) must be rectangular
18578 0 GRVNCPM1: Union (VNCAP_Mx (x=1,2,3,4,5,T)) must enclose at least one VNCAP_PARM shape!
18580 0 GRVNCPM2: VNCAP_M1 must enclose one VNCAP_COUNT shape!
18582 0 GRVNCPM2: VNCAP_M2 must enclose one VNCAP_COUNT shape!
18584 0 GRVNCPM2: VNCAP_M3 must enclose one VNCAP_COUNT shape!
18586 0 GRVNCPM2: VNCAP_M4 must enclose one VNCAP_COUNT shape!
18588 0 GRVNCPM2: VNCAP_M5 must enclose one VNCAP_COUNT shape!
18590 0 GRVNCPM2: VNCAP_MT must enclose one VNCAP_COUNT shape!
18593 0 GR900a: LV(for C4's) must be within C4LV >= 0.000 um.
18594 0 GR900a: LV outside of C4LV found! (when C4 checking is selected)
18603 0 GR900b: C4LV must touch LV !
18604 0 GR900: LV(terminal via) diameter == 47.000 um.(error <)
18605 0 GR900: LV(terminal via) diameter == 47.000 um.(error >)
18613 0 GR900c: LV touching C4 must be octogonal !
18614 0 GR906: LV(C4 pad) not within {GUARDEDGE,(CHIPEDGE not touching GUARDEDGE)} found!
18615 0 GR907: LV(C4 pad) touching Chip Logo & PN (LOGBND) found!
18617 0 GR901: LV(C4 pad) to LV(C4 pad) space >= 153.000 um.
18619 0 GR902b: LV within AM >= 14.500 um.
18621 0 GR902b: LV within MA >= 14.500 um.
18623 0 GR902b: LV within ML >= 14.500 um.
18625 0 GR902b: LV within MZ >= 14.500 um.
18627 0 GR906: LV(C4 pad) within {GUARDEDGE,(CHIPEDGE not touching GUARDEDGE)} >= 86.000 um.
18628 0 GR907: LV(C4 pad) to Chip Logo & PN (LOGBND) >= 64.000 um.
18629 0 GRC4MX: Minimum C4's per chip should be >=3
18630 0 GRC4MN: Maximum C4's per chip should be <=9000
18637 0 GR911a: LVDUMMY must not touch LV !
18647 0 GR927: ({GUARDEDGE,(CHIPEDGE not touching GUARDEDGE)} not within LV or LVDUMMY size by 1500 found!
18650 0 GRBONDPAD1: BONDPAD overlap past LASTMETAL >= 0.100 um.
18654 0 GRBONDPAD3: LASTMETAL(over BONDPAD) not within (BB or PC) found!
18656 0 GRBONDPAD3: LASTMETAL(over BONDPAD) must be within BB >= 4.900 um.
18658 0 GRBONDPAD3: LASTMETAL(over BONDPAD) must be within PC >= 4.900 um.
18668 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching BP found!
18678 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching E1 found!
18688 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching K1 found!
18698 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching M1 found!
18708 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching M2 found!
18718 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching M3 found!
18728 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching M4 found!
18738 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching M5 found!
18748 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching MT found!
18758 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching NW found!
18768 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching RX found!
18778 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching NS found!
18779 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to BP space >= 4.900 um.
18780 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to E1 space >= 4.900 um.
18781 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to K1 space >= 4.900 um.
18782 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to M1 space >= 4.900 um.
18783 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to M2 space >= 4.900 um.
18784 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to M3 space >= 4.900 um.
18785 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to M4 space >= 4.900 um.
18786 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to M5 space >= 4.900 um.
18787 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to MT space >= 4.900 um.
18788 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to NW space >= 4.900 um.
18789 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to PC space >= 4.900 um.
18790 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to RX space >= 4.900 um.
18791 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to NS space >= 4.900 um.
18796 0 WARNING: YOU HAVE BOTH C4 AND WIREBOND PADS IN THIS DESIGN
18798 0 GRLEG_NOCS01: UNQUALIFIED_FEATURE: NOIBMCRACKSTOP level found in design. Contact your IBM technical representative.
18803 0 GRPILLAR00: UNQUALIFIED_FEATURE: CUPILLAR level found in design. Contact your IBM technical representative.
18814 0 GRLEG_NOCS02: If NOIBMCRACKSTOP exists, NOIBMCRACKSTOP must be drawn exactly coincident with CHIPEDGE.
18824 0 GRPILLAR01: If CUPILLAR exists, CUPILLAR must be drawn exactly coincident with {GUARDEDGE,(CHIPEDGE not touching GUARDEDGE)}
18826 0 NOTE: YOU HAVE BOTH C4 AND CUPILLAR PADS IN THIS DESIGN. PLEASE CONTACT IBM TECHNICAL SUPPORT FOR MULTI-PROJECT WAFER DESIGN!
18854 0 GRF20: M2FILL area <= 144.00 sq. um.
18855 0 GRF20: M3FILL area <= 144.00 sq. um.
18856 0 GRF20: M4FILL area <= 144.00 sq. um.
18857 0 GRF20: M5FILL area <= 144.00 sq. um.
18858 0 GRF20: MTFILL area <= 144.00 sq. um.
18859 0 GRF20: E1FILL area <= 144.00 sq. um.
18862 0 GR5VONLY01: If 5VONLY shape exists in the layout then all (PC over RX) shapes must be covered by TG
18876 0 GR5VONLY02: 5VONLY cannot exist in the same layout with any of the following levels {JC,AS,BP2ND,DG, DGV, SBD, JD, NR, PR, ZEROVT, (MOSVAR not over TG), SCHKY, BIPOLAR}
18878 0 GRPLYONCRK1: (PLYONCRK,5VONLY) wthin CHIPEDGE >=0.
18886 0 GRPLYONCRK2: (CHIPEDGE touching PLYONCRK) must touch 5VONLY shape.
18889 0 GRJS01: JS space >=0.64.
18890 0 GRJS02: JS width  >=0.52.
18891 0 GRJS02a: JS min area  >=2.60
18892 0 GRJS04: JS to adjacent RX >=0.14.
18894 0 GRJS05: JS overlap past JRX >= 0.14 um.
18895 0 GRJS06: JS must be within JC.
18896 0 GRJS11: JS cannot overlpa BP.
18897 0 GRJSPN001: JS straddling LOGOBND not allowed.
18898 0 GRAS11: AS minimum width >= 1.44 um !
18900 0 GRAS12: AS minimum space >= 0.50 um.
18902 0 GRAS12: AS minimum notch >= 0.50 um.
18906 0 GRAS14: AS enclosed area >= 0.387 sq.um.
18907 0 GRAS15: Non-orthogonal AS shapes found!
18911 0 GRAS16: [(PC over RX) over AS] must be rectangular
18920 0 GRAS17: AS must touch [(PC over RX) not touching {DG,NW,NR,TG,PR ZEROVT}]
18923 0 GRAS18a: AS touching (PC not touching RX) not allowed.
18925 0 GRAS18b: AS touching ({RX,PC} touching OP) not allowed.
18930 0 GRAS18c: AS touching (BP touching {OP,PCFUSE,RR,RP}) not allowed.
18941 0 GRAS18d: AS touching {BB,DG,TG,MOSVAR,(ZEROVT sized by 0.72)} not allowed.
18950 0 GRAS18e: AS touching {PR,NR,JD,RN,RR,RP,PD,OP,TG} not allowed.
18960 0 GRAS18f: AS touching {BFMOAT,BONDPAD,BPERI,DI,ESDUMMY,ESDRF,IND_FILT,SBLK,TLINE} not allowed.
18961 0 GRAS19a: AS over NW not allowed.
18962 0 GRAS19b: AS over BP not allowed.
18963 0 GRAS20a: AS to NW space >= 0.44 um.
18994 0 GRAS20b: AS must abut NW (point touching not allowed and the abutting run length must be >= 0.44 mm).
18996 0 GRAS20_or: Either {AS to NW space must be >= 0.44 um} or {AS must abut NW (point touching not allowed)}
18997 0 GRAS21a: AS to BP space >= 0.34 um.
19028 0 GRAS21b: AS must abut BP (point touching not allowed and the abutting run length must be >= 0.34 mm)
19030 0 GRAS21_or: Either {AS to BP space must be >= 0.34 um} or {AS must abut BP (point touching not allowed)}
19031 0 GRAS22a: AS to TG     space >= 0.44 um.
19032 0 GRAS22a: AS to DG     space >= 0.44 um.
19033 0 GRAS22a: AS to MOSVAR space >= 0.44 um.
19035 0 GRAS22b: AS to (BP touching PCFUSE) space >= 0.34 um.
19036 0 GRAS22c: AS to BB space >= 0.44 um.
19037 0 GRAS22d: AS to ZEROVT space >= 1.16 um.
19038 0 GRAS22e: AS to RN space >= 0.34 um.
19039 0 GRAS22f: AS to BH3 space >= 0.44 um.
19042 0 GRAS104: [(PC to PC) over AS] space >= 0.560 um.
19044 0 GRAS104: [(PC to PC) over AS] notch >= 0.560 um.
19045 0 GRAS353: RX straddling AS found!
19047 0 GRAS353: RX within AS >= 0.72 um.
19048 0 GRAS355: AS to RX space >= 0.72 um.
19050 0 GRAS357: BH to AS space >= 0.44 um.
19051 0 GRAS370: (PC over RX) to AS space >= 0.80 um.
19052 0 GRAS371: (PC over RX) straddling AS found!
19054 0 GRAS371: (PC over RX) within AS >= 0.90 um.
19055 0 GRAS942: DV terminal WB pad to AS >= 3.000 um.
19056 0 GRAS942: TV terminal WB pad to AS >= 3.000 um.
19057 0 GRAS951: DV terminal WB pad touching AS not allowed
19058 0 GRAS951: TV terminal WB pad touching AS not allowed
19059 0 GRAS990: BP in the chip guardring touching AS not allowed
19060 0 GRASPN001: AS shape straddling LOGOBND not allowed
19065 0 qtHt_err_chipedge: GRQCAP1c: (QT+HT) area >= 2000000 sq.um.
19080 0 GRNW5:  (PI not over NW) space (different net) >= 1.00 um
19087 0 GRDG13: DG touching NW, BB or BH
19088 0 GRDG13: DG to NW space >= 0.440 um.
19089 0 GRDG13: DG to BB space >= 0.440 um.
19090 0 GRDG13: DG to BH space >= 0.440 um.
19093 0 GRDG13: Layout will cause: DG to BH space >= 0.440 um.
19095 0 # INFO: CMRF-7sf ASSURA DRC DECK (REV DATE 12/18/2013) #
