*******************************************************************************
****** BUFFER_J schematic cmrf7sf_digital_layout  <vs>  BUFFER_J layout cmrf7sf_digital_layout
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(pfet) Generic                                    5       5
(nfet) Generic                                    5       5
                                             ------  ------
Total                                            10      10

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 5       5           5       5
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 5       5           5       5

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 5       5           2       2
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 5       5           2       2
                                             ------  ------      ------  ------
Total                                            10      10           4       4

*******************************************************************************
****** BUFFER_J schematic cmrf7sf_digital_layout  <vs>  BUFFER_J_VAR1 layout cmrf7sf_digital_layout
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(nfet) Generic                                    5       5
(pfet) Generic                                    5       5
                                             ------  ------
Total                                            10      10

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 5       5           5       5
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 5       5           5       5

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 5       5           2       2
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 5       5           2       2
                                             ------  ------      ------  ------
Total                                            10      10           4       4

*******************************************************************************
****** SRL schematic Julian_Shifts_And_Mux  <vs>  SRL layout Julian_Shifts_And_Mux
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(BUFFER_J schematic cmrf7sf_digit...) Cell        8       4*
                                             ------  ------
Total                                             8       4

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(BUFFER_J) Cell                                   8       8           8       8

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(BUFFER_J) Cell                                   8       8           8       8
                                             ------  ------      ------  ------
Total                                             8       8           8       8

Schematic and Layout Match
