0 0 dataAuditErrors
335 0 SBLK without OP
436 0 efuse device without bp
459 0 efuse device touching ns,rx,jd,pi,rn,nw,nr,pr,bb,dg,tg,rr,rp,pd,op
462 0 HAVAR device missing bb
479 0 HAVAR device touching pi,nw,nr,pr,dg,tg,pc,rr,rp,pd,op
518 0 SBD device without NS
519 0 NS straddling SBD device
530 0 SBD device touching jd,pi,nw,nr,pr,dg,tg,pc,rr,rp,op
554 0 SBDNW device must be covered by NW
566 0 SBDNW device touching ns,jd,pi,rn,nr,pr,dg,tg,pc,rr,rp,op
600 0 PSBD device touching ns,jd,rn,nr,pr,dg,tg,pc,rr,rp,op
601 0 PSBD device missing bb
632 0 DI Diode device without bp
646 0 DI Diode device touching ns,jd,pi,rn,nr,pr,bb,dg,tg,pc,rr,rp,pd,op
683 0 DIPI Diode device touching ns,jd,rn,nr,pr,bb,dg,rr,rp,pd,op
685 0 DIPI Diode device touching nw,bp
743 0 pcap device touching ns,jd,rn,nr,pr,bb,dg,rr,rp,pd,op
744 0 pcap device touching tg
749 0 N+ diffusion in pcap pwell found
788 0 vlnpn device touching ns,jd,rn,nr,pr,bb,dg,rr,rp,pd,op
827 0 mosvar device touching dg
869 0 P+ diffusion in ncap nwell found
890 0 mosvar or ncap device touching ns,jd,pi,rn,nr,pr,bp,rr,rp,pd,op
911 0 JFET device not over pi
941 0 JFET device touching ns,jd,rn,nr,pr,bb,dg,tg,pc,rr,rp,pd,op
1269 0 Dual gate poly device without M1/CA connection
1291 0 N+ Diffused Resistor device touching ns,nw,nr,pr
1475 0 FET device touching ns,jd,rn,bb,rr,rp,pd,op
1495 0 Diffused Resistor device touching bb,dg,pc
1504 0 Diffused Resistor device touching ns,jd,rn,pd,rr,rp,nr,pr
1586 0 Polysilicon Resistor device touching ns,jd,rx,rn,tg
1592 0 Polysilicon Resistor device not covered by P+ implant
1597 0 Polysilicon Resistor device BB touching pi,nw,nr,pr
1601 0 Polysilicon Resistor device RR or RP touching nr,pr
1723 0 (AM res) not covered by mask AM
1725 0 (MT res) not covered by mask MT
1727 0 (M4 res) not covered by mask M4
1729 0 (M3 res) not covered by mask M3
1731 0 (M2 res) not covered by mask M2
1733 0 (M1 res) not covered by mask M1
1812 0 Overlapping transmission lines - terminals must abut filters
1870 0 inductor device touching ns,jd,pi,rn,nw,nr,pr,dg,tg,pc,rr,rp,pd,op
1947 0 M3 and M4 inside enhanced Inductor model must have the same dimension as MT
1951 0 M3/M4 inside standard inductor model is not allowed
2045 0 Missing v3 vias on symind coils between m3 and m4
2048 0 Missing v4 vias on symind coils between m4 and mt
2051 0 Missing v3 vias on symind coils between m3 and m4
2054 0 Missing v4 vias on symind coils between m4 and mt
2057 0 Missing ft vias on symind coils between mt and am
2060 0 Missing ft vias on symind coils between mt and am
2063 0 Missing ft vias on ind coils between mt and am
2105 0 AM signal wire exiting symetrical inductor straddling metal coil outside the pin
2109 0 Center tap signal wire exiting symetrical inductor outside CT pin
2257 0 AM signal wire not exiting transmission line at port, shorted, or open
2278 0 M4 signal wire not exiting transmission line at port, shorted, or open
2296 0 MT signal wire not exiting transmission line at port, shorted, or open
2320 0 M3 signal wire not exiting transmission line at port, shorted, or open
2341 0 M2 signal wire not exiting transmission line at port, shorted, or open
2486 0 No FT via over HT
2487 0 No FT via over QT
2508 0 MODEL concern - K1 resistor not totally over STI substrate
2924 0 nw_StampErrorConnect
2928 0 nw_StampErrorFloat
2929 0 nw_StampErrorMult
2932 0 nw_StampErrorConnect
2936 0 nw_StampErrorFloat
2937 0 nw_StampErrorMult
2940 0 ncap_nw_StampErrorConnect
2944 0 ncap_nw_StampErrorFloat
2945 0 ncap_nw_StampErrorMult
2948 0 well_StampErrorConnect
2952 0 well_StampErrorFloat
2953 0 well_StampErrorMult
2956 0 pi_StampErrorConnect
2960 0 pi_StampErrorFloat
2961 0 pi_StampErrorMult
2964 0 pwell_StampErrorConnect
2968 0 pwell_StampErrorFloat
2969 0 pwell_StampErrorMult
2972 0 ns_StampErrorConnect
2976 0 ns_StampErrorFloat
2977 0 ns_StampErrorMult
2979 0 substrate_ptap_StampErrorCon
2984 0 substrate_StampErrorCon
2991 0 sub_sti_StampErrorCon
2996 0 sub1K_StampErrorConnect
3002 0 sub50_StampErrorConnect
3010 0 Mixed voltage net found : 3V3 or 5V diffusion is connected to 1.8V gate
3012 0 ptap connected to POWER net found !
3014 0 pwtap connected to POWER net found !
3019 0 forward biased ptie device found ! [tdpdnw/diodepnw] 
3024 0 forward biased ntie device found ! [tdndsx,tdndpw/diodenx,diodendpw] 
3026 0 NW ring not connected to a power net found !
10120 0 vlnpn collector not connected to nw_ring
13176 0 ###### SIX levels of metal M1-M2-M3-M4-MT-AM #####
14852 0 malformed device nfeti_dev
14853 0 malformed device nfeti_dev_psp
14854 0 malformed device nfeti_dev_b
14855 0 malformed device nfeti_dev_psp_b
14856 0 malformed device nfet6_dev
14857 0 malformed device nfet6_dev_psp
14858 0 malformed device nfet6_dev_b
14859 0 malformed device nfet6_dev_psp_b
14860 0 malformed device nfeti_dev_MV
14861 0 malformed device nfeti_dev_psp_MV
14862 0 malformed device nfet6_dev_MV
14863 0 malformed device nfet6_dev_psp_MV
14864 0 malformed device nfeti_dev_HV
14865 0 malformed device nfeti_dev_psp_HV
14866 0 malformed device nfet6_dev_HV
14867 0 malformed device nfet6_dev_psp_HV
14868 0 malformed device nfeti_dev_TG
14869 0 malformed device nfet6_dev_TG
14870 0 malformed device nfet_dpw
14871 0 malformed device nfet_dev
14872 0 malformed device nfet_dpw_psp
14873 0 malformed device nfet_dev_psp
14874 0 malformed device nfzv_dev
14875 0 malformed device nfzv_dev_HV
14876 0 malformed device nfet_dpw_MV
14877 0 malformed device nfet_dev_MV
14878 0 malformed device nfet_dpw_psp_MV
14879 0 malformed device nfet_dev_psp_MV
14880 0 malformed device nfet_dpw_HV
14881 0 malformed device nfet_dev_HV
14882 0 malformed device nfet_dpw_psp_HV
14883 0 malformed device nfet_dev_psp_HV
14884 0 malformed device nfet_dpw_TG
14885 0 malformed device nfet_dev_TG
14886 0 malformed device nfet_dev_HVT
14887 0 malformed device nfet_dev_HVT_b
14888 0 malformed device nfet_dpw_b
14889 0 malformed device nfet_dev_b
14890 0 malformed device nfet_dpw_psp_b
14891 0 malformed device nfet_dev_psp_b
14892 0 malformed device pfet_dev
14893 0 malformed device pfet_dev_psp
14894 0 malformed device pfet_dev_MV
14895 0 malformed device pfet_dev_psp_MV
14896 0 malformed device pfet_dev_HV
14897 0 malformed device pfet_dev_psp_HV
14898 0 malformed device pfet_dev_TG
14899 0 malformed device pfet_dev_SCG
14900 0 malformed device pfet_dev_HVT
14901 0 malformed device pfet_dev_HVT_b
14902 0 malformed device pfet_dev_b
14903 0 malformed device pfet_dev_psp_b
14904 0 malformed device nfeti_mul
14905 0 malformed device nfeti_mul_psp
14906 0 malformed device nfet6_mul
14907 0 malformed device nfet6_mul_psp
14908 0 malformed device nfeti_mul_MV
14909 0 malformed device nfeti_mul_psp_MV
14910 0 malformed device nfet6_mul_MV
14911 0 malformed device nfet6_mul_psp_MV
14912 0 malformed device nfeti_mul_HV
14913 0 malformed device nfeti_mul_psp_HV
14914 0 malformed device nfet6_mul_HV
14915 0 malformed device nfet6_mul_psp_HV
14916 0 malformed device nfeti_mul_TG
14917 0 malformed device nfet6_mul_TG
14919 0 malformed device nfet_mul
14921 0 malformed device nfet_mul_psp
14922 0 malformed device nfzv_mul
14923 0 malformed device nfzv_mul_HV
14925 0 malformed device nfet_mul_MV
14927 0 malformed device nfet_mul_psp_MV
14929 0 malformed device nfet_mul_HV
14931 0 malformed device nfet_mul_psp_HV
14933 0 malformed device nfet_mul_TG
14934 0 malformed device nfet_mul_HVT
14935 0 malformed device pfet_mul
14936 0 malformed device pfet_mul_psp
14937 0 malformed device pfet_mul_MV
14938 0 malformed device pfet_mul_psp_MV
14939 0 malformed device pfet_mul_HV
14940 0 malformed device pfet_mul_psp_HV
14941 0 malformed device pfet_mul_TG
14942 0 malformed device pfet_mul_SCG
14943 0 malformed device pfet_mul_HVT
14944 0 malformed device nfRFi_dev
14945 0 malformed device nfRFi_dev_psp
14946 0 malformed device nfRF6_dev
14947 0 malformed device nfRF6_dev_psp
14948 0 malformed device nfRFi_dev_MV
14949 0 malformed device nfRFi_dev_psp_MV
14950 0 malformed device nfRF6_dev_MV
14951 0 malformed device nfRF6_dev_psp_MV
14952 0 malformed device nfRFi_dev_HV
14953 0 malformed device nfRFi_dev_psp_HV
14954 0 malformed device nfRF6_dev_HV
14955 0 malformed device nfRF6_dev_psp_HV
14956 0 malformed device nfRFi_dev_TG
14957 0 malformed device nfRF6_dev_TG
14959 0 malformed device nfRF_dev
14961 0 malformed device nfRF_dev_psp
14963 0 malformed device nfRF_dev_MV
14965 0 malformed device nfRF_dev_psp_MV
14967 0 malformed device nfRF_dev_HV
14969 0 malformed device nfRF_dev_psp_HV
14971 0 malformed device nfRF_dev_TG
14972 0 malformed device pfRF_dev
14973 0 malformed device pfRF_dev_psp
14974 0 malformed device pfRF_dev_MV
14975 0 malformed device pfRF_dev_psp_MV
14976 0 malformed device pfRF_dev_HV
14977 0 malformed device pfRF_dev_psp_HV
14978 0 malformed device pfRF_dev_TG
14979 0 malformed device pfRF_dev_SCG
14980 0 malformed device nfRFi_mul
14981 0 malformed device nfRFi_mul_psp
14982 0 malformed device nfRF6_mul
14983 0 malformed device nfRF6_mul_psp
14984 0 malformed device nfRFi_mul_MV
14985 0 malformed device nfRFi_mul_psp_MV
14986 0 malformed device nfRF6_mul_MV
14987 0 malformed device nfRF6_mul_psp_MV
14988 0 malformed device nfRFi_mul_HV
14989 0 malformed device nfRFi_mul_psp_HV
14990 0 malformed device nfRF6_mul_HV
14991 0 malformed device nfRF6_mul_psp_HV
14992 0 malformed device nfRFi_mul_TG
14993 0 malformed device nfRF6_mul_TG
14995 0 malformed device nfRF_mul
14997 0 malformed device nfRF_mul_psp
14999 0 malformed device nfRF_mul_MV
15001 0 malformed device nfRF_mul_psp_MV
15003 0 malformed device nfRF_mul_HV
15005 0 malformed device nfRF_mul_psp_HV
15007 0 malformed device nfRF_mul_TG
15008 0 malformed device pfRF_mul
15009 0 malformed device pfRF_mul_psp
15010 0 malformed device pfRF_mul_MV
15011 0 malformed device pfRF_mul_psp_MV
15012 0 malformed device pfRF_mul_HV
15013 0 malformed device pfRF_mul_psp_HV
15014 0 malformed device pfRF_mul_TG
15015 0 malformed device pfRF_mul_SCG
15016 0 malformed device hvr_dev
15017 0 malformed device diffhavar_dev
15018 0 malformed device SBD
15019 0 malformed device SBDNW
15020 0 malformed device PSBD
15021 0 malformed device DI_diode
15022 0 malformed device DIPI_diode
15023 0 malformed device DI_VPNP
15024 0 malformed device ncap_dev
15025 0 malformed device ncap33_dev
15026 0 malformed device ncap50_dev
15027 0 malformed device diffmosvar_dev
15028 0 malformed device mosvar_dev
15029 0 malformed device mosvar50_dev
15030 0 malformed device p5pcdcap50_dev
15031 0 malformed device vlnpn_dev
15032 0 malformed device jfet_dev
15033 0 malformed device res_serpentine
15034 0 malformed device resnw_serpentine
15035 0 malformed device rnw6pc_dev
15037 0 malformed device res6pc_dev
15038 0 malformed device rnw6rr_dev
15040 0 malformed device res6rr_dev
15041 0 malformed device rnw6rp_dev
15043 0 malformed device res6rp_dev
15045 0 malformed device res6n_dev
15046 0 malformed device res6p_dev
15048 0 malformed device res6n_sblk
15049 0 malformed device res6p_sblk
15050 0 malformed device k1_dev_bb
15052 0 malformed device k1_dev_sx
15054 0 malformed device esdnsh_dev
15055 0 malformed device esdpsh_dev
15056 0 malformed device sub_dev
15058 0 malformed device ntie_device
15059 0 malformed device ptie_device
15060 0 malformed device corrPoint_dev_M2
15061 0 malformed device corrPoint_dev_PD
15062 0 malformed device corrPoint_dev_ND
15063 0 malformed device corrPoint_dev_PC
15064 0 malformed device corrPoint_dev_M1
15065 0 malformed device ESD_pdnw_diode
15066 0 malformed device ESD_pdnw_diode_GR_sized
15067 0 malformed device ESD_pdnw_diode_GR
15068 0 malformed device ESD_ndsx
15069 0 malformed device ESD_ndsx_GR_sized
15070 0 malformed device ESD_ndsx_GR
15071 0 malformed device MIMpi
15072 0 malformed device MIMnw
15073 0 malformed device MIMsx
15074 0 malformed device MIMhdpi
15075 0 malformed device MIMhdnw
15076 0 malformed device MIMhdsx
15077 0 malformed device MIMHKpi
15078 0 malformed device MIMHKnw
15079 0 malformed device MIMHKpc
15080 0 malformed device MIMHKsx
15081 0 malformed device DUALMIMpi
15082 0 malformed device DUALMIMnw
15083 0 malformed device DUALMIMsx
15084 0 malformed device DUALMIMhdpi
15085 0 malformed device DUALMIMhdnw
15086 0 malformed device DUALMIMhdsx
15088 0 malformed device vncap_top1
15089 0 malformed device vncap_tnw1
15091 0 malformed device vncap_topt
15092 0 malformed device vncap_tnwt
15094 0 malformed device vncap_top2
15095 0 malformed device vncap_tnw2
15097 0 malformed device vncap_top3
15098 0 malformed device vncap_tnw3
15100 0 malformed device vncap_top4
15101 0 malformed device vncap_tnw4
15102 0 malformed device am_transmission
15103 0 malformed device ind2_mtam_m1
15104 0 malformed device ind2_mtam_bb
15106 0 malformed device symind3_amam_bb
15108 0 malformed device symind3_amam_m1
15109 0 malformed device symind2_amam_bb
15110 0 malformed device symind2_amam_m1
15111 0 malformed device padOverDev
15112 0 malformed device bondPad_PC
15113 0 malformed device bondPad_BB
15114 0 malformed device efuse
15119 0 malformed device coupledA
15124 0 malformed device singleEndA
15128 0 malformed device coupledT
15132 0 malformed device singleEndT
15135 0 malformed device coupled4
15138 0 malformed device singleEnd4
15140 0 malformed device coupled3
15142 0 malformed device singleEnd3
15143 0 malformed device coupled2
15144 0 malformed device singleEnd2
15145 0 malformed device pdiode_dev
15146 0 malformed device ndiode_dev
15147 0 malformed device ndiode_dev
15148 0 malformed device nwdiode_dev1
15149 0 malformed device nwdiode_dev
15150 0 malformed device pwell_dev
15151 0 malformed device piwell_dev
17066 0 unstable device for piwell_dev_Device_319
17067 0 unpreserved device piwell_dev_Device_319
17068 0 unstable device for pwell_dev_Device_318
17069 0 unpreserved device pwell_dev_Device_318
17070 0 unstable device for nwdiode_dev_Device_317
17071 0 unpreserved device nwdiode_dev_Device_317
17072 0 unstable device for nwdiode_dev1_Device_316
17073 0 unpreserved device nwdiode_dev1_Device_316
17074 0 unstable device for ndiode_dev_Device_315
17075 0 unpreserved device ndiode_dev_Device_315
17076 0 unstable device for ndiode_dev_Device_314
17077 0 unpreserved device ndiode_dev_Device_314
17078 0 unstable device for pdiode_dev_Device_313
17079 0 unpreserved device pdiode_dev_Device_313
17080 0 unstable device for am_RES_min_Device_312
17081 0 unpreserved device am_RES_min_Device_312
17082 0 unstable device for m4_RES_min_Device_311
17083 0 unpreserved device m4_RES_min_Device_311
17084 0 unstable device for m4_RES_min_Device_309
17085 0 unpreserved device m4_RES_min_Device_309
17086 0 unstable device for m3_RES_min_Device_308
17087 0 unpreserved device m3_RES_min_Device_308
17088 0 unstable device for m3_RES_min_Device_306
17089 0 unpreserved device m3_RES_min_Device_306
17090 0 unstable device for m2_RES_min_Device_305
17091 0 unpreserved device m2_RES_min_Device_305
17092 0 unstable device for m2_RES_min_Device_303
17093 0 unpreserved device m2_RES_min_Device_303
17094 0 unstable device for mt_RES_min_Device_302
17095 0 unpreserved device mt_RES_min_Device_302
17096 0 unstable device for mt_RES_min_Device_300
17097 0 unpreserved device mt_RES_min_Device_300
17098 0 unstable device for m1_RES_min_Device_299
17099 0 unpreserved device m1_RES_min_Device_299
17100 0 unstable device for m1_RES_min_Device_297
17101 0 unpreserved device m1_RES_min_Device_297
17102 0 unstable device for singleEnd2_shield1
17103 0 unpreserved device singleEnd2_shield1
17104 0 unstable device for coupled2_shield1
17105 0 unpreserved device coupled2_shield1
17106 0 unstable device for singleEnd3_shield2
17107 0 unpreserved device singleEnd3_shield2
17108 0 unstable device for singleEnd3_shield1
17109 0 unpreserved device singleEnd3_shield1
17110 0 unstable device for coupled3_shield2
17111 0 unpreserved device coupled3_shield2
17112 0 unstable device for coupled3_shield1
17113 0 unpreserved device coupled3_shield1
17114 0 unstable device for singleEnd4_shield3
17115 0 unpreserved device singleEnd4_shield3
17116 0 unstable device for singleEnd4_shield2
17117 0 unpreserved device singleEnd4_shield2
17118 0 unstable device for singleEnd4_shield1
17119 0 unpreserved device singleEnd4_shield1
17120 0 unstable device for coupled4_shield3
17121 0 unpreserved device coupled4_shield3
17122 0 unstable device for coupled4_shield2
17123 0 unpreserved device coupled4_shield2
17124 0 unstable device for coupled4_shield1
17125 0 unpreserved device coupled4_shield1
17126 0 unstable device for singleEndT_shield4
17127 0 unpreserved device singleEndT_shield4
17128 0 unstable device for singleEndT_shield3
17129 0 unpreserved device singleEndT_shield3
17130 0 unstable device for singleEndT_shield2
17131 0 unpreserved device singleEndT_shield2
17132 0 unstable device for singleEndT_shield1
17133 0 unpreserved device singleEndT_shield1
17134 0 unstable device for coupledT_shield4
17135 0 unpreserved device coupledT_shield4
17136 0 unstable device for coupledT_shield3
17137 0 unpreserved device coupledT_shield3
17138 0 unstable device for coupledT_shield2
17139 0 unpreserved device coupledT_shield2
17140 0 unstable device for coupledT_shield1
17141 0 unpreserved device coupledT_shield1
17142 0 unstable device for singleEndA_shieldT
17143 0 unpreserved device singleEndA_shieldT
17144 0 unstable device for singleEndA_shield4
17145 0 unpreserved device singleEndA_shield4
17146 0 unstable device for singleEndA_shield3
17147 0 unpreserved device singleEndA_shield3
17148 0 unstable device for singleEndA_shield2
17149 0 unpreserved device singleEndA_shield2
17150 0 unstable device for singleEndA_shield1
17151 0 unpreserved device singleEndA_shield1
17152 0 unstable device for coupledA_shieldT
17153 0 unpreserved device coupledA_shieldT
17154 0 unstable device for coupledA_shield4
17155 0 unpreserved device coupledA_shield4
17156 0 unstable device for coupledA_shield3
17157 0 unpreserved device coupledA_shield3
17158 0 unstable device for coupledA_shield2
17159 0 unpreserved device coupledA_shield2
17160 0 unstable device for coupledA_shield1
17161 0 unpreserved device coupledA_shield1
17162 0 unstable device for efuse_Device_266
17163 0 unpreserved device efuse_Device_266
17164 0 unstable device for bondPad_BB_Device_265
17165 0 unpreserved device bondPad_BB_Device_265
17166 0 unstable device for bondPad_PC_Device_264
17167 0 unpreserved device bondPad_PC_Device_264
17168 0 unstable device for padOverDev_Device_263
17169 0 unpreserved device padOverDev_Device_263
17170 0 unstable device for symind2_amam_m1_Device_262
17171 0 unpreserved device symind2_amam_m1_Device_262
17172 0 unstable device for symind2_amam_bb_Device_261
17173 0 unpreserved device symind2_amam_bb_Device_261
17174 0 unstable device for symind3_amam_m1_Device_258
17175 0 unpreserved device symind3_amam_m1_Device_258
17176 0 unstable device for symind3_amam_m1_Device_260
17177 0 unpreserved device symind3_amam_m1_Device_260
17178 0 unstable device for symind3_amam_bb_Device_257
17179 0 unpreserved device symind3_amam_bb_Device_257
17180 0 unstable device for symind3_amam_bb_Device_259
17181 0 unpreserved device symind3_amam_bb_Device_259
17182 0 unstable device for ind2_mtam_bb_Device_256
17183 0 unpreserved device ind2_mtam_bb_Device_256
17184 0 unstable device for ind2_mtam_m1_Device_255
17185 0 unpreserved device ind2_mtam_m1_Device_255
17186 0 unstable device for am_transmission_Device_254
17187 0 unpreserved device am_transmission_Device_254
17188 0 unstable device for vncap_tnw4_Device_253
17189 0 unpreserved device vncap_tnw4_Device_253
17190 0 unstable device for vncap_top4_pwell
17191 0 unpreserved device vncap_top4_pwell
17192 0 unstable device for vncap_top4_subs
17193 0 unpreserved device vncap_top4_subs
17194 0 unstable device for vncap_tnw3_Device_250
17195 0 unpreserved device vncap_tnw3_Device_250
17196 0 unstable device for vncap_top3_pwell
17197 0 unpreserved device vncap_top3_pwell
17198 0 unstable device for vncap_top3_subs
17199 0 unpreserved device vncap_top3_subs
17200 0 unstable device for vncap_tnw2_Device_247
17201 0 unpreserved device vncap_tnw2_Device_247
17202 0 unstable device for vncap_top2_pwell
17203 0 unpreserved device vncap_top2_pwell
17204 0 unstable device for vncap_top2_subs
17205 0 unpreserved device vncap_top2_subs
17206 0 unstable device for vncap_tnwt_Device_244
17207 0 unpreserved device vncap_tnwt_Device_244
17208 0 unstable device for vncap_topt_pwell
17209 0 unpreserved device vncap_topt_pwell
17210 0 unstable device for vncap_topt_subs
17211 0 unpreserved device vncap_topt_subs
17212 0 unstable device for vncap_tnw1_Device_241
17213 0 unpreserved device vncap_tnw1_Device_241
17214 0 unstable device for vncap_top1_pwell
17215 0 unpreserved device vncap_top1_pwell
17216 0 unstable device for vncap_top1_subs
17217 0 unpreserved device vncap_top1_subs
17218 0 unstable device for DUALMIMhdsx_Device_238
17219 0 unpreserved device DUALMIMhdsx_Device_238
17220 0 unstable device for DUALMIMhdnw_Device_237
17221 0 unpreserved device DUALMIMhdnw_Device_237
17222 0 unstable device for DUALMIMhdpi_Device_236
17223 0 unpreserved device DUALMIMhdpi_Device_236
17224 0 unstable device for DUALMIMsx_Device_235
17225 0 unpreserved device DUALMIMsx_Device_235
17226 0 unstable device for DUALMIMnw_Device_234
17227 0 unpreserved device DUALMIMnw_Device_234
17228 0 unstable device for DUALMIMpi_Device_233
17229 0 unpreserved device DUALMIMpi_Device_233
17230 0 unstable device for MIMHKsx_Device_232
17231 0 unpreserved device MIMHKsx_Device_232
17232 0 unstable device for MIMHKpc_Device_231
17233 0 unpreserved device MIMHKpc_Device_231
17234 0 unstable device for MIMHKnw_Device_230
17235 0 unpreserved device MIMHKnw_Device_230
17236 0 unstable device for MIMHKpi_Device_229
17237 0 unpreserved device MIMHKpi_Device_229
17238 0 unstable device for MIMhdsx_Device_228
17239 0 unpreserved device MIMhdsx_Device_228
17240 0 unstable device for MIMhdnw_Device_227
17241 0 unpreserved device MIMhdnw_Device_227
17242 0 unstable device for MIMhdpi_Device_226
17243 0 unpreserved device MIMhdpi_Device_226
17244 0 unstable device for MIMsx_Device_225
17245 0 unpreserved device MIMsx_Device_225
17246 0 unstable device for MIMnw_Device_224
17247 0 unpreserved device MIMnw_Device_224
17248 0 unstable device for MIMpi_Device_223
17249 0 unpreserved device MIMpi_Device_223
17250 0 unstable device for ESD_ndsx_pi_Device_222
17251 0 unpreserved device ESD_ndsx_pi_Device_222
17252 0 unstable device for ESD_pdnw_pi_Device_221
17253 0 unpreserved device ESD_pdnw_pi_Device_221
17254 0 unstable device for ESD_ndsx_GR_Device_220
17255 0 unpreserved device ESD_ndsx_GR_Device_220
17256 0 unstable device for ESD_ndsx_GR_sized_Device_219
17257 0 unpreserved device ESD_ndsx_GR_sized_Device_219
17258 0 unstable device for ESD_ndsx_Device_218
17259 0 unpreserved device ESD_ndsx_Device_218
17260 0 unstable device for ESD_pdnw_diode_GR_Device_217
17261 0 unpreserved device ESD_pdnw_diode_GR_Device_217
17262 0 unstable device for ESD_pdnw_diode_GR_sized_Device_216
17263 0 unpreserved device ESD_pdnw_diode_GR_sized_Device_216
17264 0 unstable device for ESD_pdnw_diode_Device_215
17265 0 unpreserved device ESD_pdnw_diode_Device_215
17266 0 unstable device for corrPoint_dev_M1_Device_214
17267 0 unpreserved device corrPoint_dev_M1_Device_214
17268 0 unstable device for corrPoint_dev_PC_Device_213
17269 0 unpreserved device corrPoint_dev_PC_Device_213
17270 0 unstable device for corrPoint_dev_ND_Device_212
17271 0 unpreserved device corrPoint_dev_ND_Device_212
17272 0 unstable device for corrPoint_dev_PD_Device_211
17273 0 unpreserved device corrPoint_dev_PD_Device_211
17274 0 unstable device for corrPoint_dev_M2_Device_210
17275 0 unpreserved device corrPoint_dev_M2_Device_210
17276 0 unstable device for ptie_device_Device_209
17277 0 unpreserved device ptie_device_Device_209
17278 0 unstable device for ntie_device_Device_207
17279 0 unpreserved device ntie_device_Device_207
17280 0 unstable device for ntie_device_Device_208
17281 0 unpreserved device ntie_device_Device_208
17282 0 unstable device for sub_dev_Device_206
17283 0 unpreserved device sub_dev_Device_206
17284 0 unstable device for esdpsh_dev_Device_205
17285 0 unpreserved device esdpsh_dev_Device_205
17286 0 unstable device for esdnsh_dev_Device_203
17287 0 unpreserved device esdnsh_dev_Device_203
17288 0 unstable device for esdnsh_dev_Device_204
17289 0 unpreserved device esdnsh_dev_Device_204
17290 0 unstable device for k1_dev_sx_pwell
17291 0 unpreserved device k1_dev_sx_pwell
17292 0 unstable device for k1_dev_sx_subs
17293 0 unpreserved device k1_dev_sx_subs
17294 0 unstable device for k1_dev_bb_Device_200
17295 0 unpreserved device k1_dev_bb_Device_200
17296 0 unstable device for res6p_sblk_Device_199
17297 0 unpreserved device res6p_sblk_Device_199
17298 0 unstable device for res6n_sblk_pwell
17299 0 unpreserved device res6n_sblk_pwell
17300 0 unstable device for res6n_sblk_subs
17301 0 unpreserved device res6n_sblk_subs
17302 0 unstable device for res6p_dev_Device_196
17303 0 unpreserved device res6p_dev_Device_196
17304 0 unstable device for res6n_dev_pwell
17305 0 unpreserved device res6n_dev_pwell
17306 0 unstable device for res6n_dev_subs
17307 0 unpreserved device res6n_dev_subs
17308 0 unstable device for res6rp_dev_pwell
17309 0 unpreserved device res6rp_dev_pwell
17310 0 unstable device for res6rp_dev_subs
17311 0 unpreserved device res6rp_dev_subs
17312 0 unstable device for rnw6rp_dev_Device_191
17313 0 unpreserved device rnw6rp_dev_Device_191
17314 0 unstable device for res6rr_dev_pwell
17315 0 unpreserved device res6rr_dev_pwell
17316 0 unstable device for res6rr_dev_subs
17317 0 unpreserved device res6rr_dev_subs
17318 0 unstable device for rnw6rr_dev_Device_188
17319 0 unpreserved device rnw6rr_dev_Device_188
17320 0 unstable device for res6pc_dev_pwell
17321 0 unpreserved device res6pc_dev_pwell
17322 0 unstable device for res6pc_dev_subs
17323 0 unpreserved device res6pc_dev_subs
17324 0 unstable device for rnw6pc_dev_Device_185
17325 0 unpreserved device rnw6pc_dev_Device_185
17326 0 unstable device for resnw_serpentine_Device_184
17327 0 unpreserved device resnw_serpentine_Device_184
17328 0 unstable device for res_serpentine_Device_183
17329 0 unpreserved device res_serpentine_Device_183
17330 0 unstable device for jfet_dev_Device_182
17331 0 unpreserved device jfet_dev_Device_182
17332 0 unstable device for vlnpn_dev_Device_181
17333 0 unpreserved device vlnpn_dev_Device_181
17334 0 unstable device for pcap_dev_Device_180
17335 0 unpreserved device pcap_dev_Device_180
17336 0 unstable device for p5pcdcap50_dev_Device_179
17337 0 unpreserved device p5pcdcap50_dev_Device_179
17338 0 unstable device for mosvar50_dev_Device_178
17339 0 unpreserved device mosvar50_dev_Device_178
17340 0 unstable device for mosvar_dev_Device_177
17341 0 unpreserved device mosvar_dev_Device_177
17342 0 unstable device for diffmosvar_dev_Device_176
17343 0 unpreserved device diffmosvar_dev_Device_176
17344 0 unstable device for ncap50_dev_Device_175
17345 0 unpreserved device ncap50_dev_Device_175
17346 0 unstable device for ncap33_dev_Device_174
17347 0 unpreserved device ncap33_dev_Device_174
17348 0 unstable device for ncap_dev_Device_173
17349 0 unpreserved device ncap_dev_Device_173
17350 0 unstable device for DI_VPNP_Device_172
17351 0 unpreserved device DI_VPNP_Device_172
17352 0 unstable device for DIPI_diode_Device_171
17353 0 unpreserved device DIPI_diode_Device_171
17354 0 unstable device for DI_diode_Device_170
17355 0 unpreserved device DI_diode_Device_170
17356 0 unstable device for PSBD_Device_169
17357 0 unpreserved device PSBD_Device_169
17358 0 unstable device for SBDNW_Device_168
17359 0 unpreserved device SBDNW_Device_168
17360 0 unstable device for SBD_Device_167
17361 0 unpreserved device SBD_Device_167
17362 0 unstable device for diffhavar_dev_Device_166
17363 0 unpreserved device diffhavar_dev_Device_166
17364 0 unstable device for hvr_dev_Device_165
17365 0 unpreserved device hvr_dev_Device_165
17366 0 unstable device for pfRF_mul_SCG_Device_164
17367 0 unpreserved device pfRF_mul_SCG_Device_164
17368 0 unstable device for pfRF_mul_TG_Device_163
17369 0 unpreserved device pfRF_mul_TG_Device_163
17370 0 unstable device for pfRF_mul_psp_HV_Device_162
17371 0 unpreserved device pfRF_mul_psp_HV_Device_162
17372 0 unstable device for pfRF_mul_HV_Device_161
17373 0 unpreserved device pfRF_mul_HV_Device_161
17374 0 unstable device for pfRF_mul_psp_MV_Device_160
17375 0 unpreserved device pfRF_mul_psp_MV_Device_160
17376 0 unstable device for pfRF_mul_MV_Device_159
17377 0 unpreserved device pfRF_mul_MV_Device_159
17378 0 unstable device for pfRF_mul_psp_Device_158
17379 0 unpreserved device pfRF_mul_psp_Device_158
17380 0 unstable device for pfRF_mul_Device_157
17381 0 unpreserved device pfRF_mul_Device_157
17382 0 unstable device for nfRF_mul_TG_Device_155
17383 0 unpreserved device nfRF_mul_TG_Device_155
17384 0 unstable device for nfRF_mul_TG_Device_156
17385 0 unpreserved device nfRF_mul_TG_Device_156
17386 0 unstable device for nfRF_mul_psp_HV_Device_153
17387 0 unpreserved device nfRF_mul_psp_HV_Device_153
17388 0 unstable device for nfRF_mul_psp_HV_Device_154
17389 0 unpreserved device nfRF_mul_psp_HV_Device_154
17390 0 unstable device for nfRF_mul_HV_Device_151
17391 0 unpreserved device nfRF_mul_HV_Device_151
17392 0 unstable device for nfRF_mul_HV_Device_152
17393 0 unpreserved device nfRF_mul_HV_Device_152
17394 0 unstable device for nfRF_mul_psp_MV_Device_149
17395 0 unpreserved device nfRF_mul_psp_MV_Device_149
17396 0 unstable device for nfRF_mul_psp_MV_Device_150
17397 0 unpreserved device nfRF_mul_psp_MV_Device_150
17398 0 unstable device for nfRF_mul_MV_Device_147
17399 0 unpreserved device nfRF_mul_MV_Device_147
17400 0 unstable device for nfRF_mul_MV_Device_148
17401 0 unpreserved device nfRF_mul_MV_Device_148
17402 0 unstable device for nfRF_mul_psp_Device_145
17403 0 unpreserved device nfRF_mul_psp_Device_145
17404 0 unstable device for nfRF_mul_psp_Device_146
17405 0 unpreserved device nfRF_mul_psp_Device_146
17406 0 unstable device for nfRF_mul_Device_143
17407 0 unpreserved device nfRF_mul_Device_143
17408 0 unstable device for nfRF_mul_Device_144
17409 0 unpreserved device nfRF_mul_Device_144
17410 0 unstable device for nfRF6_mul_TG_Device_142
17411 0 unpreserved device nfRF6_mul_TG_Device_142
17412 0 unstable device for nfRFi_mul_TG_Device_141
17413 0 unpreserved device nfRFi_mul_TG_Device_141
17414 0 unstable device for nfRF6_mul_psp_HV_Device_140
17415 0 unpreserved device nfRF6_mul_psp_HV_Device_140
17416 0 unstable device for nfRF6_mul_HV_Device_139
17417 0 unpreserved device nfRF6_mul_HV_Device_139
17418 0 unstable device for nfRFi_mul_psp_HV_Device_138
17419 0 unpreserved device nfRFi_mul_psp_HV_Device_138
17420 0 unstable device for nfRFi_mul_HV_Device_137
17421 0 unpreserved device nfRFi_mul_HV_Device_137
17422 0 unstable device for nfRF6_mul_psp_MV_Device_136
17423 0 unpreserved device nfRF6_mul_psp_MV_Device_136
17424 0 unstable device for nfRF6_mul_MV_Device_135
17425 0 unpreserved device nfRF6_mul_MV_Device_135
17426 0 unstable device for nfRFi_mul_psp_MV_Device_134
17427 0 unpreserved device nfRFi_mul_psp_MV_Device_134
17428 0 unstable device for nfRFi_mul_MV_Device_133
17429 0 unpreserved device nfRFi_mul_MV_Device_133
17430 0 unstable device for nfRF6_mul_psp_Device_132
17431 0 unpreserved device nfRF6_mul_psp_Device_132
17432 0 unstable device for nfRF6_mul_Device_131
17433 0 unpreserved device nfRF6_mul_Device_131
17434 0 unstable device for nfRFi_mul_psp_Device_130
17435 0 unpreserved device nfRFi_mul_psp_Device_130
17436 0 unstable device for nfRFi_mul_Device_129
17437 0 unpreserved device nfRFi_mul_Device_129
17438 0 unstable device for pfRF_dev_SCG_Device_128
17439 0 unpreserved device pfRF_dev_SCG_Device_128
17440 0 unstable device for pfRF_dev_TG_Device_127
17441 0 unpreserved device pfRF_dev_TG_Device_127
17442 0 unstable device for pfRF_dev_psp_HV_Device_126
17443 0 unpreserved device pfRF_dev_psp_HV_Device_126
17444 0 unstable device for pfRF_dev_HV_Device_125
17445 0 unpreserved device pfRF_dev_HV_Device_125
17446 0 unstable device for pfRF_dev_psp_MV_Device_124
17447 0 unpreserved device pfRF_dev_psp_MV_Device_124
17448 0 unstable device for pfRF_dev_MV_Device_123
17449 0 unpreserved device pfRF_dev_MV_Device_123
17450 0 unstable device for pfRF_dev_psp_Device_122
17451 0 unpreserved device pfRF_dev_psp_Device_122
17452 0 unstable device for pfRF_dev_Device_121
17453 0 unpreserved device pfRF_dev_Device_121
17454 0 unstable device for nfRF_dev_TG_Device_119
17455 0 unpreserved device nfRF_dev_TG_Device_119
17456 0 unstable device for nfRF_dev_TG_Device_120
17457 0 unpreserved device nfRF_dev_TG_Device_120
17458 0 unstable device for nfRF_dev_psp_HV_Device_117
17459 0 unpreserved device nfRF_dev_psp_HV_Device_117
17460 0 unstable device for nfRF_dev_psp_HV_Device_118
17461 0 unpreserved device nfRF_dev_psp_HV_Device_118
17462 0 unstable device for nfRF_dev_HV_Device_115
17463 0 unpreserved device nfRF_dev_HV_Device_115
17464 0 unstable device for nfRF_dev_HV_Device_116
17465 0 unpreserved device nfRF_dev_HV_Device_116
17466 0 unstable device for nfRF_dev_psp_MV_Device_113
17467 0 unpreserved device nfRF_dev_psp_MV_Device_113
17468 0 unstable device for nfRF_dev_psp_MV_Device_114
17469 0 unpreserved device nfRF_dev_psp_MV_Device_114
17470 0 unstable device for nfRF_dev_MV_Device_111
17471 0 unpreserved device nfRF_dev_MV_Device_111
17472 0 unstable device for nfRF_dev_MV_Device_112
17473 0 unpreserved device nfRF_dev_MV_Device_112
17474 0 unstable device for nfRF_dev_psp_Device_109
17475 0 unpreserved device nfRF_dev_psp_Device_109
17476 0 unstable device for nfRF_dev_psp_Device_110
17477 0 unpreserved device nfRF_dev_psp_Device_110
17478 0 unstable device for nfRF_dev_Device_107
17479 0 unpreserved device nfRF_dev_Device_107
17480 0 unstable device for nfRF_dev_Device_108
17481 0 unpreserved device nfRF_dev_Device_108
17482 0 unstable device for nfRF6_dev_TG_Device_106
17483 0 unpreserved device nfRF6_dev_TG_Device_106
17484 0 unstable device for nfRFi_dev_TG_Device_105
17485 0 unpreserved device nfRFi_dev_TG_Device_105
17486 0 unstable device for nfRF6_dev_psp_HV_Device_104
17487 0 unpreserved device nfRF6_dev_psp_HV_Device_104
17488 0 unstable device for nfRF6_dev_HV_Device_103
17489 0 unpreserved device nfRF6_dev_HV_Device_103
17490 0 unstable device for nfRFi_dev_psp_HV_Device_102
17491 0 unpreserved device nfRFi_dev_psp_HV_Device_102
17492 0 unstable device for nfRFi_dev_HV_Device_101
17493 0 unpreserved device nfRFi_dev_HV_Device_101
17494 0 unstable device for nfRF6_dev_psp_MV_Device_100
17495 0 unpreserved device nfRF6_dev_psp_MV_Device_100
17496 0 unstable device for nfRF6_dev_MV_Device_99
17497 0 unpreserved device nfRF6_dev_MV_Device_99
17498 0 unstable device for nfRFi_dev_psp_MV_Device_98
17499 0 unpreserved device nfRFi_dev_psp_MV_Device_98
17500 0 unstable device for nfRFi_dev_MV_Device_97
17501 0 unpreserved device nfRFi_dev_MV_Device_97
17502 0 unstable device for nfRF6_dev_psp_Device_96
17503 0 unpreserved device nfRF6_dev_psp_Device_96
17504 0 unstable device for nfRF6_dev_Device_95
17505 0 unpreserved device nfRF6_dev_Device_95
17506 0 unstable device for nfRFi_dev_psp_Device_94
17507 0 unpreserved device nfRFi_dev_psp_Device_94
17508 0 unstable device for nfRFi_dev_Device_93
17509 0 unpreserved device nfRFi_dev_Device_93
17510 0 unstable device for pfet_mul_HVT_Device_92
17511 0 unpreserved device pfet_mul_HVT_Device_92
17512 0 unstable device for pfet_mul_SCG_Device_91
17513 0 unpreserved device pfet_mul_SCG_Device_91
17514 0 unstable device for pfet_mul_TG_Device_90
17515 0 unpreserved device pfet_mul_TG_Device_90
17516 0 unstable device for pfet_mul_psp_HV_Device_89
17517 0 unpreserved device pfet_mul_psp_HV_Device_89
17518 0 unstable device for pfet_mul_HV_Device_88
17519 0 unpreserved device pfet_mul_HV_Device_88
17520 0 unstable device for pfet_mul_psp_MV_Device_87
17521 0 unpreserved device pfet_mul_psp_MV_Device_87
17522 0 unstable device for pfet_mul_MV_Device_86
17523 0 unpreserved device pfet_mul_MV_Device_86
17524 0 unstable device for pfet_mul_psp_Device_85
17525 0 unpreserved device pfet_mul_psp_Device_85
17526 0 unstable device for pfet_mul_Device_84
17527 0 unpreserved device pfet_mul_Device_84
17528 0 unstable device for nfet_mul_HVT_Device_83
17529 0 unpreserved device nfet_mul_HVT_Device_83
17530 0 unstable device for nfet_mul_TG_Device_81
17531 0 unpreserved device nfet_mul_TG_Device_81
17532 0 unstable device for nfet_mul_TG_Device_82
17533 0 unpreserved device nfet_mul_TG_Device_82
17534 0 unstable device for nfet_mul_psp_HV_Device_79
17535 0 unpreserved device nfet_mul_psp_HV_Device_79
17536 0 unstable device for nfet_mul_psp_HV_Device_80
17537 0 unpreserved device nfet_mul_psp_HV_Device_80
17538 0 unstable device for nfet_mul_HV_Device_77
17539 0 unpreserved device nfet_mul_HV_Device_77
17540 0 unstable device for nfet_mul_HV_Device_78
17541 0 unpreserved device nfet_mul_HV_Device_78
17542 0 unstable device for nfet_mul_psp_MV_Device_75
17543 0 unpreserved device nfet_mul_psp_MV_Device_75
17544 0 unstable device for nfet_mul_psp_MV_Device_76
17545 0 unpreserved device nfet_mul_psp_MV_Device_76
17546 0 unstable device for nfet_mul_MV_Device_73
17547 0 unpreserved device nfet_mul_MV_Device_73
17548 0 unstable device for nfet_mul_MV_Device_74
17549 0 unpreserved device nfet_mul_MV_Device_74
17550 0 unstable device for nfzv_mul_HV_Device_72
17551 0 unpreserved device nfzv_mul_HV_Device_72
17552 0 unstable device for nfzv_mul_Device_71
17553 0 unpreserved device nfzv_mul_Device_71
17554 0 unstable device for nfet_mul_psp_Device_69
17555 0 unpreserved device nfet_mul_psp_Device_69
17556 0 unstable device for nfet_mul_psp_Device_70
17557 0 unpreserved device nfet_mul_psp_Device_70
17558 0 unstable device for nfet_mul_Device_67
17559 0 unpreserved device nfet_mul_Device_67
17560 0 unstable device for nfet_mul_Device_68
17561 0 unpreserved device nfet_mul_Device_68
17562 0 unstable device for nfet6_mul_TG_Device_66
17563 0 unpreserved device nfet6_mul_TG_Device_66
17564 0 unstable device for nfeti_mul_TG_Device_65
17565 0 unpreserved device nfeti_mul_TG_Device_65
17566 0 unstable device for nfet6_mul_psp_HV_Device_64
17567 0 unpreserved device nfet6_mul_psp_HV_Device_64
17568 0 unstable device for nfet6_mul_HV_Device_63
17569 0 unpreserved device nfet6_mul_HV_Device_63
17570 0 unstable device for nfeti_mul_psp_HV_Device_62
17571 0 unpreserved device nfeti_mul_psp_HV_Device_62
17572 0 unstable device for nfeti_mul_HV_Device_61
17573 0 unpreserved device nfeti_mul_HV_Device_61
17574 0 unstable device for nfet6_mul_psp_MV_Device_60
17575 0 unpreserved device nfet6_mul_psp_MV_Device_60
17576 0 unstable device for nfet6_mul_MV_Device_59
17577 0 unpreserved device nfet6_mul_MV_Device_59
17578 0 unstable device for nfeti_mul_psp_MV_Device_58
17579 0 unpreserved device nfeti_mul_psp_MV_Device_58
17580 0 unstable device for nfeti_mul_MV_Device_57
17581 0 unpreserved device nfeti_mul_MV_Device_57
17582 0 unstable device for nfet6_mul_psp_Device_56
17583 0 unpreserved device nfet6_mul_psp_Device_56
17584 0 unstable device for nfet6_mul_Device_55
17585 0 unpreserved device nfet6_mul_Device_55
17586 0 unstable device for nfeti_mul_psp_Device_54
17587 0 unpreserved device nfeti_mul_psp_Device_54
17588 0 unstable device for nfeti_mul_Device_53
17589 0 unpreserved device nfeti_mul_Device_53
17590 0 unstable device for pfet_dev_psp_b_Device_52
17591 0 unpreserved device pfet_dev_psp_b_Device_52
17592 0 unstable device for pfet_dev_b_Device_51
17593 0 unpreserved device pfet_dev_b_Device_51
17594 0 unstable device for pfet_dev_HVT_b_Device_50
17595 0 unpreserved device pfet_dev_HVT_b_Device_50
17596 0 unstable device for pfet_dev_HVT_Device_49
17597 0 unpreserved device pfet_dev_HVT_Device_49
17598 0 unstable device for pfet_dev_SCG_Device_48
17599 0 unpreserved device pfet_dev_SCG_Device_48
17600 0 unstable device for pfet_dev_TG_Device_47
17601 0 unpreserved device pfet_dev_TG_Device_47
17602 0 unstable device for pfet_dev_psp_HV_Device_46
17603 0 unpreserved device pfet_dev_psp_HV_Device_46
17604 0 unstable device for pfet_dev_HV_Device_45
17605 0 unpreserved device pfet_dev_HV_Device_45
17606 0 unstable device for pfet_dev_psp_MV_Device_44
17607 0 unpreserved device pfet_dev_psp_MV_Device_44
17608 0 unstable device for pfet_dev_MV_Device_43
17609 0 unpreserved device pfet_dev_MV_Device_43
17610 0 unstable device for pfet_dev_psp_Device_42
17611 0 unpreserved device pfet_dev_psp_Device_42
17612 0 unstable device for pfet_dev_Device_41
17613 0 unpreserved device pfet_dev_Device_41
17614 0 unstable device for nfet_dev_psp_b_Device_40
17615 0 unpreserved device nfet_dev_psp_b_Device_40
17616 0 unstable device for nfet_dpw_psp_b_Device_39
17617 0 unpreserved device nfet_dpw_psp_b_Device_39
17618 0 unstable device for nfet_dev_b_Device_38
17619 0 unpreserved device nfet_dev_b_Device_38
17620 0 unstable device for nfet_dpw_b_Device_37
17621 0 unpreserved device nfet_dpw_b_Device_37
17622 0 unstable device for nfet_dev_HVT_b_Device_36
17623 0 unpreserved device nfet_dev_HVT_b_Device_36
17624 0 unstable device for nfet_dev_HVT_Device_35
17625 0 unpreserved device nfet_dev_HVT_Device_35
17626 0 unstable device for nfet_dev_TG_Device_34
17627 0 unpreserved device nfet_dev_TG_Device_34
17628 0 unstable device for nfet_dpw_TG_Device_33
17629 0 unpreserved device nfet_dpw_TG_Device_33
17630 0 unstable device for nfet_dev_psp_HV_Device_32
17631 0 unpreserved device nfet_dev_psp_HV_Device_32
17632 0 unstable device for nfet_dpw_psp_HV_Device_31
17633 0 unpreserved device nfet_dpw_psp_HV_Device_31
17634 0 unstable device for nfet_dev_HV_Device_30
17635 0 unpreserved device nfet_dev_HV_Device_30
17636 0 unstable device for nfet_dpw_HV_Device_29
17637 0 unpreserved device nfet_dpw_HV_Device_29
17638 0 unstable device for nfet_dev_psp_MV_Device_28
17639 0 unpreserved device nfet_dev_psp_MV_Device_28
17640 0 unstable device for nfet_dpw_psp_MV_Device_27
17641 0 unpreserved device nfet_dpw_psp_MV_Device_27
17642 0 unstable device for nfet_dev_MV_Device_26
17643 0 unpreserved device nfet_dev_MV_Device_26
17644 0 unstable device for nfet_dpw_MV_Device_25
17645 0 unpreserved device nfet_dpw_MV_Device_25
17646 0 unstable device for nfzv_dev_HV_Device_24
17647 0 unpreserved device nfzv_dev_HV_Device_24
17648 0 unstable device for nfzv_dev_Device_23
17649 0 unpreserved device nfzv_dev_Device_23
17650 0 unstable device for nfet_dev_psp_Device_22
17651 0 unpreserved device nfet_dev_psp_Device_22
17652 0 unstable device for nfet_dpw_psp_Device_21
17653 0 unpreserved device nfet_dpw_psp_Device_21
17654 0 unstable device for nfet_dev_Device_20
17655 0 unpreserved device nfet_dev_Device_20
17656 0 unstable device for nfet_dpw_Device_19
17657 0 unpreserved device nfet_dpw_Device_19
17658 0 unstable device for nfet6_dev_TG_Device_18
17659 0 unpreserved device nfet6_dev_TG_Device_18
17660 0 unstable device for nfeti_dev_TG_Device_17
17661 0 unpreserved device nfeti_dev_TG_Device_17
17662 0 unstable device for nfet6_dev_psp_HV_Device_16
17663 0 unpreserved device nfet6_dev_psp_HV_Device_16
17664 0 unstable device for nfet6_dev_HV_Device_15
17665 0 unpreserved device nfet6_dev_HV_Device_15
17666 0 unstable device for nfeti_dev_psp_HV_Device_14
17667 0 unpreserved device nfeti_dev_psp_HV_Device_14
17668 0 unstable device for nfeti_dev_HV_Device_13
17669 0 unpreserved device nfeti_dev_HV_Device_13
17670 0 unstable device for nfet6_dev_psp_MV_Device_12
17671 0 unpreserved device nfet6_dev_psp_MV_Device_12
17672 0 unstable device for nfet6_dev_MV_Device_11
17673 0 unpreserved device nfet6_dev_MV_Device_11
17674 0 unstable device for nfeti_dev_psp_MV_Device_10
17675 0 unpreserved device nfeti_dev_psp_MV_Device_10
17676 0 unstable device for nfeti_dev_MV_Device_9
17677 0 unpreserved device nfeti_dev_MV_Device_9
17678 0 unstable device for nfet6_dev_psp_b_Device_8
17679 0 unpreserved device nfet6_dev_psp_b_Device_8
17680 0 unstable device for nfet6_dev_b_Device_7
17681 0 unpreserved device nfet6_dev_b_Device_7
17682 0 unstable device for nfet6_dev_psp_Device_6
17683 0 unpreserved device nfet6_dev_psp_Device_6
17684 0 unstable device for nfet6_dev_Device_5
17685 0 unpreserved device nfet6_dev_Device_5
17686 0 unstable device for nfeti_dev_psp_b_Device_4
17687 0 unpreserved device nfeti_dev_psp_b_Device_4
17688 0 unstable device for nfeti_dev_b_Device_3
17689 0 unpreserved device nfeti_dev_b_Device_3
17690 0 unstable device for nfeti_dev_psp_Device_2
17691 0 unpreserved device nfeti_dev_psp_Device_2
17692 0 unstable device for nfeti_dev_Device_1
17693 0 unpreserved device nfeti_dev_Device_1
